[
{'url': 'http://only-tv.org/animal-planet.html', 'img': 'http://only-tv.org/images/animpl.png', 'title': 'Animal Planet'},
{'url': 'http://only-tv.org/match-boets.html', 'img': 'http://only-tv.org/images/match_boetc.png', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87 \xd0\xb1\xd0\xbe\xd0\xb5\xd1\x86'},
{'url': 'http://only-tv.org/discovery.html', 'img': 'http://only-tv.org/images/discavery.png', 'title': 'Discovery Channel'},
{'url': 'http://only-tv.org/match-futbol-1.html', 'img': 'http://only-tv.org/images/mat_futbol1.png', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87 \xd1\x84\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 1'},
{'url': 'http://only-tv.org/tlc.html', 'img': 'http://only-tv.org/images/tlc.png', 'title': 'TLC'},
{'url': 'http://only-tv.org/kinohit.html', 'img': 'http://only-tv.org/images/kinohit.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x85\xd0\xb8\xd1\x82'},
{'url': 'http://only-tv.org/eurosport.html', 'img': 'http://only-tv.org/images/Eurosport.png', 'title': 'Eurosport 1'},
{'url': 'http://only-tv.org/cartoon-network.html', 'img': 'http://only-tv.org/images/cartoon_network.png', 'title': 'Cartoon Network'},
{'url': 'http://only-tv.org/match-tv.html', 'img': 'http://only-tv.org/images/matchtv.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87 \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/tv-3.html', 'img': 'http://only-tv.org/images/tv_3.png', 'title': '\xd1\x82\xd0\xb23'},
{'url': 'http://only-tv.org/dozhd.html', 'img': 'http://only-tv.org/images/dozhd.png', 'title': '\xd0\x94\xd0\xbe\xd0\xb6\xd0\xb4\xd1\x8c'},
{'url': 'http://only-tv.org/match-premer.html', 'img': 'http://only-tv.org/images/match-premer.png', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87 \xd0\xbf\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8c\xd0\xb5\xd1\x80'},
{'url': 'http://only-tv.org/khl-tv.html', 'img': 'http://only-tv.org/images/khl_tv.png', 'title': '\xd0\xba\xd1\x85\xd0\xbb \xd1\x82\xd0\xb2'},
{'url': 'http://only-tv.org/kinopremera.html', 'img': 'http://only-tv.org/images/kinopremera.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbf\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8c\xd0\xb5\xd1\x80\xd0\xb0'},
{'url': 'http://only-tv.org/eurosport-2.html', 'img': 'http://only-tv.org/images/eurosport_2.png', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 2'},
{'url': 'http://only-tv.org/match-futbol-2.html', 'img': 'http://only-tv.org/images/mat_futbol2.png', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87 \xd1\x84\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 2'},
{'url': 'http://only-tv.org/kinosemya.html', 'img': 'http://only-tv.org/images/kinosemya.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb5\xd0\xbc\xd1\x8c\xd1\x8f'},
{'url': 'http://only-tv.org/match-arena.html', 'img': 'http://only-tv.org/images/match_arena.png', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87 \xd0\xb0\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb0'},
{'url': 'http://only-tv.org/id-xtra.html', 'img': 'http://only-tv.org/images/id_xtra.png', 'title': 'ID Xtra'},
{'url': 'http://only-tv.org/boomerang.html', 'img': 'http://only-tv.org/images/boomerang.png', 'title': '\xd0\xb1\xd1\x83\xd0\xbc\xd0\xb5\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb3'},
{'url': 'http://only-tv.org/nash-detektiv.html', 'img': 'http://only-tv.org/images/nash-detektiv.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88 \xd0\x94\xd0\xb5\xd1\x82\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2'},
{'url': 'http://only-tv.org/kinopremium-hd.html', 'img': 'http://only-tv.org/images/kinopremium-hd.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\x9f\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb8\xd1\x83\xd0\xbc HD'},
{'url': 'http://only-tv.org/morskoj.html', 'img': 'http://only-tv.org/images/morskoj.png', 'title': '\xd0\xbc\xd0\xbe\xd1\x80\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9'},
{'url': 'http://only-tv.org/galaxy-tv.html', 'img': 'http://only-tv.org/images/galaxy.png', 'title': 'Galaxy TV'},
{'url': 'http://only-tv.org/tnt4.html', 'img': 'http://only-tv.org/images/tnt4.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa24'},
{'url': 'http://only-tv.org/tnt.html', 'img': 'http://only-tv.org/images/tnt.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2'},
{'url': 'http://only-tv.org/sts.html', 'img': 'http://only-tv.org/images/sts.png', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1'},
{'url': 'http://only-tv.org/novyj-kanal.html', 'img': 'http://only-tv.org/images/noviy.png', 'title': '\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'http://only-tv.org/english-club-tv.html', 'img': 'http://only-tv.org/images/eng_tv.png', 'title': 'English Club TV'},
{'url': 'http://only-tv.org/nickelodeon.html', 'img': 'http://only-tv.org/images/nick.png', 'title': 'Nickelodeon'},
{'url': 'http://only-tv.org/stb.html', 'img': 'http://only-tv.org/images/stb.png', 'title': '\xd0\xa1\xd0\xa2\xd0\x91'},
{'url': 'http://only-tv.org/rossiya-1.html', 'img': 'http://only-tv.org/images/russia_1.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 1'},
{'url': 'http://only-tv.org/kinomiks.html', 'img': 'http://only-tv.org/images/kinomiks.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbc\xd0\xb8\xd0\xba\xd1\x81'},
{'url': 'http://only-tv.org/amedia-hit.html', 'img': 'http://only-tv.org/images/amedia-hit.png', 'title': 'Amedia Hit'},
{'url': 'http://only-tv.org/tnt-music.html', 'img': 'http://only-tv.org/images/tnt-music.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2 Music'},
{'url': 'http://only-tv.org/mnogo-tv.html', 'img': 'http://only-tv.org/images/mnogotv.png', 'title': '\xd0\x9c\xd0\xbd\xd0\xbe\xd0\xb3\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/365-dnej.html', 'img': 'http://only-tv.org/images/365dney.png', 'title': '365 \xd0\x94\xd0\xbd\xd0\xb5\xd0\xb9'},
{'url': 'http://only-tv.org/amc.html', 'img': 'http://only-tv.org/images/amc.png', 'title': 'AMC'},
{'url': 'http://only-tv.org/mega.html', 'img': 'http://only-tv.org/images/mega.png', 'title': '\xd0\x9c\xd0\xb5\xd0\xb3\xd0\xb0'},
{'url': 'http://only-tv.org/tet.html', 'img': 'http://only-tv.org/images/tet.png', 'title': '\xd0\xa2\xd0\x95\xd0\xa2'},
{'url': 'http://only-tv.org/viasat-history.html', 'img': 'http://only-tv.org/images/viasat_his.png', 'title': 'Viasat History'},
{'url': 'http://only-tv.org/viasat-explorer.html', 'img': 'http://only-tv.org/images/viasat_ex.png', 'title': 'Viasat Explorer'},
{'url': 'http://only-tv.org/viasat-nature.html', 'img': 'http://only-tv.org/images/viasat_nat.png', 'title': 'Viasat Nature'},
{'url': 'http://only-tv.org/nlo-tv.html', 'img': 'http://only-tv.org/images/nlo_tv.png', 'title': '\xd0\x9d\xd0\x9b\xd0\x9e \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/futbol-1-ukraina.html', 'img': 'http://only-tv.org/images/football_1.png', 'title': '\xd1\x84\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 1'},
{'url': 'http://only-tv.org/ren.html', 'img': 'http://only-tv.org/images/ren_tv.png', 'title': '\xd0\xa0\xd0\x95\xd0\x9d \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/pervyj-kanal.html', 'img': 'http://only-tv.org/images/pervij.png', 'title': '\xd0\xbf\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9'},
{'url': 'http://only-tv.org/pyatnitsa-tv.html', 'img': 'http://only-tv.org/images/pyatnitsa.png', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd0\xbd\xd0\xb8\xd1\x86\xd0\xb0'},
{'url': 'http://only-tv.org/superkanal.html', 'img': 'http://only-tv.org/images/superkanal.png', 'title': '\xd0\xa1\xd1\x83\xd0\xbf\xd0\xb5\xd1\x80 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'http://only-tv.org/pyatyj-kanal.html', 'img': 'http://only-tv.org/images/5kanal.png', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'http://only-tv.org/kinosvidanie.html', 'img': 'http://only-tv.org/images/kinosvidanie.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb2\xd0\xb8\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'},
{'url': 'http://only-tv.org/match-futbol-3.html', 'img': 'http://only-tv.org/images/mat_futbol3.png', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87 \xd1\x84\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 3'},
{'url': 'http://only-tv.org/match-igra.html', 'img': 'http://only-tv.org/images/match-igra.png', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87 \xd0\xb8\xd0\xb3\xd1\x80\xd0\xb0'},
{'url': 'http://only-tv.org/match-planeta.html', 'img': 'http://only-tv.org/images/match-planeta.png', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87 \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'http://only-tv.org/match-nash-sport.html', 'img': 'http://only-tv.org/images/match-nash-sport.png', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87 \xd0\xbd\xd0\xb0\xd1\x88 \xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82'},
{'url': 'http://only-tv.org/discovery-science.html', 'img': 'http://only-tv.org/images/discovery-science.png', 'title': 'Discovery science'},
{'url': 'http://only-tv.org/dtx.html', 'img': 'http://only-tv.org/images/dtx.png', 'title': 'DTX'},
{'url': 'http://only-tv.org/trk-kiev.html', 'img': 'http://only-tv.org/images/kiev-tv.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xb5\xd0\xb2 \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/rodnoe-kino.html', 'img': 'http://only-tv.org/images/rodnoe-kino.png', 'title': '\xd0\xa0\xd0\xbe\xd0\xb4\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://only-tv.org/nashe-novoe-kino.html', 'img': 'http://only-tv.org/images/nashe-novoe-kino.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88\xd0\xb5 \xd0\xbd\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://only-tv.org/multimaniya.html', 'img': 'http://only-tv.org/images/multiman.png', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd0\xb8\xd0\xbc\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f'},
{'url': 'http://only-tv.org/nat-geo-wild.html', 'img': 'http://only-tv.org/images/natgeowild.png', 'title': 'Nat Geo Wild'},
{'url': 'http://only-tv.org/ru-tv.html', 'img': 'http://only-tv.org/images/rutv.png', 'title': 'RU TV'},
{'url': 'http://only-tv.org/kino-tv.html', 'img': 'http://only-tv.org/images/kinotv.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/nst.html', 'img': 'http://only-tv.org/images/nsttv.png', 'title': '\xd0\x9d\xd0\xa1\xd0\xa2'},
{'url': 'http://only-tv.org/tv-xxi.html', 'img': 'http://only-tv.org/images/TV_XXI.png', 'title': 'TV 21'},
{'url': 'http://only-tv.org/oruzhie.html', 'img': 'http://only-tv.org/images/oruzhie.png', 'title': '\xd0\x9e\xd1\x80\xd1\x83\xd0\xb6\xd0\xb8\xd0\xb5'},
{'url': 'http://only-tv.org/1-plus-1.html', 'img': 'http://only-tv.org/images/1_1.png', 'title': '1+1'},
{'url': 'http://only-tv.org/ictv.html', 'img': 'http://only-tv.org/images/ICTV.png', 'title': 'ICTV'},
{'url': 'http://only-tv.org/ntv.html', 'img': 'http://only-tv.org/images/ntv.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/domashnij.html', 'img': 'http://only-tv.org/images/domash.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc\xd0\xb0\xd1\x88\xd0\xbd\xd0\xb8\xd0\xb9'},
{'url': 'http://only-tv.org/24-tekhno.html', 'img': 'http://only-tv.org/images/24texno.png', 'title': '24 \xd1\x82\xd0\xb5\xd1\x85\xd0\xbd\xd0\xbe'},
{'url': 'http://only-tv.org/trk-ukraina.html', 'img': 'http://only-tv.org/images/trk_ukr.png', 'title': '\xd0\xa2\xd0\xa0\xd0\x9a \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'http://only-tv.org/disney.html', 'img': 'http://only-tv.org/images/Disney.png', 'title': 'disney'},
{'url': 'http://only-tv.org/inter.html', 'img': 'http://only-tv.org/images/inter.png', 'title': '\xd0\x98\xd0\xbd\xd1\x82\xd0\xb5\xd1\x80'},
{'url': 'http://only-tv.org/muz-tv.html', 'img': 'http://only-tv.org/images/muz_tv.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb7-\xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/otr.html', 'img': 'http://only-tv.org/images/otr.png', 'title': '\xd0\x9e\xd0\xa2\xd0\xa0'},
{'url': 'http://only-tv.org/russkaya-komediya.html', 'img': 'http://only-tv.org/images/russkaya-komediya.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd0\xba\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f'},
{'url': 'http://only-tv.org/mult.html', 'img': 'http://only-tv.org/images/mult.png', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82'},
{'url': 'http://only-tv.org/spike.html', 'img': 'http://only-tv.org/images/spike.png', 'title': 'Spike'},
{'url': 'http://only-tv.org/sts-love.html', 'img': 'http://only-tv.org/images/sts_love.png', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1 Love'},
{'url': 'http://only-tv.org/otse.html', 'img': 'http://only-tv.org/images/otse.png', 'title': '\xd0\x9e\xd0\xa6\xd0\x95'},
{'url': 'http://only-tv.org/2x2.html', 'img': 'http://only-tv.org/images/2x2.png', 'title': '2\xd1\x852'},
{'url': 'http://only-tv.org/kanal-che.html', 'img': 'http://only-tv.org/images/kanal_che.png', 'title': '\xd1\x87\xd0\xb5'},
{'url': 'http://only-tv.org/1hd.html', 'img': 'http://only-tv.org/images/1hd.png', 'title': '1HD'},
{'url': 'http://only-tv.org/komediya-tv.html', 'img': 'http://only-tv.org/images/kamedia.png', 'title': '\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/2-plus-2.html', 'img': 'http://only-tv.org/images/2plus2.png', 'title': '2+2'},
{'url': 'http://only-tv.org/football-2.html', 'img': 'http://only-tv.org/images/football_2.png', 'title': '\xd1\x84\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 2'},
{'url': 'http://only-tv.org/illyuzion-plus.html', 'img': 'http://only-tv.org/images/illyuzion.png', 'title': '\xd0\xb8\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd \xd0\xbf\xd0\xbb\xd1\x8e\xd1\x81'},
{'url': 'http://only-tv.org/ntn.html', 'img': 'http://only-tv.org/images/ntn.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x9d'},
{'url': 'http://only-tv.org/istoriya.html', 'img': 'http://only-tv.org/images/istoria.png', 'title': '\xd0\x98\xd1\x81\xd1\x82\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f'},
{'url': 'http://only-tv.org/history-channel.html', 'img': 'http://only-tv.org/images/history.png', 'title': 'History'},
{'url': 'http://only-tv.org/rossiya-24.html', 'img': 'http://only-tv.org/images/rossiya24.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 24'},
{'url': 'http://only-tv.org/zee-tv.html', 'img': 'http://only-tv.org/images/zee.png', 'title': 'zee tv'},
{'url': 'http://only-tv.org/bober-tv.html', 'img': 'http://only-tv.org/images/bober-tv.png', 'title': '\xd0\xb1\xd0\xbe\xd0\xb1\xd0\xb5\xd1\x80 \xd1\x82\xd0\xb2'},
{'url': 'http://only-tv.org/national-geographic.html', 'img': 'http://only-tv.org/images/natgeo.png', 'title': 'National Geographic'},
{'url': 'http://only-tv.org/ryzhij.html', 'img': 'http://only-tv.org/images/ryzhij.png', 'title': '\xd0\xa0\xd1\x8b\xd0\xb6\xd0\xb8\xd0\xb9'},
{'url': 'http://only-tv.org/moya-planeta.html', 'img': 'http://only-tv.org/images/my_planet.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x8f \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'http://only-tv.org/karusel.html', 'img': 'http://only-tv.org/images/karusel.png', 'title': '\xd0\x9a\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd0\xb5\xd0\xbb\xd1\x8c'},
{'url': 'http://only-tv.org/zvezda.html', 'img': 'http://only-tv.org/images/zvezda.png', 'title': '\xd0\x97\xd0\xb2\xd0\xb5\xd0\xb7\xd0\xb4\xd0\xb0'},
{'url': 'http://only-tv.org/sovershenno-sekretno.html', 'img': 'http://only-tv.org/images/sov_sec.png', 'title': '\xd0\xa1\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x80\xd1\x88\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xbe \xd1\x81\xd0\xb5\xd0\xba\xd1\x80\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe'},
{'url': 'http://only-tv.org/k1.html', 'img': 'http://only-tv.org/images/k1.png', 'title': '\xd0\x9a1'},
{'url': 'http://only-tv.org/k2.html', 'img': 'http://only-tv.org/images/k2.png', 'title': '\xd0\x9a2'},
{'url': 'http://only-tv.org/112-kanal.html', 'img': 'http://only-tv.org/images/112_kanal.png', 'title': '112'},
{'url': 'http://only-tv.org/russkij-illyuzion.html', 'img': 'http://only-tv.org/images/ruilluz.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\x98\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd'},
{'url': 'http://only-tv.org/nauka-2.html', 'img': 'http://only-tv.org/images/nauka-2.png', 'title': '\xd0\xbd\xd0\xb0\xd1\x83\xd0\xba\xd0\xb0 2.0'},
{'url': 'http://only-tv.org/a1.html', 'img': 'http://only-tv.org/images/a1.png', 'title': 'a1'},
{'url': 'http://only-tv.org/a2.html', 'img': 'http://only-tv.org/images/a2.png', 'title': 'a2'},
{'url': 'http://only-tv.org/amedia-premium-hd.html', 'img': 'http://only-tv.org/images/amedia_prem_hd.png', 'title': 'Amedia Premium HD'},
{'url': 'http://only-tv.org/tvc.html', 'img': 'http://only-tv.org/images/tvc.png', 'title': '\xd1\x82\xd0\xb2\xd1\x86'},
{'url': 'http://only-tv.org/rtr-planeta.html', 'img': 'http://only-tv.org/images/planet_rtr.png', 'title': '\xd0\xa0\xd0\xa2\xd0\xa0 \xd0\x9f\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'http://only-tv.org/paramount-comedy.html', 'img': 'http://only-tv.org/images/paramaund.png', 'title': 'Paramount Comedy'},
{'url': 'http://only-tv.org/rbk.html', 'img': 'http://only-tv.org/images/rbk.png', 'title': '\xd0\xa0\xd0\x91\xd0\x9a'},
{'url': 'http://only-tv.org/tlum-hd.html', 'img': 'http://only-tv.org/images/tlum-hd.png', 'title': '\xd0\xa2\xd0\xbb\xd1\x83\xd0\xbc HD'},
{'url': 'http://only-tv.org/moskva-24.html', 'img': 'http://only-tv.org/images/moskva_24.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0 24'},
{'url': 'http://only-tv.org/russkij-bestseller.html', 'img': 'http://only-tv.org/images/bestseller.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb1\xd0\xb5\xd1\x81\xd1\x82\xd1\x81\xd0\xb5\xd0\xbb\xd0\xbb\xd0\xb5\xd1\x80'},
{'url': 'http://only-tv.org/russkij-roman.html', 'img': 'http://only-tv.org/images/rusroman.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd'},
{'url': 'http://only-tv.org/russkij-detektiv.html', 'img': 'http://only-tv.org/images/rusdet.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb4\xd0\xb5\xd1\x82\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2'},
{'url': 'http://only-tv.org/mtv-russia.html', 'img': 'http://only-tv.org/images/mtvru.png', 'title': 'MTV \xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f'},
{'url': 'http://only-tv.org/russian-music-box.html', 'img': 'http://only-tv.org/images/rumusicbox.png', 'title': 'Russian Music Box'},
{'url': 'http://only-tv.org/europa-plus-tv.html', 'img': 'http://only-tv.org/images/europaplus.png', 'title': '\xd0\xb5\xd0\xb2\xd1\x80\xd0\xbe\xd0\xbf\xd0\xb0 \xd0\xbf\xd0\xbb\xd1\x8e\xd1\x81 \xd1\x82\xd0\xb2'},
{'url': 'http://only-tv.org/bigudi.html', 'img': 'http://only-tv.org/images/bigudi.png', 'title': '\xd0\x91\xd0\xb8\xd0\xb3\xd1\x83\xd0\xb4\xd0\xb8'},
{'url': 'http://only-tv.org/detskij.html', 'img': 'http://only-tv.org/images/detskii.png', 'title': '\xd0\xb4\xd0\xb5\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9'},
{'url': 'http://only-tv.org/avto-24.html', 'img': 'http://only-tv.org/images/auto24.png', 'title': '\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe 24'},
{'url': 'http://only-tv.org/auto-plus.html', 'img': 'http://only-tv.org/images/autoplus.png', 'title': '\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe \xd0\xbf\xd0\xbb\xd1\x8e\xd1\x81'},
{'url': 'http://only-tv.org/lya-minor.html', 'img': 'http://only-tv.org/images/laminor.png', 'title': '\xd0\x9b\xd1\x8f-\xd0\xbc\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x80'},
{'url': 'http://only-tv.org/shanson-tv.html', 'img': 'http://only-tv.org/images/shanson.png', 'title': '\xd0\xa8\xd0\xb0\xd0\xbd\xd1\x81\xd0\xbe\xd0\xbd \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/mir.html', 'img': 'http://only-tv.org/images/mir.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x80'},
{'url': 'http://only-tv.org/mezzo.html', 'img': 'http://only-tv.org/images/mezzo.png', 'title': 'Mezzo'},
{'url': 'http://only-tv.org/dom-kino.html', 'img': 'http://only-tv.org/images/domkino.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://only-tv.org/xsport.html', 'img': 'http://only-tv.org/images/xsport.png', 'title': 'XSport'},
{'url': 'http://only-tv.org/malyatko-tv.html', 'img': 'http://only-tv.org/images/malatko.png', 'title': '\xd0\x9c\xd0\xb0\xd0\xbb\xd1\x8f\xd1\x82\xd0\xba\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/bridge-tv.html', 'img': 'http://only-tv.org/images/bridge.png', 'title': '\xd0\xb1\xd1\x80\xd0\xb8\xd0\xb4\xd0\xb6 \xd1\x82\xd0\xb2'},
{'url': 'http://only-tv.org/muzhskoe-kino.html', 'img': 'http://only-tv.org/images/muzkino.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://only-tv.org/cnn.html', 'img': 'http://only-tv.org/images/cnn.png', 'title': 'CNN'},
{'url': 'http://only-tv.org/plus-plus.html', 'img': 'http://only-tv.org/images/plusplus.png', 'title': '\xd0\x9f\xd0\xbb\xd1\x8e\xd1\x81\xd0\x9f\xd0\xbb\xd1\x8e\xd1\x81'},
{'url': 'http://only-tv.org/russia-today.html', 'img': 'http://only-tv.org/images/rustoday.png', 'title': 'Russia Today'},
{'url': 'http://only-tv.org/kukhnya-tv.html', 'img': 'http://only-tv.org/images/kuhnia.png', 'title': '\xd0\x9a\xd1\x83\xd1\x85\xd0\xbd\xd1\x8f \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/muzhskoj.html', 'img': 'http://only-tv.org/images/muzskoi.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9'},
{'url': 'http://only-tv.org/8-kanal.html', 'img': 'http://only-tv.org/images/8_kanal.png', 'title': '8 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'http://only-tv.org/strashnoe-hd.html', 'img': 'http://only-tv.org/images/strahd.png', 'title': '\xd0\xa1\xd1\x82\xd1\x80\xd0\xb0\xd1\x88\xd0\xbd\xd0\xbe\xd0\xb5 HD'},
{'url': 'http://only-tv.org/kanal-you.html', 'img': 'http://only-tv.org/images/yootv.png', 'title': '\xd1\x8e'},
{'url': 'http://only-tv.org/kazsport.html', 'img': 'http://only-tv.org/images/kazsport.png', 'title': '\xd0\x9a\xd0\x90\xd0\x97\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82'},
{'url': 'http://only-tv.org/belarus-5.html', 'img': 'http://only-tv.org/images/bel5.png', 'title': '\xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c 5'},
{'url': 'http://only-tv.org/okhota-i-rybalka.html', 'img': 'http://only-tv.org/images/ohrib.png', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xb0 \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xb0\xd0\xbb\xd0\xba\xd0\xb0'},
{'url': 'http://only-tv.org/zik.html', 'img': 'http://only-tv.org/images/zik.png', 'title': 'ZIK'},
{'url': 'http://only-tv.org/drajv-tv.html', 'img': 'http://only-tv.org/images/drajv-tv.png', 'title': '\xd0\xb4\xd1\x80\xd0\xb0\xd0\xb9\xd0\xb2 \xd1\x82\xd0\xb2'},
{'url': 'http://only-tv.org/rossiya-kultura.html', 'img': 'http://only-tv.org/images/rukultura.png', 'title': '\xd1\x80\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f \xd0\xba (\xd0\xba\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd1\x83\xd1\x80\xd0\xb0)'},
{'url': 'http://only-tv.org/okhotnik-i-rybolov.html', 'img': 'http://only-tv.org/images/ohotnik.png', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2'},
{'url': 'http://only-tv.org/euronews.html', 'img': 'http://only-tv.org/images/EuroNews.png', 'title': 'EuroNews'},
{'url': 'http://only-tv.org/newsone.html', 'img': 'http://only-tv.org/images/newsone.png', 'title': 'News One'},
{'url': 'http://only-tv.org/24-ukraina.html', 'img': 'http://only-tv.org/images/24_ukr.png', 'title': '24 \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'http://only-tv.org/espreso-tv.html', 'img': 'http://only-tv.org/images/espresotv.png', 'title': '\xd0\x95\xd1\x81\xd0\xbf\xd1\x80\xd0\xb5\xd1\x81\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/5-kanal-ukraina.html', 'img': 'http://only-tv.org/images/5_ukr.png', 'title': '5 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'http://only-tv.org/gromadske-tv.html', 'img': 'http://only-tv.org/images/gromadske-tv.png', 'title': '\xd0\x93\xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xb4\xd1\x81\xd1\x8c\xd0\xba\xd0\xb5 \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/ostrosyuzhetnoe-hd.html', 'img': 'http://only-tv.org/images/ostrotv.png', 'title': '\xd0\x9e\xd1\x81\xd1\x82\xd1\x80\xd0\xbe\xd1\x81\xd1\x8e\xd0\xb6\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe\xd0\xb5 HD'},
{'url': 'http://only-tv.org/nash-kinoroman.html', 'img': 'http://only-tv.org/images/nash-kinoroman.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88 \xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd'},
{'url': 'http://only-tv.org/evrokino.html', 'img': 'http://only-tv.org/images/eukino.png', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://only-tv.org/sport-1-ukraina.html', 'img': 'http://only-tv.org/images/sport1ukr.png', 'title': '\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 1 \xd1\x83\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'http://only-tv.org/sport-2-ukraina.html', 'img': 'http://only-tv.org/images/sport2ukr.png', 'title': '\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 2 \xd1\x83\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'http://only-tv.org/boks-tv.html', 'img': 'http://only-tv.org/images/boxtv.png', 'title': '\xd0\x91\xd0\xbe\xd0\xba\xd1\x81 \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/24-dok.html', 'img': 'http://only-tv.org/images/24dok.png', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\x94\xd0\xbe\xd0\xba\xd1\x82\xd0\xbe\xd1\x80'},
{'url': 'http://only-tv.org/indiya-tv.html', 'img': 'http://only-tv.org/images/indiatv.png', 'title': '\xd0\x98\xd0\xbd\xd0\xb4\xd0\xb8\xd1\x8f \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/nano-tv.html', 'img': 'http://only-tv.org/images/nanotv.png', 'title': '\xd0\x9d\xd0\xb0\xd0\xbd\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/feniks-kino.html', 'img': 'http://only-tv.org/images/feniks.png', 'title': '\xd1\x84\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xba\xd1\x81 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://only-tv.org/tiji.html', 'img': 'http://only-tv.org/images/tiji.png', 'title': 'Tiji'},
{'url': 'http://only-tv.org/gulli.html', 'img': 'http://only-tv.org/images/gulli.png', 'title': 'gulli'},
{'url': 'http://only-tv.org/radost-moya.html', 'img': 'http://only-tv.org/images/radostmy.png', 'title': '\xd0\xa0\xd0\xb0\xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c \xd0\xbc\xd0\xbe\xd1\x8f'},
{'url': 'http://only-tv.org/fine-living.html', 'img': 'http://only-tv.org/images/fine-living.png', 'title': 'Fine Living'},
{'url': 'http://only-tv.org/telekanal-futbol.html', 'img': 'http://only-tv.org/images/telfut.png', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb'},
{'url': 'http://only-tv.org/mgm.html', 'img': 'http://only-tv.org/images/mgm.png', 'title': 'MGM'},
{'url': 'http://only-tv.org/russkij-ekstrim.html', 'img': 'http://only-tv.org/images/ruekstrim.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xad\xd0\xba\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd0\xbc'},
{'url': 'http://only-tv.org/eda-tv.html', 'img': 'http://only-tv.org/images/edatv.png', 'title': '\xd0\x95\xd0\x94\xd0\x90 HD'},
{'url': 'http://only-tv.org/setanta-sports.html', 'img': 'http://only-tv.org/images/setanta.png', 'title': '\xd0\xa1\xd0\xb5\xd1\x82\xd0\xb0\xd0\xbd\xd1\x82\xd0\xb0 \xd0\xa1\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82'},
{'url': 'http://only-tv.org/piksel.html', 'img': 'http://only-tv.org/images/piksel.png', 'title': '\xd0\xbf\xd0\xb8\xd0\xba\xd1\x81\xd0\xb5\xd0\xbb\xd1\x8c'},
{'url': 'http://only-tv.org/travel-channel.html', 'img': 'http://only-tv.org/images/travel-channel.png', 'title': 'Travel Channel'},
{'url': 'http://only-tv.org/m1.html', 'img': 'http://only-tv.org/images/m1.png', 'title': '\xd0\x9c1'},
{'url': 'http://only-tv.org/m2.html', 'img': 'http://only-tv.org/images/m2.png', 'title': '\xd0\x9c2'},
{'url': 'http://only-tv.org/hardlife-tv.html', 'img': 'http://only-tv.org/images/hardlife-tv.png', 'title': 'HardLife TV'},
{'url': 'http://only-tv.org/outdoor-channel.html', 'img': 'http://only-tv.org/images/outdoor.png', 'title': 'Outdoor Channel'},
{'url': 'http://only-tv.org/nick-jr.html', 'img': 'http://only-tv.org/images/nickjr.png', 'title': 'Nick Jr'},
{'url': 'http://only-tv.org/vh1.html', 'img': 'http://only-tv.org/images/vh1.png', 'title': 'VH1'},
{'url': 'http://only-tv.org/travel-and-adventure.html', 'img': 'http://only-tv.org/images/travadv.png', 'title': 'travel and adventure'},
{'url': 'http://only-tv.org/krym-1.html', 'img': 'http://only-tv.org/images/krym1.png', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\x9a\xd1\x80\xd1\x8b\xd0\xbc\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9'},
{'url': 'http://only-tv.org/setanta-sports-plus.html', 'img': 'http://only-tv.org/images/setanta-sports-plus.png', 'title': 'setanta sports plus'},
{'url': 'http://only-tv.org/zhivi.html', 'img': 'http://only-tv.org/images/zhivi.png', 'title': '\xd0\x96\xd0\xb8\xd0\xb2\xd0\xb8'},
{'url': 'http://only-tv.org/bbc-news.html', 'img': 'http://only-tv.org/images/bbcnews.png', 'title': 'BBC News'},
{'url': 'http://only-tv.org/mama.html', 'img': 'http://only-tv.org/images/mama.png', 'title': '\xd0\xbc\xd0\xb0\xd0\xbc\xd0\xb0'},
{'url': 'http://only-tv.org/fox.html', 'img': 'http://only-tv.org/images/fox.png', 'title': 'FOX'},
{'url': 'http://only-tv.org/fox-life.html', 'img': 'http://only-tv.org/images/foxlife.png', 'title': 'Fox Life'},
{'url': 'http://only-tv.org/sony-sci-fi.html', 'img': 'http://only-tv.org/images/sonyscifi.png', 'title': 'Sony Sci-Fi'},
{'url': 'http://only-tv.org/sony-turbo.html', 'img': 'http://only-tv.org/images/sony-turbo.png', 'title': 'Sony Turbo'},
{'url': 'http://only-tv.org/set.html', 'img': 'http://only-tv.org/images/set.png', 'title': 'SET'},
{'url': 'http://only-tv.org/nostalgiya.html', 'img': 'http://only-tv.org/images/nostalgiya.png', 'title': '\xd0\x9d\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xb3\xd0\xb8\xd1\x8f'},
{'url': 'http://only-tv.org/kanal-strana.html', 'img': 'http://only-tv.org/images/multimuz.png', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd0\xb8\xd0\xbc\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0'},
{'url': 'http://only-tv.org/360-gradusov.html', 'img': 'http://only-tv.org/images/360grad.png', 'title': '360 \xd0\xb3\xd1\x80\xd0\xb0\xd0\xb4\xd1\x83\xd1\x81\xd0\xbe\xd0\xb2'},
{'url': 'http://only-tv.org/sarafan-tv.html', 'img': 'http://only-tv.org/images/sarafan.png', 'title': '\xd1\x81\xd0\xb0\xd1\x80\xd0\xb0\xd1\x84\xd0\xb0\xd0\xbd \xd1\x82\xd0\xb2'},
{'url': 'http://only-tv.org/tdk.html', 'img': 'http://only-tv.org/images/tdk.png', 'title': '\xd0\xa2\xd0\x94\xd0\x9a'},
{'url': 'http://only-tv.org/konnyj-mir.html', 'img': 'http://only-tv.org/images/konnyj-mir.png', 'title': '\xd0\x9a\xd0\xbe\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\xbc\xd0\xb8\xd1\x80'},
{'url': 'http://only-tv.org/yumor-tv.html', 'img': 'http://only-tv.org/images/yumor.png', 'title': '\xd0\xae\xd0\xbc\xd0\xbe\xd1\x80 \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/kinopokaz.html', 'img': 'http://only-tv.org/images/kinopokaz.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbf\xd0\xbe\xd0\xba\xd0\xb0\xd0\xb7'},
{'url': 'http://only-tv.org/krym-24.html', 'img': 'http://only-tv.org/images/krym24.png', 'title': '\xd0\x9a\xd1\x80\xd1\x8b\xd0\xbc 24'},
{'url': 'http://only-tv.org/krasnaya-liniya.html', 'img': 'http://only-tv.org/images/krasnaya-liniya.png', 'title': '\xd0\x9a\xd1\x80\xd0\xb0\xd1\x81\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xbb\xd0\xb8\xd0\xbd\xd0\xb8\xd1\x8f'},
{'url': 'http://only-tv.org/bollywood.html', 'img': 'http://only-tv.org/images/bollywood.png', 'title': 'Bollywood'},
{'url': 'http://only-tv.org/tochka-tv.html', 'img': 'http://only-tv.org/images/tochkatv.png', 'title': '\xd0\xa2\xd0\xbe\xd1\x87\xd0\xba\xd0\xb0 \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/extreme-sports.html', 'img': 'http://only-tv.org/images/extreme-sports.png', 'title': 'Extreme Sports'},
{'url': 'http://only-tv.org/kanal-o.html', 'img': 'http://only-tv.org/images/kanal-o.png', 'title': '\xd0\xbe!'},
{'url': 'http://only-tv.org/mir-seriala.html', 'img': 'http://only-tv.org/images/mir-seriala.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x80 \xd1\x81\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb\xd0\xb0'},
{'url': 'http://only-tv.org/paramount-channel.html', 'img': 'http://only-tv.org/images/paramount-channel.png', 'title': 'Paramount Channel'},
{'url': 'http://only-tv.org/vesti-fm.html', 'img': 'http://only-tv.org/images/radio/radio-vesti-fm.png', 'title': '\xd0\x92\xd0\xb5\xd1\x81\xd1\x82\xd0\xb8 \xd0\xa4\xd0\x9c'},
{'url': 'http://only-tv.org/kinopokaz-hd1.html', 'img': 'http://only-tv.org/images/kinopokaz-hd1.png', 'title': '\xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbf\xd0\xbe\xd0\xba\xd0\xb0\xd0\xb7 hd1'},
{'url': 'http://only-tv.org/kinopokaz-hd2.html', 'img': 'http://only-tv.org/images/kinopokaz-hd2.png', 'title': '\xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbf\xd0\xbe\xd0\xba\xd0\xb0\xd0\xb7 hd2'},
{'url': 'http://only-tv.org/world-fashion.html', 'img': 'http://only-tv.org/images/world-fashion.png', 'title': 'World Fashion'},
{'url': 'http://only-tv.org/viasat-hockey.html', 'img': 'http://only-tv.org/images/viasat-hockey.png', 'title': 'Viasat Hockey'},
{'url': 'http://only-tv.org/sila-tv.html', 'img': 'http://only-tv.org/images/silatv.png', 'title': '\xd0\xa1\xd0\x98\xd0\x9b\xd0\x90 \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/lyubimoe-kino.html', 'img': 'http://only-tv.org/images/lyubimoe-kino.png', 'title': '\xd0\x9b\xd1\x8e\xd0\xb1\xd0\xb8\xd0\xbc\xd0\xbe\xd0\xb5 \xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://only-tv.org/hd-life.html', 'img': 'http://only-tv.org/images/hd-life.png', 'title': 'HD Life'},
{'url': 'http://only-tv.org/trofej.html', 'img': 'http://only-tv.org/images/trofej.png', 'title': '\xd0\xa2\xd1\x80\xd0\xbe\xd1\x84\xd0\xb5\xd0\xb9'},
{'url': 'http://only-tv.org/ekho-tv.html', 'img': 'http://only-tv.org/images/ekho-tv.png', 'title': '\xd0\xad\xd1\x85\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/mir-24.html', 'img': 'http://only-tv.org/images/mir-24.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x80 24'},
{'url': 'http://only-tv.org/ulybka-rebenka.html', 'img': 'http://only-tv.org/images/ulybka-rebenka.png', 'title': '\xd0\xa3\xd0\xbb\xd1\x8b\xd0\xb1\xd0\xba\xd0\xb0 \xd1\x80\xd0\xb5\xd0\xb1\xd0\xb5\xd0\xbd\xd0\xba\xd0\xb0'},
{'url': 'http://only-tv.org/ani.html', 'img': 'http://only-tv.org/images/ani.png', 'title': 'Ani'},
{'url': 'http://only-tv.org/jimjam.html', 'img': 'http://only-tv.org/images/jimjam.png', 'title': 'JimJam'},
{'url': 'http://only-tv.org/lale.html', 'img': 'http://only-tv.org/images/lale.png', 'title': 'Lale'},
{'url': 'http://only-tv.org/detskij-mir.html', 'img': 'http://only-tv.org/images/detskij-mir.png', 'title': '\xd0\x94\xd0\xb5\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xbc\xd0\xb8\xd1\x80'},
{'url': 'http://only-tv.org/bloomberg.html', 'img': 'http://only-tv.org/images/bloomberg.png', 'title': 'Bloomberg'},
{'url': 'http://only-tv.org/zoom.html', 'img': 'http://only-tv.org/images/zoom.png', 'title': 'zoom'},
{'url': 'http://only-tv.org/zagorodnaya-zhizn.html', 'img': 'http://only-tv.org/images/zagorodnaya-zhizn.png', 'title': '\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb4\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xb6\xd0\xb8\xd0\xb7\xd0\xbd\xd1\x8c'},
{'url': 'http://only-tv.org/zoo-tv.html', 'img': 'http://only-tv.org/images/zoo-tv.png', 'title': '\xd0\x97\xd0\xbe\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/rtg.html', 'img': 'http://only-tv.org/images/rtg.png', 'title': 'rtg'},
{'url': 'http://only-tv.org/9-kanal-izrail.html', 'img': 'http://only-tv.org/images/9-kanal-izrail.png', 'title': '9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\x98\xd0\xb7\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbb\xd1\x8c'},
{'url': 'http://only-tv.org/dom-kino-premium.html', 'img': 'http://only-tv.org/images/dom-kino-premium.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe \xd0\x9f\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb8\xd1\x83\xd0\xbc'},
{'url': 'http://only-tv.org/ua-pervyj.html', 'img': 'http://only-tv.org/images/uaper.png', 'title': 'ua \xd0\xbf\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9'},
{'url': 'http://only-tv.org/telekanal-pryamoj.html', 'img': 'http://only-tv.org/images/pryamoj.png', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\x9f\xd1\x80\xd1\x8f\xd0\xbc\xd0\xbe\xd0\xb9'},
{'url': 'http://only-tv.org/dange-tv.html', 'img': 'http://only-tv.org/images/dange-tv.png', 'title': 'Dange TV'},
{'url': 'http://only-tv.org/playboy-tv.html', 'img': 'http://only-tv.org/images/playboy.png', 'title': 'Playboy TV'},
{'url': 'http://only-tv.org/ntv-serial.html', 'img': 'http://only-tv.org/images/ntv-serial.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 \xd0\xa1\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb'},
{'url': 'http://only-tv.org/ntv-hit.html', 'img': 'http://only-tv.org/images/ntv-hit.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x92\xe2\x80\x91\xd0\xa5\xd0\x98\xd0\xa2'},
{'url': 'http://only-tv.org/ntv-mir.html', 'img': 'http://only-tv.org/images/ntv-mir.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 \xd0\x9c\xd0\xb8\xd1\x80'},
{'url': 'http://only-tv.org/malysh-tv.html', 'img': 'http://only-tv.org/images/malysh.png', 'title': '\xd0\xbc\xd0\xb0\xd0\xbb\xd1\x8b\xd1\x88 \xd1\x82\xd0\xb2'},
{'url': 'http://only-tv.org/muzyka-pervogo.html', 'img': 'http://only-tv.org/images/muzyka-pervogo.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0 \xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd0\xbe\xd0\xb3\xd0\xbe'},
{'url': 'http://only-tv.org/zhara-tv.html', 'img': 'http://only-tv.org/images/zhara.png', 'title': '\xd0\xb6\xd0\xb0\xd1\x80\xd0\xb0 \xd1\x82\xd0\xb2'},
{'url': 'http://only-tv.org/enter-film.html', 'img': 'http://only-tv.org/images/enter-film.png', 'title': 'Enter-\xd0\xa4\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xbc'},
{'url': 'http://only-tv.org/pervyj-avtomobilnyj.html', 'img': 'http://only-tv.org/images/pervyj-avtomobilnyj.png', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xb0\xd0\xb2\xd1\x82\xd0\xbe\xd0\xbc\xd0\xbe\xd0\xb1\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb9'},
{'url': 'http://only-tv.org/sontse-tv.html', 'img': 'http://only-tv.org/images/sontse.png', 'title': '\xd1\x81\xd0\xbe\xd0\xbd\xd1\x86\xd0\xb5 \xd1\x82\xd0\xb2'},
{'url': 'http://only-tv.org/100-news.html', 'img': 'http://only-tv.org/images/100-news.png', 'title': '100% News'},
{'url': 'http://only-tv.org/rzhd-tv.html', 'img': 'http://only-tv.org/images/rzhd-tv.png', 'title': '\xd0\xa0\xd0\x96\xd0\x94 \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/ua-kultura.html', 'img': 'http://only-tv.org/images/uakultura.png', 'title': 'UA \xd0\x9a\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd1\x83\xd1\x80\xd0\xb0'},
{'url': 'http://only-tv.org/pervyj-delovoj.html', 'img': 'http://only-tv.org/images/pervyj-delovoj.png', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xb4\xd0\xb5\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb9'},
{'url': 'http://only-tv.org/nicktoons.html', 'img': 'http://only-tv.org/images/nicktoons.png', 'title': 'NickToons'},
{'url': 'http://only-tv.org/strah-hd.html', 'img': 'http://only-tv.org/images/strah-hd.png', 'title': '\xd0\xa1\xd1\x82\xd1\x80\xd0\xb0\xd1\x85 HD'},
{'url': 'http://only-tv.org/usadba.html', 'img': 'http://only-tv.org/images/usadba.png', 'title': '\xd1\x83\xd1\x81\xd0\xb0\xd0\xb4\xd1\x8c\xd0\xb1\xd0\xb0 \xd1\x82\xd0\xb2'},
{'url': 'http://only-tv.org/kuban-24.html', 'img': 'http://only-tv.org/images/kuban-24.png', 'title': '\xd0\x9a\xd1\x83\xd0\xb1\xd0\xb0\xd0\xbd\xd1\x8c 24'},
{'url': 'http://only-tv.org/fashion-tv.html', 'img': 'http://only-tv.org/images/fashion-tv.png', 'title': 'Fashion TV'},
{'url': 'http://only-tv.org/retro-tv.html', 'img': 'http://only-tv.org/images/retro.png', 'title': '\xd0\xa0\xd0\xb5\xd1\x82\xd1\x80\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/super-tennis-hd.html', 'img': 'http://only-tv.org/images/super-tennis-hd.png', 'title': 'Super Tennis HD'},
{'url': 'http://only-tv.org/tonus-tv.html', 'img': 'http://only-tv.org/images/tonus.png', 'title': '\xd0\xa2\xd0\xbe\xd0\xbd\xd1\x83\xd1\x81 \xd0\xa2\xd0\x92'},
{'url': 'http://only-tv.org/eurosport-gold.html', 'img': 'http://only-tv.org/images/eurosport-gold.png', 'title': 'Eurosport Gold'},
{'url': 'http://only-tv.org/filmbox-arthouse.html', 'img': 'http://only-tv.org/images/filmbox-arthouse.png', 'title': 'FilmBox Arthouse'},
{'url': 'http://only-tv.org/nashe-lyubimoe-hd.html', 'img': 'http://only-tv.org/images/nashe-lyubimoe-hd.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88\xd0\xb5 \xd0\x9b\xd1\x8e\xd0\xb1\xd0\xb8\xd0\xbc\xd0\xbe\xd0\xb5 HD'},
]
udata=1559838484.71