[
{'url': 'http://tv-fresh.org/149-11.html', 'group': '', 'img': '', 'title': '1+1'},
{'url': 'http://tv-fresh.org/4-ntv.html', 'group': '', 'img': '', 'title': '\xd0\x9d\xd0\xa2\xd0\x92'},
{'url': 'http://tv-fresh.org/21-pervyj-smotret-onlajn-transljacija.html', 'group': '', 'img': '', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9'},
{'url': 'http://tv-fresh.org/22-rossija-1.html', 'group': '', 'img': '', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 1'},
{'url': 'http://tv-fresh.org/23-tnt4.html', 'group': '', 'img': '', 'title': '\xd0\xa2\xd0\x9d\xd0\xa24'},
{'url': 'http://tv-fresh.org/24-che-tv.html', 'group': '', 'img': '', 'title': '\xd1\x87\xd0\xb5 \xd1\x82\xd0\xb2'},
{'url': 'http://tv-fresh.org/25-super-kanal.html', 'group': '', 'img': '', 'title': '\xd0\xa1\xd1\x83\xd0\xbf\xd0\xb5\xd1\x80 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'http://tv-fresh.org/26-nst.html', 'group': '', 'img': '', 'title': '\xd0\x9d\xd0\xa1\xd0\xa2'},
{'url': 'http://tv-fresh.org/27-paramount-comedy.html', 'group': '', 'img': '', 'title': 'Paramount Comedy'},
{'url': 'http://tv-fresh.org/28-national-geographic.html', 'group': '', 'img': '', 'title': 'National Geographic'},
{'url': 'http://tv-fresh.org/29-zee-tv.html', 'group': '', 'img': '', 'title': 'zee tv'},
{'url': 'http://tv-fresh.org/30-nickelodeon.html', 'group': '', 'img': '', 'title': 'Nickelodeon'},
{'url': 'http://tv-fresh.org/31-domashnij.html', 'group': '', 'img': '', 'title': '\xd0\x94\xd0\xbe\xd0\xbc\xd0\xb0\xd1\x88\xd0\xbd\xd0\xb8\xd0\xb9'},
{'url': 'http://tv-fresh.org/32-moja-planeta.html', 'group': '', 'img': '', 'title': '\xd0\x9c\xd0\xbe\xd1\x8f \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'http://tv-fresh.org/33-history.html', 'group': '', 'img': '', 'title': 'History'},
{'url': 'http://tv-fresh.org/34-illjuzion-pljus.html', 'group': '', 'img': '', 'title': '\xd0\xb8\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd \xd0\xbf\xd0\xbb\xd1\x8e\xd1\x81'},
{'url': 'http://tv-fresh.org/35-russkij-illjuzion.html', 'group': '', 'img': '', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\x98\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd'},
{'url': 'http://tv-fresh.org/36-sovershenno-sekretno.html', 'group': '', 'img': '', 'title': '\xd0\xa1\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x80\xd1\x88\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xbe \xd1\x81\xd0\xb5\xd0\xba\xd1\x80\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe'},
{'url': 'http://tv-fresh.org/37-kanal-istorija.html', 'group': '', 'img': '', 'title': '\xd0\xb8\xd1\x81\xd1\x82\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f'},
{'url': 'http://tv-fresh.org/38-amedia-premium-hd.html', 'group': '', 'img': '', 'title': 'Amedia Premium HD'},
{'url': 'http://tv-fresh.org/39-24-tehno.html', 'group': '', 'img': '', 'title': '24 \xd1\x82\xd0\xb5\xd1\x85\xd0\xbd\xd0\xbe'},
{'url': 'http://tv-fresh.org/40-nauka-20.html', 'group': '', 'img': '', 'title': '\xd0\xbd\xd0\xb0\xd1\x83\xd0\xba\xd0\xb0 2.0'},
{'url': 'http://tv-fresh.org/41-russkaja-noch.html', 'group': '', 'img': '', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd0\xbd\xd0\xbe\xd1\x87\xd1\x8c'},
{'url': 'http://tv-fresh.org/42-muz-tv.html', 'group': '', 'img': '', 'title': '\xd0\x9c\xd0\xa3\xd0\x97-\xd0\xa2\xd0\x92'},
{'url': 'http://tv-fresh.org/43-kinokomedija-tv.html', 'group': '', 'img': '', 'title': '\xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xba\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f \xd1\x82\xd0\xb2'},
{'url': 'http://tv-fresh.org/44-fox.html', 'group': '', 'img': '', 'title': 'FOX'},
{'url': 'http://tv-fresh.org/45-fox-life.html', 'group': '', 'img': '', 'title': 'Fox Life'},
{'url': 'http://tv-fresh.org/46-viasat-history.html', 'group': '', 'img': '', 'title': 'Viasat History'},
{'url': 'http://tv-fresh.org/47-kanal-a1.html', 'group': '', 'img': '', 'title': 'a1'},
{'url': 'http://tv-fresh.org/48-mtv-rossija.html', 'group': '', 'img': '', 'title': 'MTV \xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f'},
{'url': 'http://tv-fresh.org/49-tv-centr.html', 'group': '', 'img': '', 'title': '\xd0\xa2\xd0\x92 \xd0\xa6\xd0\xb5\xd0\xbd\xd1\x82\xd1\x80'},
{'url': 'http://tv-fresh.org/50-dom-kino.html', 'group': '', 'img': '', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://tv-fresh.org/51-set-sony-tv.html', 'group': '', 'img': '', 'title': 'set (sony tv)'},
{'url': 'http://tv-fresh.org/52-traveladventure.html', 'group': '', 'img': '', 'title': 'Travel+Adventure'},
{'url': 'http://tv-fresh.org/53-avto-pljus.html', 'group': '', 'img': '', 'title': '\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe \xd0\xbf\xd0\xbb\xd1\x8e\xd1\x81'},
{'url': 'http://tv-fresh.org/54-penthouse-passion.html', 'group': '', 'img': '', 'title': 'Penthouse Passion'},
{'url': 'http://tv-fresh.org/55-galaxy-tv.html', 'group': '', 'img': '', 'title': 'Galaxy TV'},
{'url': 'http://tv-fresh.org/56-kanal-a2.html', 'group': '', 'img': '', 'title': 'a2'},
{'url': 'http://tv-fresh.org/57-russkij-bestseller.html', 'group': '', 'img': '', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb1\xd0\xb5\xd1\x81\xd1\x82\xd1\x81\xd0\xb5\xd0\xbb\xd0\xbb\xd0\xb5\xd1\x80'},
{'url': 'http://tv-fresh.org/58-penthouse-gold-hd.html', 'group': '', 'img': '', 'title': 'Penthouse Gold HD'},
{'url': 'http://tv-fresh.org/59-ohota-i-rybalka.html', 'group': '', 'img': '', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xb0 \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xb0\xd0\xbb\xd0\xba\xd0\xb0'},
{'url': 'http://tv-fresh.org/60-ohotnik-i-rybolov.html', 'group': '', 'img': '', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2'},
{'url': 'http://tv-fresh.org/61-sony-sci-fi.html', 'group': '', 'img': '', 'title': 'SONY SCI-FI'},
{'url': 'http://tv-fresh.org/62-indijskoe-kino.html', 'group': '', 'img': '', 'title': '\xd0\x98\xd0\xbd\xd0\xb4\xd0\xb8\xd0\xb9\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://tv-fresh.org/63-kuhnja-tv.html', 'group': '', 'img': '', 'title': '\xd0\x9a\xd1\x83\xd1\x85\xd0\xbd\xd1\x8f \xd0\xa2\xd0\x92'},
{'url': 'http://tv-fresh.org/64-lja-minor.html', 'group': '', 'img': '', 'title': '\xd0\x9b\xd1\x8f-\xd0\x9c\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x80'},
{'url': 'http://tv-fresh.org/65-evrokino.html', 'group': '', 'img': '', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://tv-fresh.org/66-kino-tv.html', 'group': '', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'http://tv-fresh.org/67-eda-tv.html', 'group': '', 'img': '', 'title': '\xd0\x95\xd0\xb4\xd0\xb0 \xd1\x82\xd0\xb2'},
{'url': 'http://tv-fresh.org/68-rbk.html', 'group': '', 'img': '', 'title': '\xd0\xa0\xd0\x91\xd0\x9a'},
{'url': 'http://tv-fresh.org/69-kanal-ju.html', 'group': '', 'img': '', 'title': '\xd1\x8e'},
{'url': 'http://tv-fresh.org/70-brazzers-tv-europe.html', 'group': '', 'img': '', 'title': 'Brazzers TV Europe'},
{'url': 'http://tv-fresh.org/71-strashnoe-hd.html', 'group': '', 'img': '', 'title': '\xd0\xa1\xd1\x82\xd1\x80\xd0\xb0\xd1\x88\xd0\xbd\xd0\xbe\xd0\xb5 HD'},
{'url': 'http://tv-fresh.org/72-ostrosjuzhetnoe-hd.html', 'group': '', 'img': '', 'title': '\xd0\x9e\xd1\x81\xd1\x82\xd1\x80\xd0\xbe\xd1\x81\xd1\x8e\xd0\xb6\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe\xd0\xb5 HD'},
{'url': 'http://tv-fresh.org/73-nashe-krutoe.html', 'group': '', 'img': '', 'title': '\xd0\x9d\xd0\xb0\xd1\x88\xd0\xb5 \xd0\x9a\xd1\x80\xd1\x83\xd1\x82\xd0\xbe\xd0\xb5'},
{'url': 'http://tv-fresh.org/74-boks-tv.html', 'group': '', 'img': '', 'title': '\xd0\x91\xd0\xbe\xd0\xba\xd1\x81 \xd0\xa2\xd0\x92'},
{'url': 'http://tv-fresh.org/75-muzhskoj.html', 'group': '', 'img': '', 'title': '\xd0\x9c\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9'},
{'url': 'http://tv-fresh.org/76-sct.html', 'group': '', 'img': '', 'title': 'SCT'},
{'url': 'http://tv-fresh.org/77-otr.html', 'group': '', 'img': '', 'title': '\xd0\x9e\xd0\xa2\xd0\xa0'},
{'url': 'http://tv-fresh.org/78-zhivi.html', 'group': '', 'img': '', 'title': '\xd0\x96\xd0\xb8\xd0\xb2\xd0\xb8'},
{'url': 'http://tv-fresh.org/79-nostalgija.html', 'group': '', 'img': '', 'title': '\xd0\x9d\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xb3\xd0\xb8\xd1\x8f'},
{'url': 'http://tv-fresh.org/80-360-gradusov.html', 'group': '', 'img': '', 'title': '360 \xd0\xb3\xd1\x80\xd0\xb0\xd0\xb4\xd1\x83\xd1\x81\xd0\xbe\xd0\xb2'},
{'url': 'http://tv-fresh.org/81-nash-kinoroman.html', 'group': '', 'img': '', 'title': '\xd0\x9d\xd0\xb0\xd1\x88 \xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd'},
{'url': 'http://tv-fresh.org/82-nat-geo-wild.html', 'group': '', 'img': '', 'title': 'NAT GEO WILD'},
{'url': 'http://tv-fresh.org/83-avto-24.html', 'group': '', 'img': '', 'title': '\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe 24'},
{'url': 'http://tv-fresh.org/84-hollywood-tv.html', 'group': '', 'img': '', 'title': 'Hollywood \xd0\xa2\xd0\x92'},
{'url': 'http://tv-fresh.org/85-russkij-roman.html', 'group': '', 'img': '', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd'},
{'url': 'http://tv-fresh.org/86-russkij-detektiv.html', 'group': '', 'img': '', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb4\xd0\xb5\xd1\x82\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2'},
{'url': 'http://tv-fresh.org/87-bridzh-tv.html', 'group': '', 'img': '', 'title': '\xd0\xb1\xd1\x80\xd0\xb8\xd0\xb4\xd0\xb6 \xd1\x82\xd0\xb2'},
{'url': 'http://tv-fresh.org/88-365-dnej-tv.html', 'group': '', 'img': '', 'title': '365 \xd0\xb4\xd0\xbd\xd0\xb5\xd0\xb9 \xd1\x82\xd0\xb2'},
{'url': 'http://tv-fresh.org/89-kinoserija.html', 'group': '', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb5\xd1\x80\xd0\xb8\xd1\x8f'},
{'url': 'http://tv-fresh.org/90-russkij-jekstrim.html', 'group': '', 'img': '', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xad\xd0\xba\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd0\xbc'},
{'url': 'http://tv-fresh.org/91-kinoxxx.html', 'group': '', 'img': '', 'title': 'KINOXXX'},
{'url': 'http://tv-fresh.org/92-zvezda.html', 'group': '', 'img': '', 'title': '\xd0\x97\xd0\xb2\xd0\xb5\xd0\xb7\xd0\xb4\xd0\xb0'},
{'url': 'http://tv-fresh.org/93-viasat-nature.html', 'group': '', 'img': '', 'title': 'Viasat Nature'},
{'url': 'http://tv-fresh.org/94-mir.html', 'group': '', 'img': '', 'title': '\xd0\x9c\xd0\xb8\xd1\x80'},
{'url': 'http://tv-fresh.org/95-shanson-tv.html', 'group': '', 'img': '', 'title': '\xd0\xa8\xd0\xb0\xd0\xbd\xd1\x81\xd0\xbe\xd0\xbd \xd0\xa2\xd0\x92'},
{'url': 'http://tv-fresh.org/96-muzhskoe-kino.html', 'group': '', 'img': '', 'title': '\xd0\x9c\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://tv-fresh.org/97-setanta-sport-1-setanta-sports-1.html', 'group': '', 'img': '', 'title': '\xd0\xa1\xd0\xb5\xd1\x82\xd0\xb0\xd0\xbd\xd1\x82\xd0\xb0 \xd0\xa1\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 1 (Setanta Sports 1)'},
{'url': 'http://tv-fresh.org/98-outdoor-channel.html', 'group': '', 'img': '', 'title': 'Outdoor Channel'},
{'url': 'http://tv-fresh.org/99-o-la-la.html', 'group': '', 'img': '', 'title': 'O-la-la'},
{'url': 'http://tv-fresh.org/100-vh1.html', 'group': '', 'img': '', 'title': 'VH1'},
{'url': 'http://tv-fresh.org/101-1-krym.html', 'group': '', 'img': '', 'title': '1 \xd0\x9a\xd1\x80\xd1\x8b\xd0\xbc'},
{'url': 'http://tv-fresh.org/102-redlight-hd.html', 'group': '', 'img': '', 'title': 'Redlight HD'},
{'url': 'http://tv-fresh.org/103-morskoj-kanal.html', 'group': '', 'img': '', 'title': '\xd0\xbc\xd0\xbe\xd1\x80\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9'},
{'url': 'http://tv-fresh.org/104-amc.html', 'group': '', 'img': '', 'title': 'AMC'},
{'url': 'http://tv-fresh.org/105-setanta-sport-2-setanta-sports-2.html', 'group': '', 'img': '', 'title': '\xd0\xa1\xd0\xb5\xd1\x82\xd0\xb0\xd0\xbd\xd1\x82\xd0\xb0 \xd0\xa1\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 2 (Setanta Sports 2)'},
{'url': 'http://tv-fresh.org/106-sony-turbo.html', 'group': '', 'img': '', 'title': 'Sony Turbo'},
{'url': 'http://tv-fresh.org/107-cento-x-cento-tv.html', 'group': '', 'img': '', 'title': 'cento x cento tv'},
{'url': 'http://tv-fresh.org/108-dom-kino-premium.html', 'group': '', 'img': '', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe \xd0\x9f\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb8\xd1\x83\xd0\xbc'},
{'url': 'http://tv-fresh.org/109-rtg-tv.html', 'group': '', 'img': '', 'title': 'RTG TV'},
{'url': 'http://tv-fresh.org/110-bober-tv.html', 'group': '', 'img': '', 'title': '\xd0\xb1\xd0\xbe\xd0\xb1\xd0\xb5\xd1\x80 \xd1\x82\xd0\xb2'},
{'url': 'http://tv-fresh.org/111-zagorodnaja-zhizn.html', 'group': '', 'img': '', 'title': '\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb4\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xb6\xd0\xb8\xd0\xb7\xd0\xbd\xd1\x8c'},
{'url': 'http://tv-fresh.org/112-hustler-hd.html', 'group': '', 'img': '', 'title': 'Hustler HD'},
{'url': 'http://tv-fresh.org/113-dange-tv.html', 'group': '', 'img': '', 'title': 'Dange TV'},
{'url': 'http://tv-fresh.org/114-tnt-music.html', 'group': '', 'img': '', 'title': '\xd1\x82\xd0\xbd\xd1\x82 music'},
{'url': 'http://tv-fresh.org/115-krasnaja-linija.html', 'group': '', 'img': '', 'title': '\xd0\x9a\xd1\x80\xd0\xb0\xd1\x81\xd0\xbd\xd0\xb0\xd1\x8f \xd0\x9b\xd0\xb8\xd0\xbd\xd0\xb8\xd1\x8f'},
{'url': 'http://tv-fresh.org/116-playboy-tv.html', 'group': '', 'img': '', 'title': 'Playboy TV'},
{'url': 'http://tv-fresh.org/117-fap-tv-teens.html', 'group': '', 'img': '', 'title': 'FAP TV Teens'},
{'url': 'http://tv-fresh.org/118-mir-seriala.html', 'group': '', 'img': '', 'title': '\xd0\x9c\xd0\xb8\xd1\x80 \xd1\x81\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb\xd0\xb0'},
{'url': 'http://tv-fresh.org/119-russkaja-komedija.html', 'group': '', 'img': '', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd0\xba\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f'},
{'url': 'http://tv-fresh.org/120-kinopremium-hd.html', 'group': '', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\x9f\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb8\xd1\x83\xd0\xbc HD'},
{'url': 'http://tv-fresh.org/121-amedia-hit.html', 'group': '', 'img': '', 'title': 'Amedia Hit'},
{'url': 'http://tv-fresh.org/122-fap-tv-bbw.html', 'group': '', 'img': '', 'title': 'FAP TV BBW'},
{'url': 'http://tv-fresh.org/123-dorcel-tv.html', 'group': '', 'img': '', 'title': 'Dorcel TV'},
{'url': 'http://tv-fresh.org/124-fap-tv-2.html', 'group': '', 'img': '', 'title': 'FAP TV 2'},
{'url': 'http://tv-fresh.org/125-drajv-tv.html', 'group': '', 'img': '', 'title': '\xd0\xb4\xd1\x80\xd0\xb0\xd0\xb9\xd0\xb2 \xd1\x82\xd0\xb2'},
{'url': 'http://tv-fresh.org/126-kazsport.html', 'group': '', 'img': '', 'title': '\xd0\x9a\xd0\x90\xd0\x97\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82'},
{'url': 'http://tv-fresh.org/127-shokirujuschee-hd.html', 'group': '', 'img': '', 'title': '\xd0\xa8\xd0\xbe\xd0\xba\xd0\xb8\xd1\x80\xd1\x83\xd1\x8e\xd1\x89\xd0\xb5\xd0\xb5 HD'},
{'url': 'http://tv-fresh.org/128-komedijnoe-hd.html', 'group': '', 'img': '', 'title': '\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd0\xb9\xd0\xbd\xd0\xbe\xd0\xb5 HD'},
{'url': 'http://tv-fresh.org/129-hd-life.html', 'group': '', 'img': '', 'title': 'HD Life'},
{'url': 'http://tv-fresh.org/130-paramount-channel.html', 'group': '', 'img': '', 'title': 'Paramount Channel'},
{'url': 'http://tv-fresh.org/131-kinopremera.html', 'group': '', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbf\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8c\xd0\xb5\xd1\x80\xd0\xb0'},
{'url': 'http://tv-fresh.org/132-fap-tv-3.html', 'group': '', 'img': '', 'title': 'FAP TV 3'},
{'url': 'http://tv-fresh.org/133-sila-tv.html', 'group': '', 'img': '', 'title': '\xd0\xa1\xd0\x98\xd0\x9b\xd0\x90 \xd0\xa2\xd0\x92'},
{'url': 'http://tv-fresh.org/134-fap-tv-4.html', 'group': '', 'img': '', 'title': 'FAP TV 4'},
{'url': 'http://tv-fresh.org/135-tv-xxi.html', 'group': '', 'img': '', 'title': 'TV XXI'},
{'url': 'http://tv-fresh.org/136-muzyka-pervogo.html', 'group': '', 'img': '', 'title': '\xd0\x9c\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0 \xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd0\xbe\xd0\xb3\xd0\xbe'},
{'url': 'http://tv-fresh.org/137-ntv-serial.html', 'group': '', 'img': '', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 \xd0\xa1\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb'},
{'url': 'http://tv-fresh.org/138-ntv-hit.html', 'group': '', 'img': '', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 \xd0\xa5\xd0\xb8\xd1\x82'},
{'url': 'http://tv-fresh.org/139-ntv-mir.html', 'group': '', 'img': '', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 \xd0\x9c\xd0\xb8\xd1\x80'},
{'url': 'http://tv-fresh.org/140-zhara.html', 'group': '', 'img': '', 'title': '\xd0\x96\xd0\xb0\xd1\x80\xd0\xb0'},
{'url': 'http://tv-fresh.org/141-rodnoe-kino.html', 'group': '', 'img': '', 'title': '\xd0\xa0\xd0\xbe\xd0\xb4\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://tv-fresh.org/142-spike.html', 'group': '', 'img': '', 'title': 'Spike'},
{'url': 'http://tv-fresh.org/143-nashe-novoe-kino.html', 'group': '', 'img': '', 'title': '\xd0\x9d\xd0\xb0\xd1\x88\xd0\xb5 \xd0\xbd\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://tv-fresh.org/144-kinomiks.html', 'group': '', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbc\xd0\xb8\xd0\xba\xd1\x81'},
{'url': 'http://tv-fresh.org/145-extreme-sports.html', 'group': '', 'img': '', 'title': 'Extreme Sports'},
{'url': 'http://tv-fresh.org/146-kinosvidanie.html', 'group': '', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb2\xd0\xb8\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'},
{'url': 'http://tv-fresh.org/147-kinopokaz.html', 'group': '', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbf\xd0\xbe\xd0\xba\xd0\xb0\xd0\xb7'},
{'url': 'http://tv-fresh.org/148-nashe-ljubimoe-kino.html', 'group': '', 'img': '', 'title': '\xd0\x9d\xd0\xb0\xd1\x88\xd0\xb5 \xd0\xbb\xd1\x8e\xd0\xb1\xd0\xb8\xd0\xbc\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://tv-fresh.org/150-22.html', 'group': '', 'img': '', 'title': '2+2'},
{'url': 'http://tv-fresh.org/151-stb.html', 'group': '', 'img': '', 'title': '\xd0\xa1\xd0\xa2\xd0\x91'},
{'url': 'http://tv-fresh.org/152-novyj-kanal.html', 'group': '', 'img': '', 'title': '\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'http://tv-fresh.org/153-inter.html', 'group': '', 'img': '', 'title': '\xd0\x98\xd0\xbd\xd1\x82\xd0\xb5\xd1\x80'},
{'url': 'http://tv-fresh.org/154-ictv.html', 'group': '', 'img': '', 'title': 'ICTV'},
{'url': 'http://tv-fresh.org/155-trk-ukraina.html', 'group': '', 'img': '', 'title': '\xd0\xa2\xd0\xa0\xd0\x9a \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'http://tv-fresh.org/156-ntn-ukraina.html', 'group': '', 'img': '', 'title': '\xd0\xbd\xd1\x82\xd0\xbd (\xd1\x83\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0)'},
{'url': 'http://tv-fresh.org/157-mega.html', 'group': '', 'img': '', 'title': '\xd0\x9c\xd0\xb5\xd0\xb3\xd0\xb0'},
{'url': 'http://tv-fresh.org/158-oce.html', 'group': '', 'img': '', 'title': '\xd0\x9e\xd0\xa6\xd0\x95'},
{'url': 'http://tv-fresh.org/159-tet.html', 'group': '', 'img': '', 'title': '\xd0\xa2\xd0\x95\xd0\xa2'},
{'url': 'http://tv-fresh.org/160-futbol-1.html', 'group': '', 'img': '', 'title': '\xd1\x84\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 1'},
{'url': 'http://tv-fresh.org/161-futbol-2.html', 'group': '', 'img': '', 'title': '\xd1\x84\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 2'},
{'url': 'http://tv-fresh.org/162-futbol-3.html', 'group': '', 'img': '', 'title': '\xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 3'},
{'url': 'http://tv-fresh.org/163-cetanta-cport-ukraina.html', 'group': '', 'img': '', 'title': 'C\xd0\xb5\xd1\x82\xd0\xb0\xd0\xbd\xd1\x82\xd0\xb0 C\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'http://tv-fresh.org/164-setanta-sport-pljus-ukraina.html', 'group': '', 'img': '', 'title': '\xd0\xa1\xd0\xb5\xd1\x82\xd0\xb0\xd0\xbd\xd1\x82\xd0\xb0 \xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 \xd0\xbf\xd0\xbb\xd1\x8e\xd1\x81 \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'http://tv-fresh.org/165-112-kanal.html', 'group': '', 'img': '', 'title': '112'},
{'url': 'http://tv-fresh.org/166-espreso-tv.html', 'group': '', 'img': '', 'title': '\xd0\x95\xd1\x81\xd0\xbf\xd1\x80\xd0\xb5\xd1\x81\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'http://tv-fresh.org/167-news-one.html', 'group': '', 'img': '', 'title': 'News One'},
{'url': 'http://tv-fresh.org/168-ua-pervyj.html', 'group': '', 'img': '', 'title': 'UA \xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9'},
{'url': 'http://tv-fresh.org/169-m1.html', 'group': '', 'img': '', 'title': '\xd0\x9c1'},
{'url': 'http://tv-fresh.org/170-m2.html', 'group': '', 'img': '', 'title': '\xd0\x9c2'},
{'url': 'http://tv-fresh.org/171-zoom.html', 'group': '', 'img': '', 'title': 'zoom'},
{'url': 'http://tv-fresh.org/172-trofej.html', 'group': '', 'img': '', 'title': '\xd0\xa2\xd1\x80\xd0\xbe\xd1\x84\xd0\xb5\xd0\xb9'},
{'url': 'http://tv-fresh.org/173-k1.html', 'group': '', 'img': '', 'title': '\xd0\x9a1'},
{'url': 'http://tv-fresh.org/174-k2.html', 'group': '', 'img': '', 'title': '\xd0\x9a2'},
{'url': 'http://tv-fresh.org/175-fap-tv-teaching.html', 'group': '', 'img': '', 'title': 'FAP TV Teaching'},
{'url': 'http://tv-fresh.org/176-fap-tv-parody.html', 'group': '', 'img': '', 'title': 'FAP TV Parody'},
{'url': 'http://tv-fresh.org/177-fap-tv-anal.html', 'group': '', 'img': '', 'title': 'FAP TV Anal'},
{'url': 'http://tv-fresh.org/178-fap-tv-compilation.html', 'group': '', 'img': '', 'title': 'FAP TV Compilation'},
{'url': 'http://tv-fresh.org/179-oh-ah-hd.html', 'group': '', 'img': '', 'title': '\xd0\x9e\xd0\xa5-\xd0\x90\xd0\xa5 HD'},
]
udata=1591869725.3