[
{'url': 'http://tvua.biz/1pl1.html', 'img': '', 'title': '1+1'},
{'url': 'http://tvua.biz/2pl2ua.html', 'img': '', 'title': '2+2'},
{'url': 'http://tvua.biz/ukrana.html', 'img': '', 'title': '\xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'http://tvua.biz/stbtv4.html', 'img': '', 'title': '\xd0\xa1\xd0\xa2\xd0\x91'},
{'url': 'http://tvua.biz/novijkanaltv4.html', 'img': '', 'title': '\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'http://tvua.biz/ictvtv4.html', 'img': '', 'title': 'ICTV'},
{'url': 'http://tvua.biz/inter.html', 'img': '', 'title': '\xd0\x98\xd0\xbd\xd1\x82\xd0\xb5\xd1\x80'},
{'url': 'http://tvua.biz/interplus.html', 'img': '', 'title': '\xd0\x98\xd0\xbd\xd1\x82\xd0\xb5\xd1\x80+'},
{'url': 'http://tvua.biz/ntn.html', 'img': '', 'title': '\xd0\x9d\xd0\xa2\xd0\x9d'},
{'url': 'http://tvua.biz/k1.html', 'img': '', 'title': '\xd0\x9a1'},
{'url': 'http://tvua.biz/k2.html', 'img': '', 'title': '\xd0\x9a2'},
{'url': 'http://tvua.biz/pervyy-kanal.html', 'img': '', 'title': '\xd0\xbf\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9'},
{'url': 'http://tvua.biz/ntv.html', 'img': '', 'title': '\xd0\x9d\xd0\xa2\xd0\x92'},
{'url': 'http://tvua.biz/sts.html', 'img': '', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1'},
{'url': 'http://tvua.biz/ren-tv.html', 'img': '', 'title': '\xd0\xa0\xd0\xb5\xd0\xbd \xd0\xa2\xd0\x92'},
{'url': 'http://tvua.biz/chetv.html', 'img': '', 'title': '\xd1\x87\xd0\xb5 \xd1\x82\xd0\xb2'},
{'url': 'http://tvua.biz/tnt.html', 'img': '', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2'},
{'url': 'http://tvua.biz/mir.html', 'img': '', 'title': '\xd0\x9c\xd0\xb8\xd1\x80'},
{'url': 'http://tvua.biz/domashniy.html', 'img': '', 'title': '\xd0\x94\xd0\xbe\xd0\xbc\xd0\xb0\xd1\x88\xd0\xbd\xd0\xb8\xd0\xb9'},
{'url': 'http://tvua.biz/tvc-tv.html', 'img': '', 'title': '\xd1\x82\xd0\xb2\xd1\x86'},
{'url': 'http://tvua.biz/5-kanal.html', 'img': '', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'http://tvua.biz/rossiya-1.html', 'img': '', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 1'},
{'url': 'http://tvua.biz/rtr-planeta.html', 'img': '', 'title': '\xd0\xa0\xd0\xa2\xd0\xa0 \xd0\x9f\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'http://tvua.biz/rossiya-k.html', 'img': '', 'title': '\xd1\x80\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f \xd0\xba'},
{'url': 'http://tvua.biz/u_tv.html', 'img': '', 'title': '\xd1\x8e \xd1\x82\xd0\xb2'},
{'url': 'http://tvua.biz/ctclove.html', 'img': '', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1 Love'},
{'url': 'http://tvua.biz/tnt4.html', 'img': '', 'title': '\xd0\xa2\xd0\x9d\xd0\xa24'},
{'url': 'http://tvua.biz/sarafan.html', 'img': '', 'title': '\xd0\xa1\xd0\xb0\xd1\x80\xd0\xb0\xd1\x84\xd0\xb0\xd0\xbd'},
{'url': 'http://tvua.biz/belarus-1.html', 'img': '', 'title': '\xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c 1'},
{'url': 'http://tvua.biz/belarus-2.html', 'img': '', 'title': '\xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c 2'},
{'url': 'http://tvua.biz/belarus-3.html', 'img': '', 'title': '\xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c 3'},
{'url': 'http://tvua.biz/krim-1.html', 'img': '', 'title': '\xd0\x9a\xd1\x80\xd1\x8b\xd0\xbc 1'},
{'url': 'http://tvua.biz/belros.html', 'img': '', 'title': '\xd0\x91\xd0\xb5\xd0\xbb\xd0\xa0\xd0\xbe\xd1\x81'},
{'url': 'http://tvua.biz/nostalgiya.html', 'img': '', 'title': '\xd0\x9d\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xb3\xd0\xb8\xd1\x8f'},
{'url': 'http://tvua.biz/nash-detektiv.html', 'img': '', 'title': '\xd0\x9d\xd0\xb0\xd1\x88 \xd0\xb4\xd0\xb5\xd1\x82\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2'},
{'url': 'http://tvua.biz/dom-kino-premium.html', 'img': '', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe \xd0\x9f\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb8\xd1\x83\xd0\xbc'},
{'url': 'http://tvua.biz/domkino.html', 'img': '', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://tvua.biz/russkiy-roman.html', 'img': '', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd'},
{'url': 'http://tvua.biz/russkiy-detektiv.html', 'img': '', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb4\xd0\xb5\xd1\x82\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2'},
{'url': 'http://tvua.biz/russkiy-bestseller.html', 'img': '', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb1\xd0\xb5\xd1\x81\xd1\x82\xd1\x81\xd0\xb5\xd0\xbb\xd0\xbb\xd0\xb5\xd1\x80'},
{'url': 'http://tvua.biz/illuzionrus.html', 'img': '', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb8\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd'},
{'url': 'http://tvua.biz/illyuzion-pl.html', 'img': '', 'title': '\xd0\xb8\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd+'},
{'url': 'http://tvua.biz/ostrosjuzhetnoe.html', 'img': '', 'title': '\xd0\x9e\xd1\x81\xd1\x82\xd1\x80\xd0\xbe\xd1\x81\xd1\x8e\xd0\xb6\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe\xd0\xb5 HD'},
{'url': 'http://tvua.biz/kinopremera.html', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbf\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8c\xd0\xb5\xd1\x80\xd0\xb0'},
{'url': 'http://tvua.biz/muzhskoe-kino.html', 'img': '', 'title': '\xd0\x9c\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://tvua.biz/kinosvidanie.html', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb2\xd0\xb8\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'},
{'url': 'http://tvua.biz/kinokomediya.html', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xba\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f'},
{'url': 'http://tvua.biz/kinosemya.html', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb5\xd0\xbc\xd1\x8c\xd1\x8f'},
{'url': 'http://tvua.biz/kinomiks.html', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbc\xd0\xb8\xd0\xba\xd1\x81'},
{'url': 'http://tvua.biz/kinohit.html', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x85\xd0\xb8\xd1\x82'},
{'url': 'http://tvua.biz/rodnoe-kino.html', 'img': '', 'title': '\xd0\xa0\xd0\xbe\xd0\xb4\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://tvua.biz/lyubimoe-kino.html', 'img': '', 'title': '\xd0\x9d\xd0\xb0\xd1\x88\xd0\xb5 \xd0\xbb\xd1\x8e\xd0\xb1\xd0\xb8\xd0\xbc\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://tvua.biz/mir-seriala.html', 'img': '', 'title': '\xd0\x9c\xd0\xb8\xd1\x80 \xd1\x81\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb\xd0\xb0'},
{'url': 'http://tvua.biz/dorama.html', 'img': '', 'title': '\xd0\x94\xd0\xbe\xd1\x80\xd0\xb0\xd0\xbc\xd0\xb0'},
{'url': 'http://tvua.biz/telenovella.html', 'img': '', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb5\xd0\xbb\xd0\xbb\xd0\xb0'},
{'url': 'http://tvua.biz/nst.html', 'img': '', 'title': '\xd0\x9d\xd0\xa1\xd0\xa2'},
{'url': 'http://tvua.biz/evrokino.html', 'img': '', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://tvua.biz/sonyscifi.html', 'img': '', 'title': 'Sony Sci-Fi'},
{'url': 'http://tvua.biz/indiya-kino.html', 'img': '', 'title': '\xd0\x98\xd0\xbd\xd0\xb4\xd0\xb8\xd0\xb9\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://tvua.biz/zee-tv.html', 'img': '', 'title': 'zee tv'},
{'url': 'http://tvua.biz/bollywood.html', 'img': '', 'title': 'Bollywood'},
{'url': 'http://tvua.biz/fox-tv.html', 'img': '', 'title': 'Fox'},
{'url': 'http://tvua.biz/fox-live.html', 'img': '', 'title': 'Fox live'},
{'url': 'http://tvua.biz/amc-tv.html', 'img': '', 'title': 'AMC'},
{'url': 'http://tvua.biz/paramount-channel.html', 'img': '', 'title': 'Paramount Channel'},
{'url': 'http://tvua.biz/parcomedy.html', 'img': '', 'title': 'Paramount Comedy'},
{'url': 'http://tvua.biz/enter-film.html', 'img': '', 'title': 'Enter-\xd1\x84\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xbc'},
{'url': 'http://tvua.biz/zvezda.html', 'img': '', 'title': '\xd0\x97\xd0\xb2\xd0\xb5\xd0\xb7\xd0\xb4\xd0\xb0'},
{'url': 'http://tvua.biz/dikiy.html', 'img': '', 'title': '\xd0\x94\xd0\xb8\xd0\xba\xd0\xb8\xd0\xb9'},
{'url': 'http://tvua.biz/dikaya-ohota.html', 'img': '', 'title': '\xd0\x94\xd0\xb8\xd0\xba\xd0\xb0\xd1\x8f \xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xb0 HD'},
{'url': 'http://tvua.biz/discovery-science.html', 'img': '', 'title': 'Discovery science'},
{'url': 'http://tvua.biz/nat-geo-wild.html', 'img': '', 'title': 'Nat Geo Wild'},
{'url': 'http://tvua.biz/id-xtra.html', 'img': '', 'title': 'ID Xtra'},
{'url': 'http://tvua.biz/priklyucheniya-hd.html', 'img': '', 'title': '\xd0\x9f\xd1\x80\xd0\xb8\xd0\xba\xd0\xbb\xd1\x8e\xd1\x87\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f HD'},
{'url': 'http://tvua.biz/travel-channel.html', 'img': '', 'title': 'Travel Channel'},
{'url': 'http://tvua.biz/travel-adventure.html', 'img': '', 'title': 'Travel+adventure'},
{'url': 'http://tvua.biz/rtg-tv.html', 'img': '', 'title': 'RTG TV'},
{'url': 'http://tvua.biz/histori.html', 'img': '', 'title': 'History'},
{'url': 'http://tvua.biz/bober.html', 'img': '', 'title': '\xd0\x91\xd0\xbe\xd0\xb1\xd1\x91\xd1\x80'},
{'url': 'http://tvua.biz/zagorodnaya-zhizn.html', 'img': '', 'title': '\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb4\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xb6\xd0\xb8\xd0\xb7\xd0\xbd\xd1\x8c'},
{'url': 'http://tvua.biz/tvoy-dom.html', 'img': '', 'title': '\xd0\xa2\xd0\xb2\xd0\xbe\xd0\xb9 \xd0\x94\xd0\xbe\xd0\xbc'},
{'url': 'http://tvua.biz/pervyy-vegetarianskiy.html', 'img': '', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\x92\xd0\xb5\xd0\xb3\xd0\xb5\xd1\x82\xd0\xb0\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9'},
{'url': 'http://tvua.biz/kuhnya-tv.html', 'img': '', 'title': '\xd0\x9a\xd1\x83\xd1\x85\xd0\xbd\xd1\x8f \xd0\xa2\xd0\x92'},
{'url': 'http://tvua.biz/eda-tv.html', 'img': '', 'title': '\xd0\x95\xd0\xb4\xd0\xb0 \xd0\xa2\xd0\x92'},
{'url': 'http://tvua.biz/mama.html', 'img': '', 'title': '\xd0\x9c\xd0\xb0\xd0\xbc\xd0\xb0'},
{'url': 'http://tvua.biz/doktor.html', 'img': '', 'title': '\xd0\x94\xd0\xbe\xd0\xba\xd1\x82\xd0\xbe\xd1\x80'},
{'url': 'http://tvua.biz/fine-living.html', 'img': '', 'title': 'Fine Living'},
{'url': 'http://tvua.biz/avtoplys.html', 'img': '', 'title': '\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe \xd0\x9f\xd0\xbb\xd1\x8e\xd1\x81'},
{'url': 'http://tvua.biz/galaxy.html', 'img': '', 'title': 'Galaxy TV'},
{'url': 'http://tvua.biz/ohota-i-rybalka.html', 'img': '', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xb0 \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xb0\xd0\xbb\xd0\xba\xd0\xb0'},
{'url': 'http://tvua.biz/ohotnik-i-rybolov.html', 'img': '', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2'},
{'url': 'http://tvua.biz/outdoor-channel.html', 'img': '', 'title': 'Outdoor Channel'},
{'url': 'http://tvua.biz/morskoy.html', 'img': '', 'title': '\xd0\x9c\xd0\xbe\xd1\x80\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9'},
{'url': 'http://tvua.biz/moya-planeta.html', 'img': '', 'title': '\xd0\x9c\xd0\xbe\xd1\x8f \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'http://tvua.biz/zivaya-planeta.html', 'img': '', 'title': '\xd0\x96\xd0\xb8\xd0\xb2\xd0\xb0\xd1\x8f \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'http://tvua.biz/oruzhie.html', 'img': '', 'title': '\xd0\x9e\xd1\x80\xd1\x83\xd0\xb6\xd0\xb8\xd0\xb5'},
{'url': 'http://tvua.biz/365-dney.html', 'img': '', 'title': '365 \xd0\xb4\xd0\xbd\xd0\xb5\xd0\xb9'},
{'url': 'http://tvua.biz/istoriya.html', 'img': '', 'title': '\xd0\x98\xd1\x81\xd1\x82\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f'},
{'url': 'http://tvua.biz/nauka.html', 'img': '', 'title': '\xd0\xbd\xd0\xb0\xd1\x83\xd0\xba\xd0\xb0 2.0'},
{'url': 'http://tvua.biz/t24.html', 'img': '', 'title': '\xd0\xa224'},
{'url': 'http://tvua.biz/mega.html', 'img': '', 'title': '\xd0\x9c\xd0\x95\xd0\x93\xd0\x90'},
{'url': 'http://tvua.biz/sovershenno-sekretno.html', 'img': '', 'title': '\xd0\xa1\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x80\xd1\x88\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xbe \xd1\x81\xd0\xb5\xd0\xba\xd1\x80\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe'},
{'url': 'http://tvua.biz/tet.html', 'img': '', 'title': '\xd0\xa2\xd0\x95\xd0\xa2'},
{'url': 'http://tvua.biz/oce.html', 'img': '', 'title': '\xd0\x9e\xd0\xa6\xd0\x95'},
{'url': 'http://tvua.biz/9-kanal-izrail.html', 'img': '', 'title': '9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\x98\xd0\xb7\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbb\xd1\x8c'},
{'url': 'http://tvua.biz/match.html', 'img': '', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87!'},
{'url': 'http://tvua.biz/match-arena.html', 'img': '', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87 \xd0\xb0\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb0'},
{'url': 'http://tvua.biz/match-igra.html', 'img': '', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\x98\xd0\xb3\xd1\x80\xd0\xb0'},
{'url': 'http://tvua.biz/match-futbol-1.html', 'img': '', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 1'},
{'url': 'http://tvua.biz/boks-tv.html', 'img': '', 'title': '\xd0\x91\xd0\xbe\xd0\xba\xd1\x81 \xd0\xa2\xd0\x92'},
{'url': 'http://tvua.biz/khl.html', 'img': '', 'title': '\xd0\x9a\xd0\xa5\xd0\x9b'},
{'url': 'http://tvua.biz/xsport.html', 'img': '', 'title': 'Xsport'},
{'url': 'http://tvua.biz/viasatsport.html', 'img': '', 'title': 'Viasat Sport'},
{'url': 'http://tvua.biz/belarus-5.html', 'img': '', 'title': '\xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c 5'},
{'url': 'http://tvua.biz/setanta-sport.html', 'img': '', 'title': 'Setanta Sports'},
{'url': 'http://tvua.biz/setanta-sport-plus.html', 'img': '', 'title': 'Setanta Sports+'},
{'url': 'http://tvua.biz/mult.html', 'img': '', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82'},
{'url': 'http://tvua.biz/tlum.html', 'img': '', 'title': '\xd0\xa2\xd0\xbb\xd1\x83\xd0\xbc'},
{'url': 'http://tvua.biz/karusel.html', 'img': '', 'title': '\xd0\x9a\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd0\xb5\xd0\xbb\xd1\x8c'},
{'url': 'http://tvua.biz/2na2.html', 'img': '', 'title': '2x2'},
{'url': 'http://tvua.biz/ryzhiy.html', 'img': '', 'title': '\xd0\xa0\xd1\x8b\xd0\xb6\xd0\xb8\xd0\xb9'},
{'url': 'http://tvua.biz/v-gostyah-u-skazki.html', 'img': '', 'title': '\xd0\x92 \xd0\xb3\xd0\xbe\xd1\x81\xd1\x82\xd1\x8f\xd1\x85 \xd1\x83 \xd1\x81\xd0\xba\xd0\xb0\xd0\xb7\xd0\xba\xd0\xb8'},
{'url': 'http://tvua.biz/tiji.html', 'img': '', 'title': 'Tiji'},
{'url': 'http://tvua.biz/nickelodeon.html', 'img': '', 'title': 'Nickelodeon'},
{'url': 'http://tvua.biz/nick-jr.html', 'img': '', 'title': 'Nick Jr'},
{'url': 'http://tvua.biz/disney.html', 'img': '', 'title': 'disney channel'},
{'url': 'http://tvua.biz/gulli.html', 'img': '', 'title': 'gulli'},
{'url': 'http://tvua.biz/cartoon-network.html', 'img': '', 'title': 'Cartoon Network'},
{'url': 'http://tvua.biz/ani.html', 'img': '', 'title': 'Ani'},
{'url': 'http://tvua.biz/duck-tv.html', 'img': '', 'title': 'Duck TV'},
{'url': 'http://tvua.biz/radost-moja.html', 'img': '', 'title': '\xd0\xa0\xd0\xb0\xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c \xd0\xbc\xd0\xbe\xd1\x8f'},
{'url': 'http://tvua.biz/m1.html', 'img': '', 'title': '\xd0\x9c1'},
{'url': 'http://tvua.biz/m2.html', 'img': '', 'title': 'M2'},
{'url': 'http://tvua.biz/zhara.html', 'img': '', 'title': '\xd0\x96\xd0\x90\xd0\xa0\xd0\x90'},
{'url': 'http://tvua.biz/tnt-musik.html', 'img': '', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2 MUSIC'},
{'url': 'http://tvua.biz/muz-tv.html', 'img': '', 'title': '\xd0\x9c\xd1\x83\xd0\xb7-\xd0\xa2\xd0\x92'},
{'url': 'http://tvua.biz/ru-tv.html', 'img': '', 'title': 'RU TV'},
{'url': 'http://tvua.biz/lya-minor.html', 'img': '', 'title': '\xd0\xbb\xd1\x8f \xd0\xbc\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x80'},
{'url': 'http://tvua.biz/shanson.html', 'img': '', 'title': '\xd0\xa8\xd0\xb0\xd0\xbd\xd1\x81\xd0\xbe\xd0\xbd \xd0\xa2\xd0\x92'},
{'url': 'http://tvua.biz/europaplus.html', 'img': '', 'title': 'Europa Plus TV'},
{'url': 'http://tvua.biz/vh1.html', 'img': '', 'title': 'VH1 Europe'},
{'url': 'http://tvua.biz/vh1clas.html', 'img': '', 'title': 'VH1 Classic'},
{'url': 'http://tvua.biz/mcm-top.html', 'img': '', 'title': 'MCM Top'},
{'url': 'http://tvua.biz/mtv-hits.html', 'img': '', 'title': 'MTV Hits'},
{'url': 'http://tvua.biz/mtv-dance.html', 'img': '', 'title': 'MTV Dance'},
{'url': 'http://tvua.biz/112-ukrana.html', 'img': '', 'title': '112 \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'http://tvua.biz/24-telekanal-novin.html', 'img': '', 'title': '24 \xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb8\xd0\xbd'},
{'url': 'http://tvua.biz/news-one.html', 'img': '', 'title': 'News One'},
{'url': 'http://tvua.biz/5-kanal-ukraina.html', 'img': '', 'title': '5 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'http://tvua.biz/espreso-tv.html', 'img': '', 'title': '\xd0\xb5\xd1\x81\xd0\xbf\xd1\x80\xd0\xb5\xd1\x81\xd0\xbe tv'},
{'url': 'http://tvua.biz/hromadske.html', 'img': '', 'title': '\xd0\x93\xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xb4\xd1\x81\xd1\x8c\xd0\xba\xd0\xb5 \xd0\xa2\xd0\x92'},
{'url': 'http://tvua.biz/rossiya-24.html', 'img': '', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 24'},
{'url': 'http://tvua.biz/krym-24.html', 'img': '', 'title': '\xd0\x9a\xd0\xa0\xd0\xab\xd0\x9c 24'},
{'url': 'http://tvua.biz/belarus-24.html', 'img': '', 'title': '\xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c 24'},
{'url': 'http://tvua.biz/moskva-24.html', 'img': '', 'title': '\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0 24'},
{'url': 'http://tvua.biz/rbk-tv.html', 'img': '', 'title': '\xd0\xa0\xd0\x91\xd0\x9a'},
{'url': 'http://tvua.biz/izvestiya.html', 'img': '', 'title': '\xd0\x98\xd0\xb7\xd0\xb2\xd0\xb5\xd1\x81\xd1\x82\xd0\xb8\xd1\x8f'},
{'url': 'http://tvua.biz/russia-today.html', 'img': '', 'title': 'Russia today'},
{'url': 'http://tvua.biz/bbc-world-news.html', 'img': '', 'title': 'BBC News'},
{'url': 'http://tvua.biz/cnn.html', 'img': '', 'title': 'CNN'},
]
udata=1570184443.86