[
{'url': 'http://standart.tv/channel-1-eurosport1', 'img': 'http://standart.tv/storage/channels/1/default/eOONhfVMpTYHlbSk329m.png', 'title': 'Eurosport 1'},
{'url': 'http://standart.tv/channel-1-eurosport2', 'img': 'http://standart.tv/storage/channels/2/default/baBfUeExU8vVDDVoEkrd.png', 'title': 'Eurosport 2'},
{'url': 'http://standart.tv/channel-1-discovery-channel', 'img': 'http://standart.tv/storage/channels/3/default/TefnfkcjTCXI1slh2IEy.png', 'title': 'Discovery Channel'},
{'url': 'http://standart.tv/channel-1-tlc', 'img': 'http://standart.tv/storage/channels/5/default/DAWaYUqNx5bO30QHdvxz.png', 'title': 'TLC'},
{'url': 'http://standart.tv/channel-1-rentv', 'img': 'http://standart.tv/storage/channels/26/default/w4P8SSmr4CzkGFcRCbym.png', 'title': '\xd0\xa0\xd0\xb5\xd0\xbd \xd0\xa2\xd0\x92'},
{'url': 'http://standart.tv/channel-1-belarus5', 'img': 'http://standart.tv/storage/channels/4/default/1Fc5hhCgzFmtFI0BOQBA.png', 'title': '\xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c 5 HD'},
{'url': 'http://standart.tv/channel-ostrosiuzhetnoe-hd', 'img': 'http://standart.tv/storage/channels/11/default/ryXjJb5ZTZQ1K7TXMnnM.png', 'title': '\xd0\x9e\xd1\x81\xd1\x82\xd1\x80\xd0\xbe\xd1\x81\xd1\x8e\xd0\xb6\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe\xd0\xb5 HD'},
{'url': 'http://standart.tv/channel-1-kino-tv', 'img': 'http://standart.tv/storage/channels/6/default/MzHX8Dgq77aA5curNF6Y.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'http://standart.tv/channel-russky-roman', 'img': 'http://standart.tv/storage/channels/9/default/am36B8pSsRWIIMwWtdJF.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd'},
{'url': 'http://standart.tv/channel-1-kinopremiera-hd', 'img': 'http://standart.tv/storage/channels/25/default/0krsxbzpbCp1hIbA3LzS.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbf\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8c\xd0\xb5\xd1\x80\xd0\xb0'},
{'url': 'http://standart.tv/channel-1-domkino', 'img': 'http://standart.tv/storage/channels/10/default/YM3I1LLypTy3GuEeKmCP.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://standart.tv/channel-1-muzhskoe-kino', 'img': 'http://standart.tv/storage/channels/17/default/3rQCdSnwbhrW0DuL3D8a.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://standart.tv/channel-nashe-novoe-kino', 'img': 'http://standart.tv/storage/channels/24/default/PVZ62TCix4bECKapzXzg.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88\xd0\xb5 \xd0\xbd\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://standart.tv/channel-1-discovery-science', 'img': 'http://standart.tv/storage/channels/18/default/OyUAYVCcmN4xdeHONaxG.png', 'title': 'Discovery Science'},
{'url': 'http://standart.tv/channel-nat-geo-wild', 'img': 'http://standart.tv/storage/channels/42/default/LOYxWzlaKsSg1yOSY7wv.png', 'title': 'Nat Geo Wild'},
{'url': 'http://standart.tv/channel-kinosemiya', 'img': 'http://standart.tv/storage/channels/22/default/KXVg0Q2uNvxmzpuWlPRW.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb5\xd0\xbc\xd1\x8c\xd1\x8f'},
{'url': 'http://standart.tv/channel-1-kinoxit', 'img': 'http://standart.tv/storage/channels/14/default/J6ZTKP5mFAiPNa010e0k.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x85\xd0\xb8\xd1\x82'},
{'url': 'http://standart.tv/channel-1-national-geographic', 'img': 'http://standart.tv/storage/channels/15/default/vFTBGuIbG30mZ0lJwcDz.png', 'title': 'National Geographic'},
{'url': 'http://standart.tv/channel-tv1000-action', 'img': 'http://standart.tv/storage/channels/34/default/9fTYMddGptKH8XUjVDqC.png', 'title': 'TV1000 Action'},
{'url': 'http://standart.tv/channel-match-football1', 'img': 'http://standart.tv/storage/channels/13/default/zGgDuARGHP5x4lZowuwv.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 1'},
{'url': 'http://standart.tv/channel-1-viasat-sport', 'img': 'http://standart.tv/storage/channels/30/default/cCWBcMmABujTsp45Tht4.png', 'title': 'Viasat Sport'},
{'url': 'http://standart.tv/channel-doverie', 'img': 'http://standart.tv/storage/channels/12/default/WDntKRm0RsJS7SvL7Xr7.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0 \xd0\x94\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb5'},
{'url': 'http://standart.tv/channel-1-animal-planet', 'img': 'http://standart.tv/storage/channels/16/default/3Dp3R4XnLR4VJbRlhWbp.png', 'title': 'Animal Planet'},
{'url': 'http://standart.tv/channel-1-match-tv', 'img': 'http://standart.tv/storage/channels/69/default/2VDP3RquYbnQdJv4ej59.png', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87! \xd1\x82\xd0\xb2'},
{'url': 'http://standart.tv/channel-1-viasat-history', 'img': 'http://standart.tv/storage/channels/23/default/Jk0Ei7pVxGwPVQHRbBPw.png', 'title': 'Viasat History'},
{'url': 'http://standart.tv/channel-1-kinomiks', 'img': 'http://standart.tv/storage/channels/32/default/3nbcjnsoQOCr8JNfPDI2.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbc\xd0\xb8\xd0\xba\xd1\x81'},
{'url': 'http://standart.tv/channel-tv1000-russkoe-kino', 'img': 'http://standart.tv/storage/channels/1042/default/b0BzREGWsBVhVrMxi7Ef.png', 'title': 'TV1000 \xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://standart.tv/channel-1-sts', 'img': 'http://standart.tv/storage/channels/35/default/naEc5HZcVCHhZIdqjd1o.png', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1'},
{'url': 'http://standart.tv/channel-1-match-arena', 'img': 'http://standart.tv/storage/channels/20/default/KCJWfCEWFUOqG3wPTOQr.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\x90\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb0'},
{'url': 'http://standart.tv/channel-rodnoe-kino', 'img': 'http://standart.tv/storage/channels/29/default/JkjyHMpLrMuvjvVFqJ4j.png', 'title': '\xd0\xa0\xd0\xbe\xd0\xb4\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://standart.tv/channel-pervy', 'img': 'http://standart.tv/storage/channels/31/default/5VxF0N0aD0i3oOH9kuXk.png', 'title': '\xd0\xbf\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9'},
{'url': 'http://standart.tv/channel-1-match-igra', 'img': 'http://standart.tv/storage/channels/79/default/Zcoxa4VqHPCgB4PlpbOl.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\x98\xd0\xb3\xd1\x80\xd0\xb0'},
{'url': 'http://standart.tv/channel-russkaya-komedia', 'img': 'http://standart.tv/storage/channels/33/default/mQfQM43qGlZzJo4P0oK1.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd0\xba\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f'},
{'url': 'http://standart.tv/channel-kinokomedia', 'img': 'http://standart.tv/storage/channels/43/default/y17JzGKWN34ot87y0aId.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xba\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f'},
{'url': 'http://standart.tv/channel-cinema-ru', 'img': 'http://standart.tv/storage/channels/56/default/tvYPJ36mcHaAptlZ8eQj.png', 'title': 'Cinema'},
{'url': 'http://standart.tv/channel-piatnica', 'img': 'http://standart.tv/storage/channels/77/default/ObQnJXbqK6RV4AuoguzW.png', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd0\xbd\xd0\xb8\xd1\x86\xd0\xb0'},
{'url': 'http://standart.tv/channel-1-nst', 'img': 'http://standart.tv/storage/channels/19/default/NIIKxygOqxiqMdtWJyNx.png', 'title': '\xd0\x9d\xd0\xa1\xd0\xa2'},
{'url': 'http://standart.tv/channel-1-kinopremium-hd', 'img': 'http://standart.tv/storage/channels/72/default/Zzs7jePBmtqT5NC8Otso.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\x9f\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb8\xd1\x83\xd0\xbc HD'},
{'url': 'http://standart.tv/channel-1plus1', 'img': 'http://standart.tv/storage/channels/48/default/1plus1.png', 'title': '1+1'},
{'url': 'http://standart.tv/channel-1-ntv', 'img': 'http://standart.tv/storage/channels/51/default/Us0Iypy65I3aCt6UbBwf.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x92'},
{'url': 'http://standart.tv/channel-1-galaxy-tv', 'img': 'http://standart.tv/storage/channels/62/default/BPLraqtstYmJN5S4C2bv.png', 'title': 'galaxy tv'},
{'url': 'http://standart.tv/channel-1-kinopokaz-hd2', 'img': 'http://standart.tv/storage/channels/61/default/2PiNzvYwWl8yQ879PNpt.png', 'title': '\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd0\xb9\xd0\xbd\xd0\xbe\xd0\xb5'},
{'url': 'http://standart.tv/channel-1-tnt', 'img': 'http://standart.tv/storage/channels/53/default/R61P2a6Z9Av0nGaJoKhd.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2'},
{'url': 'http://standart.tv/channel-1-match-football3', 'img': 'http://standart.tv/storage/channels/101/default/3xRll1dW9otwCYF8ceIH.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 3'},
{'url': 'http://standart.tv/channel-1-tv1000', 'img': 'http://standart.tv/storage/channels/47/default/PJa7jxfzgLqiIDvoKUiP.png', 'title': 'TV1000'},
{'url': 'http://standart.tv/channel-ntv-xit', 'img': 'http://standart.tv/storage/channels/40/default/xHP1Wsw3uABBgS3Kf9Gt.png', 'title': '\xd0\xbd\xd1\x82\xd0\xb2 \xd1\x85\xd0\xb8\xd1\x82'},
{'url': 'http://standart.tv/channel-1-cartoon-network', 'img': 'http://standart.tv/storage/channels/36/default/1xt2LCAuE6mwb1pEl6RT.png', 'title': 'Cartoon Network'},
{'url': 'http://standart.tv/channel-1-kvn-tv', 'img': 'http://standart.tv/storage/channels/44/default/5h4XctsKDgeAnJSBKv4d.png', 'title': '\xd0\x9a\xd0\x92\xd0\x9d \xd0\xa2\xd0\x92'},
{'url': 'http://standart.tv/channel-kinosvidanie', 'img': 'http://standart.tv/storage/channels/57/default/vUZyz3Y10lh1NEKFaxEZ.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb2\xd0\xb8\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'},
{'url': 'http://standart.tv/channel-1-match-football2', 'img': 'http://standart.tv/storage/channels/21/default/T9oRPzMv6IFbEQ1cEKxf.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 2'},
{'url': 'http://standart.tv/channel-sony-scifi', 'img': 'http://standart.tv/storage/channels/50/default/PCy1IVaNZp4BZysnuAiF.png', 'title': 'Sony Sci-Fi'},
{'url': 'http://standart.tv/channel-1-kinopokaz', 'img': 'http://standart.tv/storage/channels/28/default/jlrlrZLgMFb7Uo9MXu4A.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbf\xd0\xbe\xd0\xba\xd0\xb0\xd0\xb7'},
{'url': 'http://standart.tv/channel-disney', 'img': 'http://standart.tv/storage/channels/74/default/D1addKbIpmb7KAQqQxhH.png', 'title': 'disney'},
{'url': 'http://standart.tv/channel-1-nash-detektiv', 'img': 'http://standart.tv/storage/channels/58/default/NUaNjRQ1on5rMwIAnT8E.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88 \xd0\xb4\xd0\xb5\xd1\x82\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2'},
{'url': 'http://standart.tv/channel-match-nash-sport', 'img': 'http://standart.tv/storage/channels/106/default/vtUrJb8pXdngRkpBpj6H.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\xa1\xd1\x82\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb0'},
{'url': 'http://standart.tv/channel-match-boets', 'img': 'http://standart.tv/storage/channels/95/default/EQgpVjkkqQBXdDl7x7tz.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\x91\xd0\xbe\xd0\xb5\xd1\x86'},
{'url': 'http://standart.tv/channel-1-tv3-ru', 'img': 'http://standart.tv/storage/channels/76/default/EhxjBt3EOta2CaI2ltHF.png', 'title': '\xd1\x82\xd0\xb23'},
{'url': 'http://standart.tv/channel-rossia1', 'img': 'http://standart.tv/storage/channels/54/default/qRU2CiSCm0mducSpPRuJ.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 1'},
{'url': 'http://standart.tv/channel-1-russky-detektiv', 'img': 'http://standart.tv/storage/channels/27/default/a4Zf9FFbNFoaEEPek4g6.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb4\xd0\xb5\xd1\x82\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2'},
{'url': 'http://standart.tv/channel-tnt4', 'img': 'http://standart.tv/storage/channels/59/default/8ePmrHnIGC2yzF17kYk5.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa24'},
{'url': 'http://standart.tv/channel-1-paramount-comedy', 'img': 'http://standart.tv/storage/channels/80/default/z4VP9liDIhyndplj7P52.png', 'title': 'Paramount Comedy'},
{'url': 'http://standart.tv/channel-match-premier', 'img': 'http://standart.tv/storage/channels/8/default/2IDSfETbxZ5fqryHuUJr.png', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87 \xd0\xbf\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8c\xd0\xb5\xd1\x80'},
{'url': 'http://standart.tv/channel-1-che', 'img': 'http://standart.tv/storage/channels/67/default/fHu4rtNKhfUjf5AjzTI2.png', 'title': '\xd0\xa7\xd0\xb5'},
{'url': 'http://standart.tv/channel-2na2', 'img': 'http://standart.tv/storage/channels/63/default/2x2.png', 'title': '2\xd1\x852'},
{'url': 'http://standart.tv/channel-1-history-ru', 'img': 'http://standart.tv/storage/channels/39/default/Q57Wg5JsdsZ6oNXiJh5O.png', 'title': 'History'},
{'url': 'http://standart.tv/channel-1-usadba', 'img': 'http://standart.tv/storage/channels/68/default/WHqPmww2ifJEmS8cKYbp.png', 'title': '\xd0\xa3\xd1\x81\xd0\xb0\xd0\xb4\xd1\x8c\xd0\xb1\xd0\xb0'},
{'url': 'http://standart.tv/channel-mult', 'img': 'http://standart.tv/storage/channels/60/default/VIJfXA0OGFzKcLm8l2Ei.png', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82'},
{'url': 'http://standart.tv/channel-kinopokaz-hd1', 'img': 'http://standart.tv/storage/channels/441/default/%D0%A8%D0%BE%D0%BA%D0%B8%D1%80%D1%83%D1%8E%D1%89%D0%B5%D0%B5.png', 'title': '\xd0\xa8\xd0\xbe\xd0\xba\xd0\xb8\xd1\x80\xd1\x83\xd1\x8e\xd1\x89\xd0\xb5\xd0\xb5'},
{'url': 'http://standart.tv/channel-1-zvezda', 'img': 'http://standart.tv/storage/channels/70/default/eZVippX0Sp6Kkcpc7p8S.png', 'title': '\xd0\x97\xd0\xb2\xd0\xb5\xd0\xb7\xd0\xb4\xd0\xb0'},
{'url': 'http://standart.tv/channel-1-match-planeta', 'img': 'http://standart.tv/storage/channels/52/default/LM3mSivVs0ZjiMQNxLSb.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\x9f\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'http://standart.tv/channel-tvxxi', 'img': 'http://standart.tv/storage/channels/55/default/aDZQ08ABfeDGYf14XPIs.png', 'title': 'TV XXI'},
{'url': 'http://standart.tv/channel-domashny', 'img': 'http://standart.tv/storage/channels/102/default/ZvJ18GmHP7m3Za0CVGvL.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc\xd0\xb0\xd1\x88\xd0\xbd\xd0\xb8\xd0\xb9'},
{'url': 'http://standart.tv/channel-1-istoria', 'img': 'http://standart.tv/storage/channels/116/default/EhLfbCR6ddUf2jyNhQ00.png', 'title': '\xd0\x98\xd1\x81\xd1\x82\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f'},
{'url': 'http://standart.tv/channel-1-russky-bestseller', 'img': 'http://standart.tv/storage/channels/41/default/DqeGqj0sYBC8LpeOwSyh.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb1\xd0\xb5\xd1\x81\xd1\x82\xd1\x81\xd0\xb5\xd0\xbb\xd0\xbb\xd0\xb5\xd1\x80'},
{'url': 'http://standart.tv/channel-vip-premiere', 'img': 'http://standart.tv/storage/channels/1162/default/zIejofEUinV5c24VR4C2.png', 'title': 'VIP Premiere HD'},
{'url': 'http://standart.tv/channel-kxl', 'img': 'http://standart.tv/storage/channels/38/default/N9nWVhqM3FazWDMiQhwR.png', 'title': '\xd0\xba\xd1\x85\xd0\xbb \xd1\x82\xd0\xb2'},
{'url': 'http://standart.tv/channel-rossia-24', 'img': 'http://standart.tv/storage/channels/91/default/UwMTPUWroeKMZVbzbkDJ.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 24'},
{'url': 'http://standart.tv/channel-1-box-tv', 'img': 'http://standart.tv/storage/channels/37/default/2GQBU4n1dVNzU3yrSza9.png', 'title': '\xd0\x91\xd0\xbe\xd0\xba\xd1\x81 \xd0\xa2\xd0\x92'},
{'url': 'http://standart.tv/channel-zee-tv', 'img': 'http://standart.tv/storage/channels/49/default/hCV2C3drTLyTZnNBjcWk.png', 'title': 'zee tv'},
{'url': 'http://standart.tv/channel-1-lubimoe-kino', 'img': 'http://standart.tv/storage/channels/45/default/hAfqJKrEPgI0n5WsZDez.png', 'title': '\xd0\x9b\xd1\x8e\xd0\xb1\xd0\xb8\xd0\xbc\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://standart.tv/channel-1-fox', 'img': 'http://standart.tv/storage/channels/81/default/XSRH9U3dD4hMWyOkjDeW.png', 'title': 'Fox'},
{'url': 'http://standart.tv/channel-1-5kanal-ru', 'img': 'http://standart.tv/storage/channels/64/default/MaMUxLeg2L4HyhGydzZo.png', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'http://standart.tv/channel-tvcentr', 'img': 'http://standart.tv/storage/channels/84/default/X760d19qu1qVWOFfpL5q.png', 'title': '\xd0\xa2\xd0\x92 \xd0\xa6\xd0\xb5\xd0\xbd\xd1\x82\xd1\x80'},
{'url': 'http://standart.tv/channel-nash-kinoroman', 'img': 'http://standart.tv/storage/channels/100/default/RzF5OLOGrOeNFJZ3kDSa.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd'},
{'url': 'http://standart.tv/channel-novy-kanal-ua', 'img': 'http://standart.tv/storage/channels/97/default/z8TIcLY7K6YRwZ247mnp.png', 'title': '\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'http://standart.tv/channel-1-texno-24', 'img': 'http://standart.tv/storage/channels/85/default/Q90W9SOHY9A4Y4BrZ5vn.png', 'title': '\xd0\xa2\xd0\xb5\xd1\x85\xd0\xbd\xd0\xbe 24'},
{'url': 'http://standart.tv/channel-1-kinoseria', 'img': 'http://standart.tv/storage/channels/65/default/Yo6KeUadzgUzWplhNguu.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb5\xd1\x80\xd0\xb8\xd1\x8f'},
{'url': 'http://standart.tv/channel-1-super', 'img': 'http://standart.tv/storage/channels/92/default/RIZNApYWrMhstC9eKClS.png', 'title': '\xd1\x81\xd1\x83\xd0\xbf\xd0\xb5\xd1\x80'},
{'url': 'http://standart.tv/channel-oxota-i-rybalka', 'img': 'http://standart.tv/storage/channels/89/default/60LPoGJCj9eNn09YFriv.png', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xb0 \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xb0\xd0\xbb\xd0\xba\xd0\xb0'},
{'url': 'http://standart.tv/channel-ictv-ua', 'img': 'http://standart.tv/storage/channels/391/default/r1tuQOLcyqswxA6oSXzC.png', 'title': 'ICTV'},
{'url': 'http://standart.tv/channel-telekafe', 'img': 'http://standart.tv/storage/channels/104/default/R3U505sYMmQGeRSfwZgm.png', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xba\xd0\xb0\xd1\x84\xd0\xb5'},
{'url': 'http://standart.tv/channel-1-vip-comedy', 'img': 'http://standart.tv/storage/channels/107/default/vbvzU3v0muAmMRLygOEc.png', 'title': 'VIP Comedy'},
{'url': 'http://standart.tv/channel-1-78kanal', 'img': 'http://standart.tv/storage/channels/139/default/78.png', 'title': '78'},
{'url': 'http://standart.tv/channel-1-sony-turbo', 'img': 'http://standart.tv/storage/channels/82/default/J8bPtrsqMBnP8XKKOolP.png', 'title': 'Sony Turbo'},
{'url': 'http://standart.tv/channel-bobior', 'img': 'http://standart.tv/storage/channels/111/default/2rTWAe5vJEpLVJKKQkbN.png', 'title': '\xd0\xb1\xd0\xbe\xd0\xb1\xd0\xb5\xd1\x80'},
{'url': 'http://standart.tv/channel-nickelodeon-ru', 'img': 'http://standart.tv/storage/channels/98/default/kV1pY7293bG76TZTsjBC.png', 'title': 'Nickelodeon'},
{'url': 'http://standart.tv/channel-1-klassika-kino', 'img': 'http://standart.tv/storage/channels/87/default/RJE3SvUACThOIcLU2K5K.png', 'title': '\xd0\x9a\xd0\xbb\xd0\xb0\xd1\x81\xd1\x81\xd0\xb8\xd0\xba\xd0\xb0 \xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://standart.tv/channel-1-sts-int', 'img': 'http://standart.tv/storage/channels/148/default/YuPKYHQ3nYgHKZgMSlzr.png', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1 International'},
{'url': 'http://standart.tv/channel-oruzhie', 'img': 'http://standart.tv/storage/channels/66/default/IKmEhJBx9KRRzGtxaW7p.png', 'title': '\xd0\x9e\xd1\x80\xd1\x83\xd0\xb6\xd0\xb8\xd0\xb5'},
{'url': 'http://standart.tv/channel-karusel', 'img': 'http://standart.tv/storage/channels/114/default/ELCks8XIm4vGCGrrX9eT.png', 'title': '\xd0\x9a\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd0\xb5\xd0\xbb\xd1\x8c'},
{'url': 'http://standart.tv/channel-inter-ua', 'img': 'http://standart.tv/storage/channels/90/default/sVcsqruTXgkDgaInjfWZ.png', 'title': 'I\xd0\xbd\xd1\x82\xd0\xb5\xd1\x80'},
{'url': 'http://standart.tv/channel-kuxnia-tv', 'img': 'http://standart.tv/storage/channels/162/default/dnayuh7tj64icsvQITB7.png', 'title': '\xd0\x9a\xd1\x83\xd1\x85\xd0\xbd\xd1\x8f \xd0\xa2\xd0\x92'},
{'url': 'http://standart.tv/channel-multimuzyka', 'img': 'http://standart.tv/storage/channels/118/default/eYDgFuubwzIG6OIwkZl7.png', 'title': '\xd0\xbc\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82 \xd0\xb8 \xd0\xbc\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0'},
{'url': 'http://standart.tv/channel-112-ua', 'img': 'http://standart.tv/storage/channels/88/default/112.png', 'title': '112 \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'http://standart.tv/channel-mtv-russia', 'img': 'http://standart.tv/storage/channels/96/default/VoqriuUABlxdemL1CeY2.png', 'title': 'MTV Russia'},
{'url': 'http://standart.tv/channel-evrokino', 'img': 'http://standart.tv/storage/channels/83/default/1vJl3q7i5LSA6MsS0SU2.png', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://standart.tv/channel-1-nostalgia', 'img': 'http://standart.tv/storage/channels/86/default/bbdtsrg2vkGj6w2KAwYQ.png', 'title': '\xd0\x9d\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xb3\xd0\xb8\xd1\x8f'},
{'url': 'http://standart.tv/channel-dikaya-rybalka-hd', 'img': 'http://standart.tv/storage/channels/93/default/Jv2D1puB4qYIrLJTLaEE.png', 'title': '\xd0\x94\xd0\xb8\xd0\xba\xd0\xb0\xd1\x8f \xd1\x80\xd1\x8b\xd0\xb1\xd0\xb0\xd0\xbb\xd0\xba\xd0\xb0 HD'},
{'url': 'http://standart.tv/channel-ukraina', 'img': 'http://standart.tv/storage/channels/1124/default/VR4HEH9BEQ6PB6kjFcOT.png', 'title': '\xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd1\x97\xd0\xbd\xd0\xb0'},
{'url': 'http://standart.tv/channel-1-foxlife', 'img': 'http://standart.tv/storage/channels/78/default/x6RXHxrUni9m8oiRFWiA.png', 'title': 'Fox Life'},
{'url': 'http://standart.tv/channel-bolt', 'img': 'http://standart.tv/storage/channels/75/default/QHCaGSwqwLB2s1IEnrzz.png', 'title': 'Bolt'},
{'url': 'http://standart.tv/channel-izvestia', 'img': 'http://standart.tv/storage/channels/140/default/9cLox4xm0BnGrPffXfDY.png', 'title': '\xd0\x98\xd0\xb7\xd0\xb2\xd0\xb5\xd1\x81\xd1\x82\xd0\xb8\xd1\x8f'},
{'url': 'http://standart.tv/channel-1-domkino-premium', 'img': 'http://standart.tv/storage/channels/71/default/v6kRGCeIBNGFyFVtZG2S.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe \xd0\x9f\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb8\xd1\x83\xd0\xbc'},
{'url': 'http://standart.tv/channel-neizvestnaya-planeta', 'img': 'http://standart.tv/storage/channels/73/default/EUG6gCNAnFhzfmEdTjK0.png', 'title': '\xd0\x9d\xd0\xb5\xd0\xb8\xd0\xb7\xd0\xb2\xd0\xb5\xd1\x81\xd1\x82\xd0\xbd\xd0\xb0\xd1\x8f \xd0\x9f\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'http://standart.tv/channel-1-hollywood', 'img': 'http://standart.tv/storage/channels/113/default/VoEcBg3wPDfXrVqyOjYY.png', 'title': 'Hollywood'},
{'url': 'http://standart.tv/channel-moya-planeta', 'img': 'http://standart.tv/storage/channels/109/default/Pto1tcKd0Fi11fDTmbPM.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x8f \xd0\x9f\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'http://standart.tv/channel-1-ntv-serial', 'img': 'http://standart.tv/storage/channels/99/default/Mj6nvvC04dXlrjV8nf6D.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 \xd0\xa1\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb'},
{'url': 'http://standart.tv/channel-euronews', 'img': 'http://standart.tv/storage/channels/132/default/wMllKBCls0DNR6L4fE4L.png', 'title': 'euronews'},
{'url': 'http://standart.tv/channel-newsone-ua', 'img': 'http://standart.tv/storage/channels/112/default/dpJrusV1dDDNMoRijZzX.png', 'title': 'NewsOne'},
{'url': 'http://standart.tv/channel-1-ocean-tv', 'img': 'http://standart.tv/storage/channels/125/default/HVyx6aByiDGz94YYgtao.png', 'title': 'ocean tv'},
{'url': 'http://standart.tv/channel-indiyskoe-kino', 'img': 'http://standart.tv/storage/channels/130/default/Nm1uiwdyD4UgJZyiGSlm.png', 'title': '\xd0\x98\xd0\xbd\xd0\xb4\xd0\xb8\xd0\xb9\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://standart.tv/channel-setanta-sports', 'img': 'http://standart.tv/storage/channels/840/default/3rihmDqgtKTH2SFWHGCF.png', 'title': 'Setanta Sports'},
{'url': 'http://standart.tv/channel-1-dozhd', 'img': 'http://standart.tv/storage/channels/120/default/Fs3SOxUd3B3t74GVk5LQ.png', 'title': '\xd0\x94\xd0\xbe\xd0\xb6\xd0\xb4\xd1\x8c'},
{'url': 'http://standart.tv/channel-illuzion-plus', 'img': 'http://standart.tv/storage/channels/105/default/zfAgdrUigVG2EGmjwsF1.png', 'title': '\xd0\x98\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd +'},
{'url': 'http://standart.tv/channel-ua-pershy', 'img': 'http://standart.tv/storage/channels/166/default/bIOELndSc3oemDbMId20.png', 'title': 'UA:\xd0\x9f\xd0\xb5\xd1\x80\xd1\x88\xd0\xb8\xd0\xb9'},
{'url': 'http://standart.tv/channel-1-sts-love', 'img': 'http://standart.tv/storage/channels/117/default/pnQEiKFyYto4hNPxr76b.png', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1 Love'},
{'url': 'http://standart.tv/channel-setanta-sports-plus', 'img': 'http://standart.tv/storage/channels/842/default/oUSKbnmUAIjOqJlawbJ7.png', 'title': 'Setanta Sports+'},
{'url': 'http://standart.tv/channel-muztv', 'img': 'http://standart.tv/storage/channels/138/default/D2ppobC3FeQEt7vIUSro.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb7-\xd0\xa2\xd0\x92'},
{'url': 'http://standart.tv/channel-mir', 'img': 'http://standart.tv/storage/channels/124/default/CU3wJoxJhJJDhWtHgp5v.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x80'},
{'url': 'http://standart.tv/channel-1-yu', 'img': 'http://standart.tv/storage/channels/127/default/mghAu1KqrGpEnxHYLWLS.png', 'title': '\xd0\xae'},
{'url': 'http://standart.tv/channel-ru-tv', 'img': 'http://standart.tv/storage/channels/123/default/uaLWPVpes1QyyAvamAlT.png', 'title': 'ru.tv'},
{'url': 'http://standart.tv/channel-sarafan', 'img': 'http://standart.tv/storage/channels/94/default/eD6wrnM2x6dLwyWl3ma1.png', 'title': '\xd0\xa1\xd0\xb0\xd1\x80\xd0\xb0\xd1\x84\xd0\xb0\xd0\xbd'},
{'url': 'http://standart.tv/channel-stb-ua', 'img': 'http://standart.tv/storage/channels/932/default/oqRlUAugYFDtvAZQaznQ.png', 'title': '\xd0\xa1\xd0\xa2\xd0\x91'},
{'url': 'http://standart.tv/channel-1-ont-by', 'img': 'http://standart.tv/storage/channels/141/default/NiJTYbZqI3HZAM1lBUpc.png', 'title': '\xd0\x9e\xd0\x9d\xd0\xa2'},
{'url': 'http://standart.tv/channel-game-show', 'img': 'http://standart.tv/storage/channels/108/default/sclrXRjw3sdA47D1dvMz.png', 'title': 'Game Show'},
{'url': 'http://standart.tv/channel-krasnaya-linia', 'img': 'http://standart.tv/storage/channels/126/default/S3nhHLcGXiEEgptkB65P.png', 'title': '\xd0\x9a\xd1\x80\xd0\xb0\xd1\x81\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xbb\xd0\xb8\xd0\xbd\xd0\xb8\xd1\x8f'},
{'url': 'http://standart.tv/channel-komedia', 'img': 'http://standart.tv/storage/channels/119/default/6jjGbox6UCcoUtv7WOWZ.png', 'title': '\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f'},
{'url': 'http://standart.tv/channel-1-russky-illuzion', 'img': 'http://standart.tv/storage/channels/103/default/yG1lu0ND8gUS3JQuflTs.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb8\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd'},
{'url': 'http://standart.tv/channel-tnt-music', 'img': 'http://standart.tv/storage/channels/156/default/Vk7kKjjQOhToW6SHmPQj.png', 'title': '\xd1\x82\xd0\xbd\xd1\x82 music'},
{'url': 'http://standart.tv/channel-otr', 'img': 'http://standart.tv/storage/channels/182/default/folC4wkevKOIU8SGPi5f.png', 'title': '\xd0\x9e\xd0\xa2\xd0\xa0'},
{'url': 'http://standart.tv/channel-kultura', 'img': 'http://standart.tv/storage/channels/143/default/8ggL8v92hHrN8F6HsTcm.png', 'title': '\xd1\x80\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f \xd0\xba (\xd0\xba\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd1\x83\xd1\x80\xd0\xb0)'},
{'url': 'http://standart.tv/channel-vremia', 'img': 'http://standart.tv/storage/channels/134/default/p3exSj9KjmCPTN9pDnAW.png', 'title': '\xd0\x92\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f'},
{'url': 'http://standart.tv/channel-1-detsky-mir', 'img': 'http://standart.tv/storage/channels/133/default/RpAwh2xY7aiznwtWwEan.png', 'title': '\xd0\x94\xd0\xb5\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xbc\xd0\xb8\xd1\x80'},
{'url': 'http://standart.tv/channel-shanson-tv', 'img': 'http://standart.tv/storage/channels/136/default/4wGyrEHAJZVEYxjUJhjw.png', 'title': '\xd1\x88\xd0\xb0\xd0\xbd\xd1\x81\xd0\xbe\xd0\xbd tb'},
{'url': 'http://standart.tv/channel-konny-mir', 'img': 'http://standart.tv/storage/channels/129/default/b9rhAfMVkMKBLV5K4CYj.png', 'title': '\xd0\x9a\xd0\xbe\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\xbc\xd0\xb8\xd1\x80'},
{'url': 'http://standart.tv/channel-2plus2', 'img': 'http://standart.tv/storage/channels/1306/default/2plus2.png', 'title': '2+2'},
{'url': 'http://standart.tv/channel-8kanal-by', 'img': 'http://standart.tv/storage/channels/150/default/J2019U5aSBSLepeQYfso.png', 'title': '8 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c'},
{'url': 'http://standart.tv/channel-tlum-hd', 'img': 'http://standart.tv/storage/channels/115/default/wqPaiVPj2M7Vht93r887.png', 'title': '\xd0\xa2\xd0\xbb\xd1\x83\xd0\xbc HD'},
{'url': 'http://standart.tv/channel-mtv-hits', 'img': 'http://standart.tv/storage/channels/121/default/oOk55wZW6OBIW4gI8hzk.png', 'title': 'MTV Hits'},
{'url': 'http://standart.tv/channel-mir-seriala', 'img': 'http://standart.tv/storage/channels/135/default/0KLeGyJW1B5FVJwmh6Sm.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x80 \xd1\x81\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb\xd0\xb0'},
{'url': 'http://standart.tv/channel-hd-media', 'img': 'http://standart.tv/storage/channels/144/default/TDTmUwRASwbROlycjeFj.png', 'title': 'HD \xd0\x9c\xd0\xb5\xd0\xb4\xd0\xb8\xd0\xb0'},
{'url': 'http://standart.tv/channel-1-sony-tv', 'img': 'http://standart.tv/storage/channels/912/default/bRDS0HMZWTKRPEl2Apc5.png', 'title': 'Sony \xd0\xa2\xd0\x92 HD'},
{'url': 'http://standart.tv/channel-priamyj', 'img': 'http://standart.tv/storage/channels/157/default/ZwbcHUKeZjOYBVZEj6xQ.png', 'title': '\xd0\x9f\xd1\x80\xd1\x8f\xd0\xbc\xd0\xb8\xd0\xb9'},
{'url': 'http://standart.tv/channel-1-zhivi', 'img': 'http://standart.tv/storage/channels/164/default/zmTnCIOwfNcIspZIuWFE.png', 'title': '\xd0\x96\xd0\xb8\xd0\xb2\xd0\xb8'},
{'url': 'http://standart.tv/channel-bridge-tv', 'img': 'http://standart.tv/storage/channels/128/default/8oa1DpRWjwYHSDkfRCXq.png', 'title': 'Bridge TV'},
{'url': 'http://standart.tv/channel-1-rbk', 'img': 'http://standart.tv/storage/channels/193/default/6kWqiemS7bWMwXda0rRa.png', 'title': '\xd0\xa0\xd0\x91\xd0\x9a'},
{'url': 'http://standart.tv/channel-tnv-planeta', 'img': 'http://standart.tv/storage/channels/131/default/ulrCZgNbrKuqXa8Xzin3.png', 'title': '\xd0\xa2\xd0\x9d\xd0\x92-\xd0\x9f\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'http://standart.tv/channel-1-diskont', 'img': 'http://standart.tv/storage/channels/159/default/y7cXASuBkUOxKbPK5m62.png', 'title': '\xd0\x94\xd0\xb8\xd1\x81\xd0\xba\xd0\xbe\xd0\xbd\xd1\x82'},
{'url': 'http://standart.tv/channel-nano-tv', 'img': 'http://standart.tv/storage/channels/154/default/grPY5yaV3v6RNdOopdEC.png', 'title': '\xd0\xbd\xd0\xb0\xd0\xbd\xd0\xbe'},
{'url': 'http://standart.tv/channel-1-muzyka-pervogo', 'img': 'http://standart.tv/storage/channels/110/default/9GFt6y3dCVNjtdUPJJkW.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0 \xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd0\xbe\xd0\xb3\xd0\xbe'},
{'url': 'http://standart.tv/channel-1-skazki-zayki', 'img': 'http://standart.tv/storage/channels/151/default/5Yu68EM27rIfhHFC7Kmn.png', 'title': '\xd0\xa1\xd0\xba\xd0\xb0\xd0\xb7\xd0\xba\xd0\xb8 \xd0\x97\xd0\xb0\xd0\xb9\xd0\xba\xd0\xb8'},
{'url': 'http://standart.tv/channel-mir-24', 'img': 'http://standart.tv/storage/channels/175/default/JUpkLSELYPRhSvoRVgp8.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x80 24'},
{'url': 'http://standart.tv/channel-k1-ua', 'img': 'http://standart.tv/storage/channels/174/default/4bbJnXsn0DMsqrUhFND5.png', 'title': '\xd0\x9a1'},
{'url': 'http://standart.tv/channel-dacha', 'img': 'http://standart.tv/storage/channels/122/default/1AmEB1bADIqWhfGG2piz.png', 'title': '\xd0\x94\xd0\xb0\xd1\x87\xd0\xb0'},
{'url': 'http://standart.tv/channel-1-ntn-ua', 'img': 'http://standart.tv/storage/channels/146/default/BEBDT4vc2aPY4XtuIKAE.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x9d'},
{'url': 'http://standart.tv/channel-epik-drama', 'img': 'http://standart.tv', 'title': 'Epic Drama'},
{'url': 'http://standart.tv/channel-1-russian-musicbox', 'img': 'http://standart.tv/storage/channels/145/default/oMA34xepMWs9b1ZKksNP.png', 'title': 'Russian MusicBox'},
{'url': 'http://standart.tv/channel-1-stv-by', 'img': 'http://standart.tv/storage/channels/142/default/c1de53nAukv85uToRasB.png', 'title': '\xd0\xa1\xd0\xa2\xd0\x92 \xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c'},
{'url': 'http://standart.tv/channel-multimania', 'img': 'http://standart.tv/storage/channels/535/default/4MpeQTqY4BmIS2pf4rMH.png', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd0\xb8\xd0\xbc\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f'},
{'url': 'http://standart.tv/channel-eda', 'img': 'http://standart.tv/storage/channels/155/default/ikZvZ6bcyWG0DAgXPGiy.png', 'title': '\xd0\x95\xd0\xb4\xd0\xb0'},
{'url': 'http://standart.tv/channel-tet-ua', 'img': 'http://standart.tv/storage/channels/973/default/NBx53Ng1I03rtnAcdV2w.png', 'title': '\xd0\xa2\xd0\x95\xd0\xa2'},
{'url': 'http://standart.tv/channel-sankt-peterburg', 'img': 'http://standart.tv/storage/channels/149/default/tegPj9XbcvDUecaQgun4.png', 'title': '\xd0\xa1\xd0\xb0\xd0\xbd\xd0\xba\xd1\x82-\xd0\x9f\xd0\xb5\xd1\x82\xd0\xb5\xd1\x80\xd0\xb1\xd1\x83\xd1\x80\xd0\xb3'},
{'url': 'http://standart.tv/channel-feniks-plus-kino', 'img': 'http://standart.tv/storage/channels/322/default/VmjovjZYteQYjwtu7iDP.png', 'title': '\xd0\xa4\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xba\xd1\x81+ \xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://standart.tv/channel-1hd', 'img': 'http://standart.tv/storage/channels/158/default/1hd_music.png', 'title': '1HD'},
{'url': 'http://standart.tv/channel-amedia2', 'img': 'http://standart.tv/storage/channels/137/default/O3uEj1fXqQ5zP7EroxHI.png', 'title': '\xd0\x902'},
{'url': 'http://standart.tv/channel-5kanal-ua', 'img': 'http://standart.tv/storage/channels/181/default/9uYmRbn8pRdHyVcLUjqu.png', 'title': '5 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'http://standart.tv/channel-onemuz', 'img': 'http://standart.tv/storage/channels/191/default/jiUIMYHmk0CFPNdBPEjs.png', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xbc\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb9'},
{'url': 'http://standart.tv/channel-atr-ua', 'img': 'http://standart.tv/storage/channels/152/default/atr-ua.png', 'title': 'ATR'},
{'url': 'http://standart.tv/channel-dorama', 'img': 'http://standart.tv/storage/channels/259/default/dMu2fzQCryTNSjr98G2w.png', 'title': '\xd0\x94\xd0\xbe\xd1\x80\xd0\xb0\xd0\xbc\xd0\xb0'},
{'url': 'http://standart.tv/channel-lale', 'img': 'http://standart.tv/storage/channels/173/default/VfDExYXqFklsNY3gv9nr.png', 'title': 'Lale'},
{'url': 'http://standart.tv/channel-trofey', 'img': 'http://standart.tv/storage/channels/178/default/ndIrJgihTYySK1cf8GSK.png', 'title': '\xd0\xa2\xd1\x80\xd0\xbe\xd1\x84\xd0\xb5\xd0\xb9'},
{'url': 'http://standart.tv/channel-moskva-24', 'img': 'http://standart.tv/storage/channels/171/default/EamyZ805fY3U2DinPPhO.png', 'title': '\xd0\xbc\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0 24'},
{'url': 'http://standart.tv/channel-1-rostov-papa', 'img': 'http://standart.tv/storage/channels/168/default/gJzrsSXmctTtPgrdloXa.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x82\xd0\xbe\xd0\xb2-\xd0\xbf\xd0\xb0\xd0\xbf\xd0\xb0'},
{'url': 'http://standart.tv/channel-bst', 'img': 'http://standart.tv/storage/channels/163/default/RhM4RzJBPmpBn4POqT5t.png', 'title': '\xd0\x91\xd0\xa1\xd0\xa2'},
{'url': 'http://standart.tv/channel-mega-ua', 'img': 'http://standart.tv/storage/channels/167/default/uC1ZMBQdCO3yRe9p7cfC.png', 'title': '\xd0\x9c\xd0\xb5\xd0\xb3\xd0\xb0'},
{'url': 'http://standart.tv/channel-pervy-meteo', 'img': 'http://standart.tv/storage/channels/183/default/j4MYZ7CdJiiHEHUcCfAd.png', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xbc\xd0\xb5\xd1\x82\xd0\xb5\xd0\xbe'},
{'url': 'http://standart.tv/channel-1-mir-premium', 'img': 'http://standart.tv/storage/channels/184/default/OgoTghSmSRQpj1yYxFXq.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x80 Premium'},
{'url': 'http://standart.tv/channel-m1-ua', 'img': 'http://standart.tv/storage/channels/169/default/XMZuWRLrbgvVKHNlVqQE.png', 'title': '\xd0\x9c1'},
{'url': 'http://standart.tv/channel-bolshaya-azia', 'img': 'http://standart.tv/storage/channels/160/default/XPa1g9FNH9PmHye8CRpq.png', 'title': '\xd0\x91\xd0\xbe\xd0\xbb\xd1\x8c\xd1\x88\xd0\xb0\xd1\x8f \xd0\x90\xd0\xb7\xd0\xb8\xd1\x8f'},
{'url': 'http://standart.tv/channel-voprosy-i-otvety', 'img': 'http://standart.tv/storage/channels/153/default/YoXHHvLRrUqehoJB73dA.png', 'title': '\xd0\x92\xd0\xbe\xd0\xbf\xd1\x80\xd0\xbe\xd1\x81\xd1\x8b \xd0\xb8 \xd0\xbe\xd1\x82\xd0\xb2\xd0\xb5\xd1\x82\xd1\x8b'},
{'url': 'http://standart.tv/channel-nashe-tv', 'img': 'http://standart.tv/storage/channels/189/default/VdRpFQ2J16XZlD8Tu5Vy.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88\xd0\xb5 \xd0\xa2\xd0\x92'},
{'url': 'http://standart.tv/channel-rtd-ru', 'img': 'http://standart.tv/storage/channels/185/default/y0IXKn1URRFjqkrbRvy4.png', 'title': 'RT \xd0\x94 \xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9'},
{'url': 'http://standart.tv/channel-tdk-42', 'img': 'http://standart.tv/storage/channels/206/default/RLGXkul9LZeDQK2sil9L.png', 'title': '\xd0\xa2\xd0\x94\xd0\x9a 42'},
{'url': 'http://standart.tv/channel-krik-tv', 'img': 'http://standart.tv/storage/channels/224/default/LB1SoTZKBhubbUL9IFPa.png', 'title': '\xd0\xba\xd1\x80\xd0\xb8\xd0\xba \xd1\x82\xd0\xb2'},
{'url': 'http://standart.tv/channel-zhara', 'img': 'http://standart.tv/storage/channels/161/default/IAnZLjVaK5PO8TI9lCir.png', 'title': '\xd0\x96\xd0\xb0\xd1\x80\xd0\xb0'},
{'url': 'http://standart.tv/channel-21-kanal-uzhgorod', 'img': 'http://standart.tv/storage/channels/172/default/88HB4sEboLYzGgLCfPd8.png', 'title': '21 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xa3\xd0\xb6\xd0\xb3\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb4'},
{'url': 'http://standart.tv/channel-1-cctv-ru', 'img': 'http://standart.tv/storage/channels/198/default/aiEof4Rh8PLqGUkYGnTb.png', 'title': 'CGTN \xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9'},
{'url': 'http://standart.tv/channel-1-belarus24', 'img': 'http://standart.tv/storage/channels/201/default/YTJD55AqRYMO3TzXtFtX.png', 'title': '\xd0\xb1\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c 24'},
{'url': 'http://standart.tv/channel-brio-tv', 'img': 'http://standart.tv/storage/channels/196/default/xuvVWUiW6NNX9ZMFz8WD.png', 'title': 'Brio-TV'},
{'url': 'http://standart.tv/channel-musicbox-ua-hd', 'img': 'http://standart.tv/storage/channels/188/default/17aX8B4l0KqBRutEDgeG.png', 'title': 'MusicBox UA'},
{'url': 'http://standart.tv/channel-kyiv-ua', 'img': 'http://standart.tv/storage/channels/177/default/SCpkOdmKYUeBC1yAmBIA.png', 'title': '\xd0\x9a\xd0\xb8\xd1\x97\xd0\xb2'},
{'url': 'http://standart.tv/channel-34-dnepr', 'img': 'http://standart.tv/storage/channels/176/default/34.png', 'title': '34 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\x94\xd0\xbd\xd0\xb5\xd0\xbf\xd1\x80'},
{'url': 'http://standart.tv/channel-c-music-tv', 'img': 'http://standart.tv/storage/channels/186/default/4Jxh7bCMGRbtPwbrFQFT.png', 'title': 'C Music TV'},
{'url': 'http://standart.tv/channel-espreso-tv', 'img': 'http://standart.tv/storage/channels/232/default/UtVMzzFEFuK0EQGR4wSR.png', 'title': '\xd0\xb5\xd1\x81\xd0\xbf\xd1\x80\xd0\xb5\xd1\x81\xd0\xbe tv'},
{'url': 'http://standart.tv/channel-1-8kanal-ru', 'img': 'http://standart.tv/storage/channels/1338/default/Duzew40gD366Li1SDB3S.png', 'title': '8 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'http://standart.tv/channel-1-acb-tv', 'img': 'http://standart.tv/storage/channels/205/default/acb-tv.png', 'title': 'ACB TV'},
{'url': 'http://standart.tv/channel-rgvk-dagestan', 'img': 'http://standart.tv/storage/channels/190/default/rDOhVAHMAe6Qj6lw1fEB.png', 'title': '\xd0\xa0\xd0\x93\xd0\x92\xd0\x9a \xd0\x94\xd0\xb0\xd0\xb3\xd0\xb5\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd'},
{'url': 'http://standart.tv/channel-doktor', 'img': 'http://standart.tv/storage/channels/187/default/iG4zh9ehMSF2xKZr85OY.png', 'title': '\xd0\x94\xd0\xbe\xd0\xba\xd1\x82\xd0\xbe\xd1\x80'},
{'url': 'http://standart.tv/channel-smaylik-tv', 'img': 'http://standart.tv/storage/channels/902/default/HgLfkwaPCrE2hEgzDm5g.png', 'title': '\xd0\xa1\xd0\xbc\xd0\xb0\xd0\xb9\xd0\xbb\xd0\xb8\xd0\xba \xd0\xa2\xd0\x92'},
{'url': 'http://standart.tv/channel-1-ktk-kz', 'img': 'http://standart.tv/storage/channels/165/default/UN2bSsl5TNU431SUL68k.png', 'title': '\xd0\x9a\xd0\xa2\xd0\x9a'},
{'url': 'http://standart.tv/channel-ua-tv', 'img': 'http://standart.tv/storage/channels/192/default/eoK4uzNgeWREAHXxBiTp.png', 'title': 'UATV'},
{'url': 'http://standart.tv/channel-12-omsk', 'img': 'http://standart.tv/storage/channels/199/default/2pzKAFcv6uhPkqbGZzgp.png', 'title': '12 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\x9e\xd0\xbc\xd1\x81\xd0\xba'},
{'url': 'http://standart.tv/channel-ots', 'img': 'http://standart.tv/storage/channels/211/default/zhuUjIduMDDK1pDrk2nf.png', 'title': '\xd0\x9e\xd0\xa2\xd0\xa1'},
{'url': 'http://standart.tv/channel-spas', 'img': 'http://standart.tv/storage/channels/918/default/QgvQqhxwqqOrEJaWebkY.png', 'title': '\xd1\x81\xd0\xbf\xd0\xb0\xd1\x81'},
{'url': 'http://standart.tv/channel-tochka-tv', 'img': 'http://standart.tv/storage/channels/210/default/iSrB4ISeZpfOxiblYo2L.png', 'title': '\xd0\xa2\xd0\xbe\xd1\x87\xd0\xba\xd0\xb0'},
{'url': 'http://standart.tv/channel-sochi24', 'img': 'http://standart.tv/storage/channels/216/default/tYA31r3ch1sqyEHFY4nx.png', 'title': '\xd0\xa1\xd0\xbe\xd1\x87\xd0\xb8 24'},
{'url': 'http://standart.tv/channel-1-kaleydoskop-tv', 'img': 'http://standart.tv/storage/channels/209/default/GzueIljhu09lXnhhHzUk.png', 'title': '\xd0\x9a\xd0\xb0\xd0\xbb\xd0\xb5\xd0\xb9\xd0\xb4\xd0\xbe\xd1\x81\xd0\xba\xd0\xbe\xd0\xbf \xd0\xa2\xd0\x92'},
{'url': 'http://standart.tv/channel-mama', 'img': 'http://standart.tv/storage/channels/195/default/9f0Tc2wuGejq8ETS7nSq.png', 'title': '\xd0\x9c\xd0\xb0\xd0\xbc\xd0\xb0'},
{'url': 'http://standart.tv/channel-hromadske', 'img': 'http://standart.tv/storage/channels/219/default/tFiiAVhunou7PNTytuAz.png', 'title': '\xd0\xb3\xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xb4\xd1\x81\xd1\x8c\xd0\xba\xd0\xb5'},
{'url': 'http://standart.tv/channel-tv3-by', 'img': 'http://standart.tv/storage/channels/170/default/J0iVstCWZxoZC7vo3n3o.png', 'title': '\xd0\xa2\xd0\x923 \xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c'},
{'url': 'http://standart.tv/channel-kuban-24-orbita', 'img': 'http://standart.tv/storage/channels/228/default/nhpnpl33P5Lgt0pbi02c.png', 'title': '\xd0\x9a\xd1\x83\xd0\xb1\xd0\xb0\xd0\xbd\xd1\x8c 24 \xd0\x9e\xd1\x80\xd0\xb1\xd0\xb8\xd1\x82\xd0\xb0'},
{'url': 'http://standart.tv/channel-novoe-televidenie', 'img': 'http://standart.tv/storage/channels/213/default/j1pH88D2cKDt8Tr3X1WZ.png', 'title': '\xd0\x9d\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb5 \xd1\x82\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xb2\xd0\xb8\xd0\xb4\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5'},
{'url': 'http://standart.tv/channel-tumenskoe-vremia', 'img': 'http://standart.tv/storage/channels/221/default/CA7pVDUqqGxYN6fF9tGb.png', 'title': '\xd0\xa2\xd1\x8e\xd0\xbc\xd0\xb5\xd0\xbd\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xb2\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f'},
{'url': 'http://standart.tv/channel-astraxan24', 'img': 'http://standart.tv/storage/channels/230/default/4UUwv0f0oDmq3HrCvQCU.png', 'title': '\xd0\x90\xd1\x81\xd1\x82\xd1\x80\xd0\xb0\xd1\x85\xd0\xb0\xd0\xbd\xd1\x8c 24'},
{'url': 'http://standart.tv/channel-mir-belogoria', 'img': 'http://standart.tv/storage/channels/215/default/P6pdzYDZNL2MC5lFG4Ek.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x80 \xd0\x91\xd0\xb5\xd0\xbb\xd0\xbe\xd0\xb3\xd0\xbe\xd1\x80\xd1\x8c\xd1\x8f'},
{'url': 'http://standart.tv/channel-1-soyuz', 'img': 'http://standart.tv/storage/channels/217/default/qip9XxY3Mw3LWwHjWI5u.png', 'title': '\xd0\xa1\xd0\xbe\xd1\x8e\xd0\xb7'},
{'url': 'http://standart.tv/channel-nash-dom', 'img': 'http://standart.tv/storage/channels/212/default/hefU49f1nt71gQiOSBnq.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88 \xd0\xb4\xd0\xbe\xd0\xbc'},
{'url': 'http://standart.tv/channel-1-volgograd-24', 'img': 'http://standart.tv/storage/channels/203/default/403pVYRpmmaBMgXPf37V.png', 'title': '\xd0\x92\xd0\xbe\xd0\xbb\xd0\xb3\xd0\xbe\xd0\xb3\xd1\x80\xd0\xb0\xd0\xb4 24'},
{'url': 'http://standart.tv/channel-maliatko-tv', 'img': 'http://standart.tv/storage/channels/225/default/BJVMKazKK3zXFriQiIQ4.png', 'title': '\xd0\x9c\xd0\xb0\xd0\xbb\xd1\x8f\xd1\x82\xd0\xba\xd0\xbe TV'},
{'url': 'http://standart.tv/channel-1-luxury', 'img': 'http://standart.tv/storage/channels/218/default/2h3f74EsDQX1e4pJsMJ3.png', 'title': 'luxury'},
{'url': 'http://standart.tv/channel-prosveschenie', 'img': 'http://standart.tv/storage/channels/222/default/V1gikpHDqcP04mMCxF5y.png', 'title': '\xd0\x9f\xd1\x80\xd0\xbe\xd1\x81\xd0\xb2\xd0\xb5\xd1\x89\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5'},
{'url': 'http://standart.tv/channel-1-7kanal-kz', 'img': 'http://standart.tv/storage/channels/1330/default/ofq4EPLijjZMBRAn3ctA.png', 'title': '7 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'http://standart.tv/channel-1-xabar24', 'img': 'http://standart.tv/storage/channels/226/default/HBMuXifI5U2bMKXouojH.png', 'title': '\xd0\xa5\xd0\xb0\xd0\xb1\xd0\xb0\xd1\x80 24'},
{'url': 'http://standart.tv/channel-1-tdk-ru', 'img': 'http://standart.tv/storage/channels/197/default/N9JdEq7amJBnqeEPmqof.png', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xb2\xd0\xb8\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\xb4\xd0\xb0\xd0\xbc\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xba\xd0\xbb\xd1\x83\xd0\xb1'},
{'url': 'http://standart.tv/channel-vmeste-rf', 'img': 'http://standart.tv/storage/channels/223/default/DaddvP01NiR0xIxQdzYU.png', 'title': '\xd0\x92\xd0\xbc\xd0\xb5\xd1\x81\xd1\x82\xd0\xb5-\xd0\xa0\xd0\xa4'},
{'url': 'http://standart.tv/channel-novy-mir', 'img': 'http://standart.tv/storage/channels/594/default/%D0%9D%D0%BE%D0%B2%D1%8B%D0%B9-%D0%BC%D0%B8%D1%80.png', 'title': '\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xbc\xd0\xb8\xd1\x80'},
{'url': 'http://standart.tv/channel-lipeckoe-vremia', 'img': 'http://standart.tv/storage/channels/208/default/ln8XCSgUQmXYL5IB02Wi.png', 'title': '\xd0\x9b\xd0\xb8\xd0\xbf\xd0\xb5\xd1\x86\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xb2\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f'},
{'url': 'http://standart.tv/channel-1-leomax', 'img': 'http://standart.tv/storage/channels/200/default/JzhxKo1Y4UzUpqqKVCbL.png', 'title': 'Leomax'},
{'url': 'http://standart.tv/channel-krt-ua', 'img': 'http://standart.tv/storage/channels/207/default/NgUlQMx9GZ4g6nTv1aaH.png', 'title': '\xd0\x9a\xd0\xa0\xd0\xa2'},
{'url': 'http://standart.tv/channel-rti', 'img': 'http://standart.tv/storage/channels/204/default/CpsaJtuDBxZqhq8uELxd.png', 'title': '4 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd1\x8b RTi'},
{'url': 'http://standart.tv/channel-radost-moya', 'img': 'http://standart.tv/storage/channels/234/default/NpmFev6g3JXu14EHFhvz.png', 'title': '\xd0\xa0\xd0\xb0\xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c \xd0\xbc\xd0\xbe\xd1\x8f'},
{'url': 'http://standart.tv/channel-pravdatyt-kyiv', 'img': 'http://standart.tv', 'title': '\xd0\x9f\xd1\x80\xd0\xb0\xd0\xb2\xd0\xb4\xd0\xb0\xd0\xa2\xd0\xa3\xd0\xa2 \xd0\x9a\xd0\xb8\xd1\x97\xd0\xb2'},
{'url': 'http://standart.tv/channel-yuzhnaya-volna', 'img': 'http://standart.tv/storage/channels/180/default/OPOjAtt9D3thvkG5Lhzj.png', 'title': '\xd0\xae\xd0\xb6\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xb2\xd0\xbe\xd0\xbb\xd0\xbd\xd0\xb0'},
{'url': 'http://standart.tv/channel-foodman-club', 'img': 'http://standart.tv/storage/channels/339/default/Foodman-club.png', 'title': 'Foodman.club'},
{'url': 'http://standart.tv/channel-vetta24', 'img': 'http://standart.tv/storage/channels/231/default/imjeEfXNjEVQZgh9ekpf.png', 'title': '\xd0\x92\xd0\xb5\xd1\x82\xd1\x82\xd0\xb0 24 \xd0\x9f\xd0\xb5\xd1\x80\xd0\xbc\xd1\x8c'},
{'url': 'http://standart.tv/channel-1-kuraj', 'img': 'http://standart.tv/storage/channels/202/default/rjZL3fz5sIEqZU2UdLDl.png', 'title': '\xd0\x9a\xd1\x83\xd1\x80\xd0\xb0\xd0\xb9'},
{'url': 'http://standart.tv/channel-millet', 'img': 'http://standart.tv/storage/channels/508/default/R9fniqOsbKAQNySDVxgH.png', 'title': '\xd0\x9c\xd0\xb8\xd0\xbb\xd0\xbb\xd0\xb5\xd1\x82'},
{'url': 'http://standart.tv/channel-grozny', 'img': 'http://standart.tv/storage/channels/214/default/3GyhJuO5OpggfaD62t2N.png', 'title': '\xd0\x93\xd1\x80\xd0\xbe\xd0\xb7\xd0\xbd\xd1\x8b\xd0\xb9'},
{'url': 'http://standart.tv/channel-mostvideo', 'img': 'http://standart.tv/storage/channels/229/default/wBRtKPaAf0WfYrtwtaj4.png', 'title': 'MostVideo'},
{'url': 'http://standart.tv/channel-1-afontovo-kr', 'img': 'http://standart.tv/storage/channels/227/default/zDnL8afoUvvDZ8FYYbz8.png', 'title': '\xd0\x90\xd1\x84\xd0\xbe\xd0\xbd\xd1\x82\xd0\xbe\xd0\xb2\xd0\xbe \xd0\x9a\xd1\x80\xd0\xb0\xd1\x81\xd0\xbd\xd0\xbe\xd1\x8f\xd1\x80\xd1\x81\xd0\xba'},
]
udata=1579512381.27