[
{'url': 'http://vsetv.cc/1hd', 'img': 'http://vsetv.cc/img/1hd.jpg', 'title': '1HD'},
{'url': 'http://vsetv.cc/bridge', 'img': 'http://vsetv.cc/img/bridge.jpg', 'title': 'Bridge TV'},
{'url': 'http://vsetv.cc/europaplus', 'img': 'http://vsetv.cc/img/europaplus.jpg', 'title': 'Europa Plus TV'},
{'url': 'http://vsetv.cc/mtvdance', 'img': 'http://vsetv.cc/img/mtvdance.jpg', 'title': 'MTV Dance'},
{'url': 'http://vsetv.cc/mtvhits', 'img': 'http://vsetv.cc/img/mtvhits.jpg', 'title': 'MTV Hits'},
{'url': 'http://vsetv.cc/russianmusicbox', 'img': 'http://vsetv.cc/img/russianmusicbox.jpg', 'title': 'music box ru'},
{'url': 'http://vsetv.cc/rutv', 'img': 'http://vsetv.cc/img/rutv.jpg', 'title': 'RU TV'},
{'url': 'http://vsetv.cc/vh1classic', 'img': 'http://vsetv.cc/img/vh1classic.jpg', 'title': 'VH1 Classic'},
{'url': 'http://vsetv.cc/tntmusic', 'img': 'http://vsetv.cc/img/tntmusic.jpg', 'title': '\xd1\x82\xd0\xbd\xd1\x82 music'},
{'url': 'http://vsetv.cc/shanson', 'img': 'http://vsetv.cc/img/shanson.jpg', 'title': '\xd0\xa8\xd0\xb0\xd0\xbd\xd1\x81\xd0\xbe\xd0\xbd \xd0\xa2\xd0\x92'},
{'url': 'http://vsetv.cc/2x2', 'img': 'http://vsetv.cc/img/2x2.jpg', 'title': '2x2'},
{'url': 'http://vsetv.cc/360tv', 'img': 'http://vsetv.cc/img/360tv.jpg', 'title': '360 \xd0\xb3\xd1\x80\xd0\xb0\xd0\xb4\xd1\x83\xd1\x81\xd0\xbe\xd0\xb2'},
{'url': 'http://vsetv.cc/fashiontv', 'img': 'http://vsetv.cc/img/fashiontv.jpg', 'title': 'Fashion TV'},
{'url': 'http://vsetv.cc/mtvru', 'img': 'http://vsetv.cc/img/mtvru.jpg', 'title': 'MTV \xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f'},
{'url': 'http://vsetv.cc/mtvruhd', 'img': 'http://vsetv.cc/img/mtvruhd.jpg', 'title': 'MTV \xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f HD'},
{'url': 'http://vsetv.cc/shoppinglive', 'img': 'http://vsetv.cc/img/shoppinglive.jpg', 'title': 'Shopping Live'},
{'url': 'http://vsetv.cc/tlchd', 'img': 'http://vsetv.cc/img/tlchd.jpg', 'title': 'TLC HD'},
{'url': 'http://vsetv.cc/topshop', 'img': 'http://vsetv.cc/img/topshop.jpg', 'title': 'Top Shop'},
{'url': 'http://vsetv.cc/worldfashion', 'img': 'http://vsetv.cc/img/worldfashion.jpg', 'title': 'World Fashion'},
{'url': 'http://vsetv.cc/k1', 'img': 'http://vsetv.cc/img/k1.jpg', 'title': '\xd0\x9a1'},
{'url': 'http://vsetv.cc/ntvstyle', 'img': 'http://vsetv.cc/img/ntvstyle.jpg', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 \xd0\xa1\xd1\x82\xd0\xb8\xd0\xbb\xd1\x8c'},
{'url': 'http://vsetv.cc/retrotv', 'img': 'http://vsetv.cc/img/retrotv.jpg', 'title': '\xd1\x80\xd0\xb5\xd1\x82\xd1\x80\xd0\xbe \xd1\x82\xd0\xb2'},
{'url': 'http://vsetv.cc/sarafan', 'img': 'http://vsetv.cc/img/sarafan.jpg', 'title': '\xd1\x81\xd0\xb0\xd1\x80\xd0\xb0\xd1\x84\xd0\xb0\xd0\xbd \xd1\x82\xd0\xb2'},
{'url': 'http://vsetv.cc/ctclove', 'img': 'http://vsetv.cc/img/ctclove.jpg', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1 Love'},
{'url': 'http://vsetv.cc/tnthd', 'img': 'http://vsetv.cc/img/tnthd.jpg', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2 HD'},
{'url': 'http://vsetv.cc/u', 'img': 'http://vsetv.cc/img/u.jpg', 'title': '\xd0\xae'},
{'url': 'http://vsetv.cc/amedia1', 'img': 'http://vsetv.cc/img/amedia1.jpg', 'title': 'amedia 1'},
{'url': 'http://vsetv.cc/amedia2', 'img': 'http://vsetv.cc/img/amedia2.jpg', 'title': 'amedia 2'},
{'url': 'http://vsetv.cc/amediahithd', 'img': 'http://vsetv.cc/img/amediahithd.jpg', 'title': 'Amedia Hit HD'},
{'url': 'http://vsetv.cc/amediapremium', 'img': 'http://vsetv.cc/img/amediapremium.jpg', 'title': 'Amedia Premium'},
{'url': 'http://vsetv.cc/amediapremiumhd', 'img': 'http://vsetv.cc/img/amediapremiumhd.jpg', 'title': 'Amedia Premium HD'},
{'url': 'http://vsetv.cc/fox', 'img': 'http://vsetv.cc/img/fox.jpg', 'title': 'Fox'},
{'url': 'http://vsetv.cc/foxhd', 'img': 'http://vsetv.cc/img/foxhd.jpg', 'title': 'Fox HD'},
{'url': 'http://vsetv.cc/foxlife', 'img': 'http://vsetv.cc/img/foxlife.jpg', 'title': 'Fox Life'},
{'url': 'http://vsetv.cc/foxlifehd', 'img': 'http://vsetv.cc/img/foxlifehd.jpg', 'title': 'Fox Life HD'},
{'url': 'http://vsetv.cc/set', 'img': 'http://vsetv.cc/img/set.jpg', 'title': 'SET'},
{'url': 'http://vsetv.cc/sonyscifi', 'img': 'http://vsetv.cc/img/sonyscifi.jpg', 'title': 'Sony Sci-Fi'},
{'url': 'http://vsetv.cc/tv1000', 'img': 'http://vsetv.cc/img/tv1000.jpg', 'title': 'tv 1000'},
{'url': 'http://vsetv.cc/tv1000action', 'img': 'http://vsetv.cc/img/tv1000action.jpg', 'title': 'TV 1000 Action East'},
{'url': 'http://vsetv.cc/tv1000rus', 'img': 'http://vsetv.cc/img/tv1000rus.jpg', 'title': 'tv 1000 \xd1\x80\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://vsetv.cc/tv21', 'img': 'http://vsetv.cc/img/tv21.jpg', 'title': 'tv xxi'},
{'url': 'http://vsetv.cc/vipcomedyhd', 'img': 'http://vsetv.cc/img/vipcomedyhd.jpg', 'title': 'ViP Comedy HD'},
{'url': 'http://vsetv.cc/vipmegahithd', 'img': 'http://vsetv.cc/img/vipmegahithd.jpg', 'title': 'ViP Megahit HD'},
{'url': 'http://vsetv.cc/vippremiumhd', 'img': 'http://vsetv.cc/img/vippremiumhd.jpg', 'title': 'ViP Premiere HD'},
{'url': 'http://vsetv.cc/domkino', 'img': 'http://vsetv.cc/img/domkino.jpg', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://vsetv.cc/domkinopremiumhd', 'img': 'http://vsetv.cc/img/domkinopremiumhd.jpg', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe \xd0\x9f\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb8\xd1\x83\xd0\xbc HD'},
{'url': 'http://vsetv.cc/eurokino', 'img': 'http://vsetv.cc/img/eurokino.jpg', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://vsetv.cc/illusionplus', 'img': 'http://vsetv.cc/img/illusionplus.jpg', 'title': '\xd0\xb8\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd+'},
{'url': 'http://vsetv.cc/kinoseriya', 'img': 'http://vsetv.cc/img/kinoseriya.jpg', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb5\xd1\x80\xd0\xb8\xd1\x8f'},
{'url': 'http://vsetv.cc/nashelyubimoekino', 'img': 'http://vsetv.cc/img/nashelyubimoekino.jpg', 'title': '\xd0\x9d\xd0\xb0\xd1\x88\xd0\xb5 \xd0\xbb\xd1\x8e\xd0\xb1\xd0\xb8\xd0\xbc\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://vsetv.cc/strashnoe', 'img': 'http://vsetv.cc/img/strashnoe.jpg', 'title': '\xd0\x9d\xd0\xa1\xd0\xa2'},
{'url': 'http://vsetv.cc/ntvserial', 'img': 'http://vsetv.cc/img/ntvserial.jpg', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 \xd0\xa1\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb'},
{'url': 'http://vsetv.cc/ntn', 'img': 'http://vsetv.cc/img/ntn.jpg', 'title': '\xd0\xbd\xd1\x82\xd0\xbd (\xd1\x83\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0)'},
{'url': 'http://vsetv.cc/bestrussia', 'img': 'http://vsetv.cc/img/bestrussia.jpg', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb1\xd0\xb5\xd1\x81\xd1\x82\xd1\x81\xd0\xb5\xd0\xbb\xd0\xbb\xd0\xb5\xd1\x80'},
{'url': 'http://vsetv.cc/rudetective', 'img': 'http://vsetv.cc/img/rudetective.jpg', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb4\xd0\xb5\xd1\x82\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2'},
{'url': 'http://vsetv.cc/russkiyillusion', 'img': 'http://vsetv.cc/img/russkiyillusion.jpg', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb8\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd'},
{'url': 'http://vsetv.cc/rusroman', 'img': 'http://vsetv.cc/img/rusroman.jpg', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd'},
{'url': 'http://vsetv.cc/animalplanet', 'img': 'http://vsetv.cc/img/animalplanet.jpg', 'title': 'Animal Planet'},
{'url': 'http://vsetv.cc/animalplanethd', 'img': 'http://vsetv.cc/img/animalplanethd.jpg', 'title': 'Animal Planet HD'},
{'url': 'http://vsetv.cc/davincilearning', 'img': 'http://vsetv.cc/img/davincilearning.jpg', 'title': 'Da Vinci Learning'},
{'url': 'http://vsetv.cc/discovery', 'img': 'http://vsetv.cc/img/discovery.jpg', 'title': 'Discovery Channel'},
{'url': 'http://vsetv.cc/discoveryhd', 'img': 'http://vsetv.cc/img/discoveryhd.jpg', 'title': 'Discovery Channel HD'},
{'url': 'http://vsetv.cc/discoveryscience', 'img': 'http://vsetv.cc/img/discoveryscience.jpg', 'title': 'Discovery Science'},
{'url': 'http://vsetv.cc/discoverysciencehd', 'img': 'http://vsetv.cc/img/discoverysciencehd.jpg', 'title': 'Discovery Science HD'},
{'url': 'http://vsetv.cc/idxtrahd', 'img': 'http://vsetv.cc/img/idxtrahd.jpg', 'title': 'ID Xtra HD'},
{'url': 'http://vsetv.cc/natgeowild', 'img': 'http://vsetv.cc/img/natgeowild.jpg', 'title': 'Nat Geo Wild'},
{'url': 'http://vsetv.cc/natgeowildhd', 'img': 'http://vsetv.cc/img/natgeowildhd.jpg', 'title': 'Nat Geo Wild HD'},
{'url': 'http://vsetv.cc/natgeo', 'img': 'http://vsetv.cc/img/natgeo.jpg', 'title': 'National Geographic'},
{'url': 'http://vsetv.cc/natgeohd', 'img': 'http://vsetv.cc/img/natgeohd.jpg', 'title': 'National Geographic HD'},
{'url': 'http://vsetv.cc/ocean', 'img': 'http://vsetv.cc/img/ocean.jpg', 'title': 'Ocean-TV'},
{'url': 'http://vsetv.cc/rtg', 'img': 'http://vsetv.cc/img/rtg.jpg', 'title': 'RTG TV'},
{'url': 'http://vsetv.cc/rtdoc', 'img': 'http://vsetv.cc/img/rtdoc.jpg', 'title': 'Russia Today Doc'},
{'url': 'http://vsetv.cc/viasatexplore', 'img': 'http://vsetv.cc/img/viasatexplore.jpg', 'title': 'viasat explore'},
{'url': 'http://vsetv.cc/viasathistory', 'img': 'http://vsetv.cc/img/viasathistory.jpg', 'title': 'Viasat History'},
{'url': 'http://vsetv.cc/viasatnature', 'img': 'http://vsetv.cc/img/viasatnature.jpg', 'title': 'Viasat Nature East'},
{'url': 'http://vsetv.cc/bober', 'img': 'http://vsetv.cc/img/bober.jpg', 'title': '\xd0\xb1\xd0\xbe\xd0\xb1\xd0\xb5\xd1\x80'},
{'url': 'http://vsetv.cc/animalfamilyhd', 'img': 'http://vsetv.cc/img/animalfamilyhd.jpg', 'title': '\xd0\x92 \xd0\xbc\xd0\xb8\xd1\x80\xd0\xb5 \xd0\xb6\xd0\xb8\xd0\xb2\xd0\xbe\xd1\x82\xd0\xbd\xd1\x8b\xd1\x85 HD'},
{'url': 'http://vsetv.cc/timetv', 'img': 'http://vsetv.cc/img/timetv.jpg', 'title': '\xd0\x92\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f'},
{'url': 'http://vsetv.cc/doctv', 'img': 'http://vsetv.cc/img/doctv.jpg', 'title': '\xd0\x94\xd0\xbe\xd0\xba\xd1\x82\xd0\xbe\xd1\x80'},
{'url': 'http://vsetv.cc/edahd', 'img': 'http://vsetv.cc/img/edahd.jpg', 'title': '\xd0\x95\xd0\xb4\xd0\xb0 HD'},
{'url': 'http://vsetv.cc/liveplanet', 'img': 'http://vsetv.cc/img/liveplanet.jpg', 'title': '\xd0\x96\xd0\xb8\xd0\xb2\xd0\xb0\xd1\x8f \xd0\x9f\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'http://vsetv.cc/telezoo', 'img': 'http://vsetv.cc/img/telezoo.jpg', 'title': '\xd0\x97\xd0\xbe\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'http://vsetv.cc/zoopark', 'img': 'http://vsetv.cc/img/zoopark.jpg', 'title': '\xd0\xb7\xd0\xbe\xd0\xbe\xd0\xbf\xd0\xb0\xd1\x80\xd0\xba'},
{'url': 'http://vsetv.cc/istoriya', 'img': 'http://vsetv.cc/img/istoriya.jpg', 'title': '\xd0\x98\xd1\x81\xd1\x82\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f'},
{'url': 'http://vsetv.cc/moyaplaneta', 'img': 'http://vsetv.cc/img/moyaplaneta.jpg', 'title': '\xd0\x9c\xd0\xbe\xd1\x8f \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'http://vsetv.cc/nano', 'img': 'http://vsetv.cc/img/nano.jpg', 'title': '\xd0\xbd\xd0\xb0\xd0\xbd\xd0\xbe \xd1\x82\xd0\xb2'},
{'url': 'http://vsetv.cc/nauka', 'img': 'http://vsetv.cc/img/nauka.jpg', 'title': '\xd0\xbd\xd0\xb0\xd1\x83\xd0\xba\xd0\xb0 2.0'},
{'url': 'http://vsetv.cc/ntvpravo', 'img': 'http://vsetv.cc/img/ntvpravo.jpg', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 \xd0\x9f\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbe'},
{'url': 'http://vsetv.cc/adventurehd', 'img': 'http://vsetv.cc/img/adventurehd.jpg', 'title': '\xd0\x9f\xd1\x80\xd0\xb8\xd0\xba\xd0\xbb\xd1\x8e\xd1\x87\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f HD'},
{'url': 'http://vsetv.cc/psihologiya21', 'img': 'http://vsetv.cc/img/psihologiya21.jpg', 'title': '\xd0\x9f\xd1\x81\xd0\xb8\xd1\x85\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb3\xd0\xb8\xd1\x8f 21'},
{'url': 'http://vsetv.cc/rzd', 'img': 'http://vsetv.cc/img/rzd.jpg', 'title': '\xd1\x80\xd0\xb6\xd0\xb4 \xd1\x82\xd0\xb2'},
{'url': 'http://vsetv.cc/telecafe', 'img': 'http://vsetv.cc/img/telecafe.jpg', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xba\xd0\xb0\xd1\x84\xd0\xb5'},
{'url': 'http://vsetv.cc/teletravel', 'img': 'http://vsetv.cc/img/teletravel.jpg', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xbf\xd1\x83\xd1\x82\xd0\xb5\xd1\x88\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xb8\xd1\x8f'},
{'url': 'http://vsetv.cc/usadba', 'img': 'http://vsetv.cc/img/usadba.jpg', 'title': '\xd0\xa3\xd1\x81\xd0\xb0\xd0\xb4\xd1\x8c\xd0\xb1\xd0\xb0'},
{'url': 'http://vsetv.cc/cartoonnetwork', 'img': 'http://vsetv.cc/img/cartoonnetwork.jpg', 'title': 'Cartoon Network'},
{'url': 'http://vsetv.cc/disney', 'img': 'http://vsetv.cc/img/disney.jpg', 'title': 'disney channel'},
{'url': 'http://vsetv.cc/jimjam', 'img': 'http://vsetv.cc/img/jimjam.jpg', 'title': 'JimJam'},
{'url': 'http://vsetv.cc/nickjr', 'img': 'http://vsetv.cc/img/nickjr.jpg', 'title': 'nick jr.'},
{'url': 'http://vsetv.cc/nickelodeon', 'img': 'http://vsetv.cc/img/nickelodeon.jpg', 'title': 'Nickelodeon'},
{'url': 'http://vsetv.cc/nickelodeonhd', 'img': 'http://vsetv.cc/img/nickelodeonhd.jpg', 'title': 'Nickelodeon HD'},
{'url': 'http://vsetv.cc/tiji', 'img': 'http://vsetv.cc/img/tiji.jpg', 'title': 'TiJi'},
{'url': 'http://vsetv.cc/skazka', 'img': 'http://vsetv.cc/img/skazka.jpg', 'title': '\xd0\x92 \xd0\xb3\xd0\xbe\xd1\x81\xd1\x82\xd1\x8f\xd1\x85 \xd1\x83 \xd1\x81\xd0\xba\xd0\xb0\xd0\xb7\xd0\xba\xd0\xb8'},
{'url': 'http://vsetv.cc/detskiy', 'img': 'http://vsetv.cc/img/detskiy.jpg', 'title': '\xd0\x94\xd0\xb5\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9'},
{'url': 'http://vsetv.cc/detskiymir', 'img': 'http://vsetv.cc/img/detskiymir.jpg', 'title': '\xd0\x94\xd0\xb5\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xbc\xd0\xb8\xd1\x80'},
{'url': 'http://vsetv.cc/mama', 'img': 'http://vsetv.cc/img/mama.jpg', 'title': '\xd0\x9c\xd0\xb0\xd0\xbc\xd0\xb0'},
{'url': 'http://vsetv.cc/mult', 'img': 'http://vsetv.cc/img/mult.jpg', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82'},
{'url': 'http://vsetv.cc/dw', 'img': 'http://vsetv.cc/img/dw.jpg', 'title': 'Deutsche Welle'},
{'url': 'http://vsetv.cc/euronews', 'img': 'http://vsetv.cc/img/euronews.jpg', 'title': 'EuroNews'},
{'url': 'http://vsetv.cc/france24', 'img': 'http://vsetv.cc/img/france24.jpg', 'title': 'France 24'},
{'url': 'http://vsetv.cc/rt', 'img': 'http://vsetv.cc/img/rt.jpg', 'title': 'Russia Today'},
{'url': 'http://vsetv.cc/mir24', 'img': 'http://vsetv.cc/img/mir24.jpg', 'title': '\xd0\x9c\xd0\xb8\xd1\x80 24'},
{'url': 'http://vsetv.cc/m24', 'img': 'http://vsetv.cc/img/m24.jpg', 'title': '\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0 24'},
{'url': 'http://vsetv.cc/meteo', 'img': 'http://vsetv.cc/img/meteo.jpg', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\x9c\xd0\xb5\xd1\x82\xd0\xb5\xd0\xbe'},
{'url': 'http://vsetv.cc/rbc', 'img': 'http://vsetv.cc/img/rbc.jpg', 'title': '\xd0\xa0\xd0\x91\xd0\x9a'},
{'url': 'http://vsetv.cc/dtx', 'img': 'http://vsetv.cc/img/dtx.jpg', 'title': 'DTX'},
{'url': 'http://vsetv.cc/avto24', 'img': 'http://vsetv.cc/img/avto24.jpg', 'title': '\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe 24'},
{'url': 'http://vsetv.cc/drive', 'img': 'http://vsetv.cc/img/drive.jpg', 'title': '\xd0\xb4\xd1\x80\xd0\xb0\xd0\xb9\xd0\xb2 \xd1\x82\xd0\xb2'},
{'url': 'http://vsetv.cc/mans', 'img': 'http://vsetv.cc/img/mans.jpg', 'title': '\xd0\x9c\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9'},
{'url': 'http://vsetv.cc/ohotairybalka', 'img': 'http://vsetv.cc/img/ohotairybalka.jpg', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xb0 \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xb0\xd0\xbb\xd0\xba\xd0\xb0'},
{'url': 'http://vsetv.cc/ohotnikirybolov', 'img': 'http://vsetv.cc/img/ohotnikirybolov.jpg', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2'},
{'url': 'http://vsetv.cc/ohotnikirybolovhd', 'img': 'http://vsetv.cc/img/ohotnikirybolovhd.jpg', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2 HD'},
{'url': 'http://vsetv.cc/extremtv', 'img': 'http://vsetv.cc/img/extremtv.jpg', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x8d\xd0\xba\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd0\xbc'},
{'url': 'http://vsetv.cc/techno24', 'img': 'http://vsetv.cc/img/techno24.jpg', 'title': '\xd0\xa2\xd0\xb5\xd1\x85\xd0\xbd\xd0\xbe 24'},
{'url': 'http://vsetv.cc/eurosport1', 'img': 'http://vsetv.cc/img/eurosport1.jpg', 'title': 'Eurosport 1'},
{'url': 'http://vsetv.cc/eurosport1hd', 'img': 'http://vsetv.cc/img/eurosport1hd.jpg', 'title': 'Eurosport 1 HD'},
{'url': 'http://vsetv.cc/eurosport2', 'img': 'http://vsetv.cc/img/eurosport2.jpg', 'title': 'Eurosport 2'},
{'url': 'http://vsetv.cc/extremesports', 'img': 'http://vsetv.cc/img/extremesports.jpg', 'title': 'Extreme Sports'},
{'url': 'http://vsetv.cc/viasatsport', 'img': 'http://vsetv.cc/img/viasatsport.jpg', 'title': 'Viasat Sport'},
{'url': 'http://vsetv.cc/viasatsporthd', 'img': 'http://vsetv.cc/img/viasatsporthd.jpg', 'title': 'Viasat Sport HD'},
{'url': 'http://vsetv.cc/belarus5', 'img': 'http://vsetv.cc/img/belarus5.jpg', 'title': '\xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c 5'},
{'url': 'http://vsetv.cc/futbol', 'img': 'http://vsetv.cc/img/futbol.jpg', 'title': '\xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb'},
{'url': 'http://vsetv.cc/rtvi', 'img': 'http://vsetv.cc/img/rtvi.jpg', 'title': 'RTVi'},
{'url': 'http://vsetv.cc/belarus24', 'img': 'http://vsetv.cc/img/belarus24.jpg', 'title': '\xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c 24'},
{'url': 'http://vsetv.cc/vmesterf', 'img': 'http://vsetv.cc/img/vmesterf.jpg', 'title': '\xd0\x92\xd0\xbc\xd0\xb5\xd1\x81\xd1\x82\xd0\xb5 \xd0\xa0\xd0\xa4'},
{'url': 'http://vsetv.cc/inter', 'img': 'http://vsetv.cc/img/inter.jpg', 'title': '\xd0\x98\xd0\xbd\xd1\x82\xd0\xb5\xd1\x80'},
{'url': 'http://vsetv.cc/rline', 'img': 'http://vsetv.cc/img/rline.jpg', 'title': '\xd0\x9a\xd1\x80\xd0\xb0\xd1\x81\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xbb\xd0\xb8\xd0\xbd\xd0\xb8\xd1\x8f'},
{'url': 'http://vsetv.cc/krik', 'img': 'http://vsetv.cc/img/krik.jpg', 'title': '\xd0\xba\xd1\x80\xd0\xb8\xd0\xba \xd1\x82\xd0\xb2'},
{'url': 'http://vsetv.cc/mir', 'img': 'http://vsetv.cc/img/mir.jpg', 'title': '\xd0\x9c\xd0\xb8\xd1\x80'},
{'url': 'http://vsetv.cc/mirhd', 'img': 'http://vsetv.cc/img/mirhd.jpg', 'title': '\xd0\x9c\xd0\xb8\xd1\x80 HD'},
{'url': 'http://vsetv.cc/ntvhd', 'img': 'http://vsetv.cc/img/ntvhd.jpg', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 HD'},
{'url': 'http://vsetv.cc/1tvhd', 'img': 'http://vsetv.cc/img/1tvhd.jpg', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb HD'},
{'url': 'http://vsetv.cc/russia', 'img': 'http://vsetv.cc/img/russia.jpg', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 1'},
{'url': 'http://vsetv.cc/russiahd', 'img': 'http://vsetv.cc/img/russiahd.jpg', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f HD'},
{'url': 'http://vsetv.cc/soyuz', 'img': 'http://vsetv.cc/img/soyuz.jpg', 'title': '\xd0\xa1\xd0\xbe\xd1\x8e\xd0\xb7'},
{'url': 'http://vsetv.cc/spas', 'img': 'http://vsetv.cc/img/spas.jpg', 'title': '\xd0\xa1\xd0\xbf\xd0\xb0\xd1\x81 \xd0\xa2\xd0\x92'},
{'url': 'http://vsetv.cc/tbn', 'img': 'http://vsetv.cc/img/tbn.jpg', 'title': '\xd0\xa2\xd0\x91\xd0\x9d'},
{'url': 'http://vsetv.cc/tro', 'img': 'http://vsetv.cc/img/tro.jpg', 'title': '\xd0\xa2\xd0\xa0\xd0\x9e \xd0\xa1\xd0\xbe\xd1\x8e\xd0\xb7\xd0\xb0'},
]
udata=1592214089.15