[
{'url': 'ucom:http://ott-cdn.ucom.am/s60/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/005.png', 'title': 'disney channel'},
{'url': 'ucom:http://ott-cdn.ucom.am/s90/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/009.png', 'title': 'tv 1000'},
{'url': 'ucom:http://ott-cdn.ucom.am/s72/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/010.png', 'title': 'Viasat Explorer'},
{'url': 'ucom:http://ott-cdn.ucom.am/s70/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/011.png', 'title': 'Viasat History'},
{'url': 'ucom:http://ott-cdn.ucom.am/s95/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/012.png', 'title': 'tv 1000 \xd1\x80\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'ucom:http://ott-cdn.ucom.am/s71/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/014.png', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xbf\xd1\x83\xd1\x82\xd0\xb5\xd1\x88\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xb8\xd1\x8f'},
{'url': 'ucom:http://ott-cdn.ucom.am/s24/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/015.png', 'title': 'BBC World News'},
{'url': 'ucom:http://ott-cdn.ucom.am/s15/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/023.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f \xd0\xa0\xd0\xa2\xd0\xa0'},
{'url': 'ucom:http://ott-cdn.ucom.am/s21/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/024.png', 'title': '\xd1\x80\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 24'},
{'url': 'ucom:http://ott-cdn.ucom.am/s30/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/025.png', 'title': 'Fashion TV'},
{'url': 'ucom:http://ott-cdn.ucom.am/s35/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/026.png', 'title': 'Mezzo'},
{'url': 'ucom:http://ott-cdn.ucom.am/s97/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/031.png', 'title': 'ViP COMEDY'},
{'url': 'ucom:http://ott-cdn.ucom.am/s55/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/036.png', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2'},
{'url': 'ucom:http://ott-cdn.ucom.am/s49/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/040.png', 'title': 'MCM Top'},
{'url': 'ucom:http://ott-cdn.ucom.am/s20/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/061.png', 'title': '\xd0\xa6\xd0\xb5\xd0\xbd\xd1\x82\xd1\x80\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xb2\xd0\xb8\xd0\xb4\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5'},
{'url': 'ucom:http://ott-cdn.ucom.am/s54/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/064.png', 'title': '\xd1\x82\xd0\xb2\xd1\x86'},
{'url': 'ucom:http://ott-cdn.ucom.am/s31/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/066.png', 'title': '\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb4\xd0\xbd\xd1\x8b\xd0\xb9'},
{'url': 'ucom:http://ott-cdn.ucom.am/s1/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/067.png', 'title': '\xd4\xb1\xd5\xbc\xd5\xa1\xd5\xbb\xd5\xab\xd5\xb6 \xd4\xb1\xd5\xac\xd5\xab\xd6\x84'},
{'url': 'ucom:http://ott-cdn.ucom.am/s4/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/068.png', 'title': '\xd4\xb1\xd6\x80\xd5\xb4\xd5\xa5\xd5\xb6\xd5\xab\xd5\xa1 TV HD'},
{'url': 'ucom:http://ott-cdn.ucom.am/s3/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/069.png', 'title': '\xd5\x87\xd5\xa1\xd5\xb6\xd5\xa9'},
{'url': 'ucom:http://ott-cdn.ucom.am/s9/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/070.png', 'title': '\xd4\xb1\xd5\x90'},
{'url': 'ucom:http://ott-cdn.ucom.am/s2/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/071.png', 'title': '\xd5\x802'},
{'url': 'ucom:http://ott-cdn.ucom.am/s6/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/072.png', 'title': '\xd4\xb1\xd6\x80\xd5\xa1\xd6\x80\xd5\xa1\xd5\xbf'},
{'url': 'ucom:http://ott-cdn.ucom.am/s7/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/073.png', 'title': '\xd4\xb5\xd6\x80\xd5\xaf\xd5\xab\xd6\x80 \xd5\x84\xd5\xa5\xd5\xa4\xd5\xab\xd5\xa1'},
{'url': 'ucom:http://ott-cdn.ucom.am/s8/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/074.png', 'title': 'ATV'},
{'url': 'ucom:http://ott-cdn.ucom.am/s5/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/075.png', 'title': '\xd4\xbf\xd5\xa5\xd5\xb6\xd5\xbf\xd6\x80\xd5\xb8\xd5\xb6'},
{'url': 'ucom:http://ott-cdn.ucom.am/s10/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/076.png', 'title': '21TV'},
{'url': 'ucom:http://ott-cdn.ucom.am/s68/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/085.png', 'title': '\xd0\xa2\xd0\xb5\xd1\x85\xd0\xbd\xd0\xbe 24'},
{'url': 'ucom:http://ott-cdn.ucom.am/s92/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/086.png', 'title': 'zoo tv'},
{'url': 'ucom:http://ott-cdn.ucom.am/s91/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/091.png', 'title': 'Viasat Action'},
{'url': 'ucom:http://ott-cdn.ucom.am/s67/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/092.png', 'title': 'Viasat Nature'},
{'url': 'ucom:http://ott-cdn.ucom.am/s34/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/094.png', 'title': 'Bridge TV'},
{'url': 'ucom:http://ott-cdn.ucom.am/s39/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/096.png', 'title': 'Mir'},
{'url': 'ucom:http://ott-cdn.ucom.am/s52/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/098.png', 'title': '\xd0\x91\xd0\xb5\xd1\x81\xd1\x82\xd1\x81\xd0\xb5\xd0\xbb\xd0\xbb\xd0\xb5\xd1\x80 +'},
{'url': 'ucom:http://ott-cdn.ucom.am/s43/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/108.png', 'title': '\xd0\xa8\xd0\xb0\xd0\xbd\xd1\x81\xd0\xbe\xd0\xbd \xd0\xa2\xd0\x92'},
{'url': 'ucom:http://ott-cdn.ucom.am/s57/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/110.png', 'title': '\xd0\xa0\xd1\x8b\xd0\xb6\xd0\xb8\xd0\xb9'},
{'url': 'ucom:http://ott-cdn.ucom.am/s82/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/112.png', 'title': 'Setanta Sports Plus HD'},
{'url': 'ucom:http://ott-cdn.ucom.am/s87/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/113.png', 'title': '\xd0\x9d\xd0\xa1\xd0\xa2'},
{'url': 'ucom:http://wpc.35916.upsiloncdn.net/8035916/ucomstreams/s12/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/115.png', 'title': '\xd5\x803'},
{'url': 'ucom:http://wpc.35916.upsiloncdn.net/8035916/ucomstreams/s13/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/116.png', 'title': '\xd5\x87\xd5\xb8\xd5\xb2\xd5\xa1\xd5\xaf\xd5\xa1\xd5\xa9'},
{'url': 'ucom:http://ott-cdn.ucom.am/s11/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/117.png', 'title': '\xd4\xb1\xd6\x80\xd5\xb4\xd5\x86\xd5\xb5\xd5\xb8\xd6\x82\xd5\xa6'},
{'url': 'ucom:http://ott-cdn.ucom.am/s65/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/119.png', 'title': 'Bloomberg'},
{'url': 'ucom:http://ott-cdn.ucom.am/s81/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/122.png', 'title': 'Setanta Sports HD'},
{'url': 'ucom:http://ott-cdn.ucom.am/s58/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/140.png', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82'},
{'url': 'ucom:http://ott-cdn.ucom.am/s69/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/144.png', 'title': 'Al Jazeera Arabic'},
{'url': 'ucom:http://ott-cdn.ucom.am/s48/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/295.png', 'title': '\xd5\x96\xd5\xab\xd5\xac\xd5\xb4\xd5\xa6\xd5\xb8\xd5\xb6'},
{'url': 'ucom:http://ott-cdn.ucom.am/s74/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/296.png', 'title': '\xd4\xbd\xd5\xa1\xd5\xb2\xd4\xb1\xd5\xac\xd5\xab\xd6\x84'},
{'url': 'ucom:http://ott-cdn.ucom.am/s53/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/297.png', 'title': '\xd4\xb9\xd5\xa1\xd5\xbe\xd5\xa1 TV'},
{'url': 'ucom:http://ott-cdn.ucom.am/s73/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/298.png', 'title': '\xd5\x80\xd5\xa1\xd5\xb5 TV'},
{'url': 'ucom:http://ott-cdn.ucom.am/s94/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/299.png', 'title': '\xd4\xbf\xd5\xab\xd5\xb6\xd5\xb8\xd5\xb4\xd5\xa1\xd5\xb6'},
{'url': 'ucom:http://ott-cdn.ucom.am/s66/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/300.png', 'title': 'Cineman'},
{'url': 'ucom:http://ott-cdn.ucom.am/s46/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/301.png', 'title': 'Tun-tunik'},
{'url': 'ucom:http://ott-cdn.ucom.am/s32/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/302.png', 'title': 'Comedy'},
{'url': 'ucom:http://ott-cdn.ucom.am/s42/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/303.png', 'title': 'Jan TV'},
{'url': 'ucom:http://ott-cdn.ucom.am/s22/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/304.png', 'title': 'Armcinema'},
{'url': 'ucom:http://ott-cdn.ucom.am/s83/index.m3u8', 'group': '', 'img': 'https://mobapp-t5.ucom.am/static/channelicon/305.png', 'title': 'Armenia Premium '},
]
udata=1569576567.56