[
{'url': 'telehub:nash-detektiv', 'group': '', 'img': 'http://telehub.org/images/nash-detektiv.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88 \xd0\x94\xd0\xb5\xd1\x82\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2'},
{'url': 'telehub:kinopremium-hd', 'group': '', 'img': 'http://telehub.org/images/kinopremium-hd.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\x9f\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb8\xd1\x83\xd0\xbc HD'},
{'url': 'telehub:morskoj', 'group': '', 'img': 'http://telehub.org/images/morskoj.png', 'title': '\xd0\xbc\xd0\xbe\xd1\x80\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9'},
{'url': 'telehub:galaxy-tv', 'group': '', 'img': 'http://telehub.org/images/galaxy.png', 'title': 'Galaxy TV'},
{'url': 'telehub:tnt4', 'group': '', 'img': 'http://telehub.org/images/tnt4.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa24'},
{'url': 'telehub:tnt', 'group': '', 'img': 'http://telehub.org/images/tnt.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2'},
{'url': 'telehub:sts', 'group': '', 'img': 'http://telehub.org/images/sts.png', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1'},
{'url': 'telehub:novyj-kanal', 'group': '', 'img': 'http://telehub.org/images/noviy.png', 'title': '\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'telehub:setanta-sports-ukraine', 'group': '', 'img': 'http://telehub.org/images/setanta-sports-ukraine.png', 'title': 'Setanta Sports Ukraine'},
{'url': 'telehub:nickelodeon', 'group': '', 'img': 'http://telehub.org/images/nick.png', 'title': 'Nickelodeon'},
{'url': 'telehub:stb', 'group': '', 'img': 'http://telehub.org/images/stb.png', 'title': '\xd0\xa1\xd0\xa2\xd0\x91'},
{'url': 'telehub:rossiya-1', 'group': '', 'img': 'http://telehub.org/images/russia_1.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 1'},
{'url': 'telehub:eurosport-2', 'group': '', 'img': 'http://telehub.org/images/eurosport_2.png', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 2'},
{'url': 'telehub:amedia-hit', 'group': '', 'img': 'http://telehub.org/images/amedia-hit.png', 'title': 'Amedia Hit'},
{'url': 'telehub:tnt-music', 'group': '', 'img': 'http://telehub.org/images/tnt-music.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2 Music'},
{'url': 'telehub:mnogo-tv', 'group': '', 'img': 'http://telehub.org/images/mnogotv.png', 'title': '\xd0\x9c\xd0\xbd\xd0\xbe\xd0\xb3\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'telehub:365-dnej', 'group': '', 'img': 'http://telehub.org/images/365dney.png', 'title': '365 \xd0\x94\xd0\xbd\xd0\xb5\xd0\xb9'},
{'url': 'telehub:amc', 'group': '', 'img': 'http://telehub.org/images/amc.png', 'title': 'AMC'},
{'url': 'telehub:mega', 'group': '', 'img': 'http://telehub.org/images/mega.png', 'title': '\xd0\x9c\xd0\xb5\xd0\xb3\xd0\xb0'},
{'url': 'telehub:tet', 'group': '', 'img': 'http://telehub.org/images/tet.png', 'title': '\xd0\xa2\xd0\x95\xd0\xa2'},
{'url': 'telehub:viasat-history', 'group': '', 'img': 'http://telehub.org/images/viasat_his.png', 'title': 'Viasat History'},
{'url': 'telehub:viasat-explorer', 'group': '', 'img': 'http://telehub.org/images/viasat_ex.png', 'title': 'Viasat Explorer'},
{'url': 'telehub:viasat-nature', 'group': '', 'img': 'http://telehub.org/images/viasat_nat.png', 'title': 'Viasat Nature'},
{'url': 'telehub:nlo-tv', 'group': '', 'img': 'http://telehub.org/images/nlo_tv.png', 'title': '\xd0\x9d\xd0\x9b\xd0\x9e \xd0\xa2\xd0\x92'},
{'url': 'telehub:futbol-1-ukraina', 'group': '', 'img': 'http://telehub.org/images/football_1.png', 'title': '\xd1\x84\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 1'},
{'url': 'telehub:ren', 'group': '', 'img': 'http://telehub.org/images/ren_tv.png', 'title': '\xd0\xa0\xd0\x95\xd0\x9d \xd0\xa2\xd0\x92'},
{'url': 'telehub:pervyj-kanal', 'group': '', 'img': 'http://telehub.org/images/pervij.png', 'title': '\xd0\xbf\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9'},
{'url': 'telehub:bt-sport-espn', 'group': '', 'img': 'http://telehub.org/images/bt-sport-espn.png', 'title': 'BT Sport ESPN'},
{'url': 'telehub:superkanal', 'group': '', 'img': 'http://telehub.org/images/superkanal.png', 'title': '\xd0\xa1\xd1\x83\xd0\xbf\xd0\xb5\xd1\x80 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'telehub:pyatyj-kanal', 'group': '', 'img': 'http://telehub.org/images/5kanal.png', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'telehub:multimaniya', 'group': '', 'img': 'http://telehub.org/images/multiman.png', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd0\xb8\xd0\xbc\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f'},
{'url': 'telehub:nat-geo-wild', 'group': '', 'img': 'http://telehub.org/images/natgeowild.png', 'title': 'Nat Geo Wild'},
{'url': 'telehub:ru-tv', 'group': '', 'img': 'http://telehub.org/images/rutv.png', 'title': 'RU TV'},
{'url': 'telehub:kino-tv', 'group': '', 'img': 'http://telehub.org/images/kinotv.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'telehub:nst', 'group': '', 'img': 'http://telehub.org/images/nsttv.png', 'title': '\xd0\x9d\xd0\xa1\xd0\xa2'},
{'url': 'telehub:tv-xxi', 'group': '', 'img': 'http://telehub.org/images/TV_XXI.png', 'title': 'TV 21'},
{'url': 'telehub:oruzhie', 'group': '', 'img': 'http://telehub.org/images/oruzhie.png', 'title': '\xd0\x9e\xd1\x80\xd1\x83\xd0\xb6\xd0\xb8\xd0\xb5'},
{'url': 'telehub:1-plus-1', 'group': '', 'img': 'http://telehub.org/images/1_1.png', 'title': '1+1'},
{'url': 'telehub:ictv', 'group': '', 'img': 'http://telehub.org/images/ICTV.png', 'title': 'ICTV'},
{'url': 'telehub:ntv', 'group': '', 'img': 'http://telehub.org/images/ntv.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x92'},
{'url': 'telehub:domashnij', 'group': '', 'img': 'http://telehub.org/images/domash.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc\xd0\xb0\xd1\x88\xd0\xbd\xd0\xb8\xd0\xb9'},
{'url': 'telehub:24-tekhno', 'group': '', 'img': 'http://telehub.org/images/24texno.png', 'title': '24 \xd1\x82\xd0\xb5\xd1\x85\xd0\xbd\xd0\xbe'},
{'url': 'telehub:trk-ukraina', 'group': '', 'img': 'http://telehub.org/images/trk_ukr.png', 'title': '\xd0\xa2\xd0\xa0\xd0\x9a \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'telehub:disney', 'group': '', 'img': 'http://telehub.org/images/Disney.png', 'title': 'disney'},
{'url': 'telehub:inter', 'group': '', 'img': 'http://telehub.org/images/inter.png', 'title': '\xd0\x98\xd0\xbd\xd1\x82\xd0\xb5\xd1\x80'},
{'url': 'telehub:muz-tv', 'group': '', 'img': 'http://telehub.org/images/muz_tv.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb7-\xd0\xa2\xd0\x92'},
{'url': 'telehub:otr', 'group': '', 'img': 'http://telehub.org/images/otr.png', 'title': '\xd0\x9e\xd0\xa2\xd0\xa0'},
{'url': 'telehub:russkaya-komediya', 'group': '', 'img': 'http://telehub.org/images/russkaya-komediya.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd0\xba\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f'},
{'url': 'telehub:mult', 'group': '', 'img': 'http://telehub.org/images/mult.png', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82'},
{'url': 'telehub:spike', 'group': '', 'img': 'http://telehub.org/images/spike.png', 'title': 'Spike'},
{'url': 'telehub:sts-love', 'group': '', 'img': 'http://telehub.org/images/sts_love.png', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1 Love'},
{'url': 'telehub:otse', 'group': '', 'img': 'http://telehub.org/images/otse.png', 'title': '\xd0\x9e\xd0\xa6\xd0\x95'},
{'url': 'telehub:2x2', 'group': '', 'img': 'http://telehub.org/images/2x2.png', 'title': '2\xd1\x852'},
{'url': 'telehub:kanal-che', 'group': '', 'img': 'http://telehub.org/images/kanal_che.png', 'title': '\xd1\x87\xd0\xb5'},
{'url': 'telehub:1hd', 'group': '', 'img': 'http://telehub.org/images/1hd.png', 'title': '1HD'},
{'url': 'telehub:komediya-tv', 'group': '', 'img': 'http://telehub.org/images/kamedia.png', 'title': '\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f \xd0\xa2\xd0\x92'},
{'url': 'telehub:2-plus-2', 'group': '', 'img': 'http://telehub.org/images/2plus2.png', 'title': '2+2'},
{'url': 'telehub:football-2', 'group': '', 'img': 'http://telehub.org/images/football_2.png', 'title': '\xd1\x84\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 2'},
{'url': 'telehub:illyuzion-plus', 'group': '', 'img': 'http://telehub.org/images/illyuzion.png', 'title': '\xd0\xb8\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd \xd0\xbf\xd0\xbb\xd1\x8e\xd1\x81'},
{'url': 'telehub:ntn', 'group': '', 'img': 'http://telehub.org/images/ntn.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x9d'},
{'url': 'telehub:istoriya', 'group': '', 'img': 'http://telehub.org/images/istoria.png', 'title': '\xd0\x98\xd1\x81\xd1\x82\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f'},
{'url': 'telehub:history-channel', 'group': '', 'img': 'http://telehub.org/images/history.png', 'title': 'History'},
{'url': 'telehub:rossiya-24', 'group': '', 'img': 'http://telehub.org/images/rossiya24.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 24'},
{'url': 'telehub:zee-tv', 'group': '', 'img': 'http://telehub.org/images/zee.png', 'title': 'zee tv'},
{'url': 'telehub:bober-tv', 'group': '', 'img': 'http://telehub.org/images/bober-tv.png', 'title': '\xd0\xb1\xd0\xbe\xd0\xb1\xd0\xb5\xd1\x80 \xd1\x82\xd0\xb2'},
{'url': 'telehub:national-geographic', 'group': '', 'img': 'http://telehub.org/images/natgeo.png', 'title': 'National Geographic'},
{'url': 'telehub:ryzhij', 'group': '', 'img': 'http://telehub.org/images/ryzhij.png', 'title': '\xd0\xa0\xd1\x8b\xd0\xb6\xd0\xb8\xd0\xb9'},
{'url': 'telehub:moya-planeta', 'group': '', 'img': 'http://telehub.org/images/my_planet.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x8f \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'telehub:karusel', 'group': '', 'img': 'http://telehub.org/images/karusel.png', 'title': '\xd0\x9a\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd0\xb5\xd0\xbb\xd1\x8c'},
{'url': 'telehub:zvezda', 'group': '', 'img': 'http://telehub.org/images/zvezda.png', 'title': '\xd0\x97\xd0\xb2\xd0\xb5\xd0\xb7\xd0\xb4\xd0\xb0'},
{'url': 'telehub:sovershenno-sekretno', 'group': '', 'img': 'http://telehub.org/images/sov_sec.png', 'title': '\xd0\xa1\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x80\xd1\x88\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xbe \xd1\x81\xd0\xb5\xd0\xba\xd1\x80\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe'},
{'url': 'telehub:k1', 'group': '', 'img': 'http://telehub.org/images/k1.png', 'title': '\xd0\x9a1'},
{'url': 'telehub:k2', 'group': '', 'img': 'http://telehub.org/images/k2.png', 'title': '\xd0\x9a2'},
{'url': 'telehub:112-kanal', 'group': '', 'img': 'http://telehub.org/images/112_kanal.png', 'title': '112'},
{'url': 'telehub:russkij-illyuzion', 'group': '', 'img': 'http://telehub.org/images/ruilluz.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\x98\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd'},
{'url': 'telehub:nauka-2', 'group': '', 'img': 'http://telehub.org/images/nauka-2.png', 'title': '\xd0\xbd\xd0\xb0\xd1\x83\xd0\xba\xd0\xb0 2.0'},
{'url': 'telehub:a1', 'group': '', 'img': 'http://telehub.org/images/a1.png', 'title': 'a1'},
{'url': 'telehub:a2', 'group': '', 'img': 'http://telehub.org/images/a2.png', 'title': 'a2'},
{'url': 'telehub:amedia-premium-hd', 'group': '', 'img': 'http://telehub.org/images/amedia_prem_hd.png', 'title': 'Amedia Premium HD'},
{'url': 'telehub:tvc', 'group': '', 'img': 'http://telehub.org/images/tvc.png', 'title': '\xd1\x82\xd0\xb2\xd1\x86'},
{'url': 'telehub:rtr-planeta', 'group': '', 'img': 'http://telehub.org/images/planet_rtr.png', 'title': '\xd0\xa0\xd0\xa2\xd0\xa0 \xd0\x9f\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'telehub:paramount-comedy', 'group': '', 'img': 'http://telehub.org/images/paramaund.png', 'title': 'Paramount Comedy'},
{'url': 'telehub:rbk', 'group': '', 'img': 'http://telehub.org/images/rbk.png', 'title': '\xd0\xa0\xd0\x91\xd0\x9a'},
{'url': 'telehub:tlum-hd', 'group': '', 'img': 'http://telehub.org/images/tlum-hd.png', 'title': '\xd0\xa2\xd0\xbb\xd1\x83\xd0\xbc HD'},
{'url': 'telehub:moskva-24', 'group': '', 'img': 'http://telehub.org/images/moskva_24.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0 24'},
{'url': 'telehub:russkij-bestseller', 'group': '', 'img': 'http://telehub.org/images/bestseller.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb1\xd0\xb5\xd1\x81\xd1\x82\xd1\x81\xd0\xb5\xd0\xbb\xd0\xbb\xd0\xb5\xd1\x80'},
{'url': 'telehub:russkij-roman', 'group': '', 'img': 'http://telehub.org/images/rusroman.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd'},
{'url': 'telehub:russkij-detektiv', 'group': '', 'img': 'http://telehub.org/images/rusdet.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb4\xd0\xb5\xd1\x82\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2'},
{'url': 'telehub:mtv-russia', 'group': '', 'img': 'http://telehub.org/images/mtvru.png', 'title': 'MTV \xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f'},
{'url': 'telehub:russian-music-box', 'group': '', 'img': 'http://telehub.org/images/rumusicbox.png', 'title': 'Russian Music Box'},
{'url': 'telehub:europa-plus-tv', 'group': '', 'img': 'http://telehub.org/images/europaplus.png', 'title': '\xd0\xb5\xd0\xb2\xd1\x80\xd0\xbe\xd0\xbf\xd0\xb0 \xd0\xbf\xd0\xbb\xd1\x8e\xd1\x81 \xd1\x82\xd0\xb2'},
{'url': 'telehub:bigudi', 'group': '', 'img': 'http://telehub.org/images/bigudi.png', 'title': '\xd0\x91\xd0\xb8\xd0\xb3\xd1\x83\xd0\xb4\xd0\xb8'},
{'url': 'telehub:detskij', 'group': '', 'img': 'http://telehub.org/images/detskii.png', 'title': '\xd0\xb4\xd0\xb5\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9'},
{'url': 'telehub:avto-24', 'group': '', 'img': 'http://telehub.org/images/auto24.png', 'title': '\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe 24'},
{'url': 'telehub:auto-plus', 'group': '', 'img': 'http://telehub.org/images/autoplus.png', 'title': '\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe \xd0\xbf\xd0\xbb\xd1\x8e\xd1\x81'},
{'url': 'telehub:lya-minor', 'group': '', 'img': 'http://telehub.org/images/laminor.png', 'title': '\xd0\x9b\xd1\x8f-\xd0\xbc\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x80'},
{'url': 'telehub:shanson-tv', 'group': '', 'img': 'http://telehub.org/images/shanson.png', 'title': '\xd0\xa8\xd0\xb0\xd0\xbd\xd1\x81\xd0\xbe\xd0\xbd \xd0\xa2\xd0\x92'},
{'url': 'telehub:mir', 'group': '', 'img': 'http://telehub.org/images/mir.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x80'},
{'url': 'telehub:mezzo', 'group': '', 'img': 'http://telehub.org/images/mezzo.png', 'title': 'Mezzo'},
{'url': 'telehub:dom-kino', 'group': '', 'img': 'http://telehub.org/images/domkino.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'telehub:xsport', 'group': '', 'img': 'http://telehub.org/images/xsport.png', 'title': 'XSport'},
{'url': 'telehub:malyatko-tv', 'group': '', 'img': 'http://telehub.org/images/malatko.png', 'title': '\xd0\x9c\xd0\xb0\xd0\xbb\xd1\x8f\xd1\x82\xd0\xba\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'telehub:bridge-tv', 'group': '', 'img': 'http://telehub.org/images/bridge.png', 'title': '\xd0\xb1\xd1\x80\xd0\xb8\xd0\xb4\xd0\xb6 \xd1\x82\xd0\xb2'},
{'url': 'telehub:muzhskoe-kino', 'group': '', 'img': 'http://telehub.org/images/muzkino.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'telehub:cnn', 'group': '', 'img': 'http://telehub.org/images/cnn.png', 'title': 'CNN'},
{'url': 'telehub:plus-plus', 'group': '', 'img': 'http://telehub.org/images/plusplus.png', 'title': '\xd0\x9f\xd0\xbb\xd1\x8e\xd1\x81\xd0\x9f\xd0\xbb\xd1\x8e\xd1\x81'},
{'url': 'telehub:russia-today', 'group': '', 'img': 'http://telehub.org/images/rustoday.png', 'title': 'Russia Today'},
{'url': 'telehub:kukhnya-tv', 'group': '', 'img': 'http://telehub.org/images/kuhnia.png', 'title': '\xd0\x9a\xd1\x83\xd1\x85\xd0\xbd\xd1\x8f \xd0\xa2\xd0\x92'},
{'url': 'telehub:muzhskoj', 'group': '', 'img': 'http://telehub.org/images/muzskoi.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9'},
{'url': 'telehub:8-kanal', 'group': '', 'img': 'http://telehub.org/images/8_kanal.png', 'title': '8 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'telehub:strashnoe-hd', 'group': '', 'img': 'http://telehub.org/images/strahd.png', 'title': '\xd0\xa1\xd1\x82\xd1\x80\xd0\xb0\xd1\x88\xd0\xbd\xd0\xbe\xd0\xb5 HD'},
{'url': 'telehub:kanal-you', 'group': '', 'img': 'http://telehub.org/images/yootv.png', 'title': '\xd1\x8e'},
{'url': 'telehub:kazsport', 'group': '', 'img': 'http://telehub.org/images/kazsport.png', 'title': '\xd0\x9a\xd0\x90\xd0\x97\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82'},
{'url': 'telehub:belarus-5', 'group': '', 'img': 'http://telehub.org/images/bel5.png', 'title': '\xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c 5'},
{'url': 'telehub:okhota-i-rybalka', 'group': '', 'img': 'http://telehub.org/images/ohrib.png', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xb0 \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xb0\xd0\xbb\xd0\xba\xd0\xb0'},
{'url': 'telehub:zik', 'group': '', 'img': 'http://telehub.org/images/zik.png', 'title': 'ZIK'},
{'url': 'telehub:drajv-tv', 'group': '', 'img': 'http://telehub.org/images/drajv-tv.png', 'title': '\xd0\xb4\xd1\x80\xd0\xb0\xd0\xb9\xd0\xb2 \xd1\x82\xd0\xb2'},
{'url': 'telehub:rossiya-kultura', 'group': '', 'img': 'http://telehub.org/images/rukultura.png', 'title': '\xd1\x80\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f \xd0\xba (\xd0\xba\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd1\x83\xd1\x80\xd0\xb0)'},
{'url': 'telehub:okhotnik-i-rybolov', 'group': '', 'img': 'http://telehub.org/images/ohotnik.png', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2'},
{'url': 'telehub:euronews', 'group': '', 'img': 'http://telehub.org/images/EuroNews.png', 'title': 'EuroNews'},
{'url': 'telehub:newsone', 'group': '', 'img': 'http://telehub.org/images/newsone.png', 'title': 'News One'},
{'url': 'telehub:24-ukraina', 'group': '', 'img': 'http://telehub.org/images/24_ukr.png', 'title': '24 \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'telehub:espreso-tv', 'group': '', 'img': 'http://telehub.org/images/espresotv.png', 'title': '\xd0\x95\xd1\x81\xd0\xbf\xd1\x80\xd0\xb5\xd1\x81\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'telehub:5-kanal-ukraina', 'group': '', 'img': 'http://telehub.org/images/5_ukr.png', 'title': '5 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'telehub:gromadske-tv', 'group': '', 'img': 'http://telehub.org/images/gromadske-tv.png', 'title': '\xd0\x93\xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xb4\xd1\x81\xd1\x8c\xd0\xba\xd0\xb5 \xd0\xa2\xd0\x92'},
{'url': 'telehub:ostrosyuzhetnoe-hd', 'group': '', 'img': 'http://telehub.org/images/ostrotv.png', 'title': '\xd0\x9e\xd1\x81\xd1\x82\xd1\x80\xd0\xbe\xd1\x81\xd1\x8e\xd0\xb6\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe\xd0\xb5 HD'},
{'url': 'telehub:nash-kinoroman', 'group': '', 'img': 'http://telehub.org/images/nash-kinoroman.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88 \xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd'},
{'url': 'telehub:evrokino', 'group': '', 'img': 'http://telehub.org/images/eukino.png', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'telehub:sport-1-ukraina', 'group': '', 'img': 'http://telehub.org/images/sport1ukr.png', 'title': '\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 1 \xd1\x83\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'telehub:sport-2-ukraina', 'group': '', 'img': 'http://telehub.org/images/sport2ukr.png', 'title': '\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 2 \xd1\x83\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'telehub:boks-tv', 'group': '', 'img': 'http://telehub.org/images/boxtv.png', 'title': '\xd0\x91\xd0\xbe\xd0\xba\xd1\x81 \xd0\xa2\xd0\x92'},
{'url': 'telehub:24-dok', 'group': '', 'img': 'http://telehub.org/images/24dok.png', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\x94\xd0\xbe\xd0\xba\xd1\x82\xd0\xbe\xd1\x80'},
{'url': 'telehub:indiya-tv', 'group': '', 'img': 'http://telehub.org/images/indiatv.png', 'title': '\xd0\x98\xd0\xbd\xd0\xb4\xd0\xb8\xd1\x8f \xd0\xa2\xd0\x92'},
{'url': 'telehub:nano-tv', 'group': '', 'img': 'http://telehub.org/images/nanotv.png', 'title': '\xd0\xbd\xd0\xb0\xd0\xbd\xd0\xbe \xd1\x82\xd0\xb2'},
{'url': 'telehub:feniks-kino', 'group': '', 'img': 'http://telehub.org/images/feniks.png', 'title': '\xd1\x84\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xba\xd1\x81 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'telehub:tiji', 'group': '', 'img': 'http://telehub.org/images/tiji.png', 'title': 'Tiji'},
{'url': 'telehub:gulli', 'group': '', 'img': 'http://telehub.org/images/gulli.png', 'title': 'gulli'},
{'url': 'telehub:radost-moya', 'group': '', 'img': 'http://telehub.org/images/radostmy.png', 'title': '\xd0\xa0\xd0\xb0\xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c \xd0\xbc\xd0\xbe\xd1\x8f'},
{'url': 'telehub:fine-living', 'group': '', 'img': 'http://telehub.org/images/fine-living.png', 'title': 'Fine Living'},
{'url': 'telehub:telekanal-futbol', 'group': '', 'img': 'http://telehub.org/images/telfut.png', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb'},
{'url': 'telehub:mgm', 'group': '', 'img': 'http://telehub.org/images/mgm.png', 'title': 'MGM'},
{'url': 'telehub:russkij-ekstrim', 'group': '', 'img': 'http://telehub.org/images/ruekstrim.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xad\xd0\xba\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd0\xbc'},
{'url': 'telehub:eda-tv', 'group': '', 'img': 'http://telehub.org/images/edatv.png', 'title': '\xd0\x95\xd0\xb4\xd0\xb0 \xd0\xa2\xd0\x92'},
{'url': 'telehub:setanta-sports', 'group': '', 'img': 'http://telehub.org/images/setanta.png', 'title': '\xd1\x81\xd0\xb5\xd1\x82\xd0\xb0\xd0\xbd\xd1\x82\xd0\xb0 \xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82'},
{'url': 'telehub:piksel', 'group': '', 'img': 'http://telehub.org/images/piksel.png', 'title': '\xd0\xbf\xd0\xb8\xd0\xba\xd1\x81\xd0\xb5\xd0\xbb\xd1\x8c'},
{'url': 'telehub:travel-channel', 'group': '', 'img': 'http://telehub.org/images/travel-channel.png', 'title': 'Travel Channel'},
{'url': 'telehub:m1', 'group': '', 'img': 'http://telehub.org/images/m1.png', 'title': '\xd0\x9c1'},
{'url': 'telehub:m2', 'group': '', 'img': 'http://telehub.org/images/m2.png', 'title': '\xd0\x9c2'},
{'url': 'telehub:hardlife-tv', 'group': '', 'img': 'http://telehub.org/images/hardlife-tv.png', 'title': 'HardLife TV'},
{'url': 'telehub:outdoor-channel', 'group': '', 'img': 'http://telehub.org/images/outdoor.png', 'title': 'Outdoor Channel'},
{'url': 'telehub:nick-jr', 'group': '', 'img': 'http://telehub.org/images/nickjr.png', 'title': 'Nick Jr'},
{'url': 'telehub:vh1', 'group': '', 'img': 'http://telehub.org/images/vh1.png', 'title': 'VH1'},
{'url': 'telehub:travel-and-adventure', 'group': '', 'img': 'http://telehub.org/images/travadv.png', 'title': 'travel and adventure'},
{'url': 'telehub:krym-1', 'group': '', 'img': 'http://telehub.org/images/krym1.png', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\x9a\xd1\x80\xd1\x8b\xd0\xbc\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9'},
{'url': 'telehub:setanta-sports-plus', 'group': '', 'img': 'http://telehub.org/images/setanta-sports-plus.png', 'title': 'Setanta Sports Plus'},
{'url': 'telehub:zhivi', 'group': '', 'img': 'http://telehub.org/images/zhivi.png', 'title': '\xd0\x96\xd0\xb8\xd0\xb2\xd0\xb8'},
{'url': 'telehub:bbc-news', 'group': '', 'img': 'http://telehub.org/images/bbcnews.png', 'title': 'BBC News'},
{'url': 'telehub:mama', 'group': '', 'img': 'http://telehub.org/images/mama.png', 'title': '\xd0\xbc\xd0\xb0\xd0\xbc\xd0\xb0'},
{'url': 'telehub:fox', 'group': '', 'img': 'http://telehub.org/images/fox.png', 'title': 'FOX'},
{'url': 'telehub:fox-life', 'group': '', 'img': 'http://telehub.org/images/foxlife.png', 'title': 'Fox Life'},
{'url': 'telehub:sony-sci-fi', 'group': '', 'img': 'http://telehub.org/images/sonyscifi.png', 'title': 'Sony Sci-Fi'},
{'url': 'telehub:sony-turbo', 'group': '', 'img': 'http://telehub.org/images/sony-turbo.png', 'title': 'Sony Turbo'},
{'url': 'telehub:set', 'group': '', 'img': 'http://telehub.org/images/set.png', 'title': 'SET'},
{'url': 'telehub:nostalgiya', 'group': '', 'img': 'http://telehub.org/images/nostalgiya.png', 'title': '\xd0\x9d\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xb3\xd0\xb8\xd1\x8f'},
{'url': 'telehub:kanal-strana', 'group': '', 'img': 'http://telehub.org/images/multimuz.png', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd0\xb8\xd0\xbc\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0'},
{'url': 'telehub:360-gradusov', 'group': '', 'img': 'http://telehub.org/images/360grad.png', 'title': '360 \xd0\xb3\xd1\x80\xd0\xb0\xd0\xb4\xd1\x83\xd1\x81\xd0\xbe\xd0\xb2'},
{'url': 'telehub:sarafan-tv', 'group': '', 'img': 'http://telehub.org/images/sarafan.png', 'title': '\xd1\x81\xd0\xb0\xd1\x80\xd0\xb0\xd1\x84\xd0\xb0\xd0\xbd \xd1\x82\xd0\xb2'},
{'url': 'telehub:tdk', 'group': '', 'img': 'http://telehub.org/images/tdk.png', 'title': '\xd0\xa2\xd0\x94\xd0\x9a'},
{'url': 'telehub:konnyj-mir', 'group': '', 'img': 'http://telehub.org/images/konnyj-mir.png', 'title': '\xd0\x9a\xd0\xbe\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\xbc\xd0\xb8\xd1\x80'},
{'url': 'telehub:yumor-tv', 'group': '', 'img': 'http://telehub.org/images/yumor.png', 'title': '\xd0\xae\xd0\xbc\xd0\xbe\xd1\x80 \xd0\xa2\xd0\x92'},
{'url': 'telehub:kinopokaz', 'group': '', 'img': 'http://telehub.org/images/kinopokaz.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbf\xd0\xbe\xd0\xba\xd0\xb0\xd0\xb7'},
{'url': 'telehub:krym-24', 'group': '', 'img': 'http://telehub.org/images/krym24.png', 'title': '\xd0\x9a\xd1\x80\xd1\x8b\xd0\xbc 24'},
{'url': 'telehub:krasnaya-liniya', 'group': '', 'img': 'http://telehub.org/images/krasnaya-liniya.png', 'title': '\xd0\x9a\xd1\x80\xd0\xb0\xd1\x81\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xbb\xd0\xb8\xd0\xbd\xd0\xb8\xd1\x8f'},
{'url': 'telehub:bollywood', 'group': '', 'img': 'http://telehub.org/images/bollywood.png', 'title': 'Bollywood'},
{'url': 'telehub:tochka-tv', 'group': '', 'img': 'http://telehub.org/images/tochkatv.png', 'title': '\xd0\xa2\xd0\xbe\xd1\x87\xd0\xba\xd0\xb0 \xd0\xa2\xd0\x92'},
{'url': 'telehub:extreme-sports', 'group': '', 'img': 'http://telehub.org/images/extreme-sports.png', 'title': 'Extreme Sports'},
{'url': 'telehub:kanal-o', 'group': '', 'img': 'http://telehub.org/images/kanal-o.png', 'title': '\xd0\xbe!'},
{'url': 'telehub:mir-seriala', 'group': '', 'img': 'http://telehub.org/images/mir-seriala.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x80 \xd1\x81\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb\xd0\xb0'},
{'url': 'telehub:paramount-channel', 'group': '', 'img': 'http://telehub.org/images/paramount-channel.png', 'title': 'Paramount Channel'},
{'url': 'telehub:vesti-fm', 'group': '', 'img': 'http://telehub.org/images/radio/radio-vesti-fm.png', 'title': '\xd0\x92\xd0\xb5\xd1\x81\xd1\x82\xd0\xb8 \xd0\xa4\xd0\x9c'},
{'url': 'telehub:kinopokaz-hd1', 'group': '', 'img': 'http://telehub.org/images/kinopokaz-hd1.png', 'title': '\xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbf\xd0\xbe\xd0\xba\xd0\xb0\xd0\xb7 hd1'},
{'url': 'telehub:kinopokaz-hd2', 'group': '', 'img': 'http://telehub.org/images/kinopokaz-hd2.png', 'title': '\xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbf\xd0\xbe\xd0\xba\xd0\xb0\xd0\xb7 hd2'},
{'url': 'telehub:world-fashion', 'group': '', 'img': 'http://telehub.org/images/world-fashion.png', 'title': 'World Fashion'},
{'url': 'telehub:viasat-hockey', 'group': '', 'img': 'http://telehub.org/images/viasat-hockey.png', 'title': 'Viasat Hockey'},
{'url': 'telehub:sila-tv', 'group': '', 'img': 'http://telehub.org/images/silatv.png', 'title': '\xd0\xa1\xd0\x98\xd0\x9b\xd0\x90 \xd0\xa2\xd0\x92'},
{'url': 'telehub:lyubimoe-kino', 'group': '', 'img': 'http://telehub.org/images/lyubimoe-kino.png', 'title': '\xd0\x9b\xd1\x8e\xd0\xb1\xd0\xb8\xd0\xbc\xd0\xbe\xd0\xb5 \xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'telehub:hd-life', 'group': '', 'img': 'http://telehub.org/images/hd-life.png', 'title': 'HD Life'},
{'url': 'telehub:trofej', 'group': '', 'img': 'http://telehub.org/images/trofej.png', 'title': '\xd0\xa2\xd1\x80\xd0\xbe\xd1\x84\xd0\xb5\xd0\xb9'},
{'url': 'telehub:ekho-tv', 'group': '', 'img': 'http://telehub.org/images/ekho-tv.png', 'title': '\xd0\xad\xd1\x85\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'telehub:mir-24', 'group': '', 'img': 'http://telehub.org/images/mir-24.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x80 24'},
{'url': 'telehub:ulybka-rebenka', 'group': '', 'img': 'http://telehub.org/images/ulybka-rebenka.png', 'title': '\xd0\xa3\xd0\xbb\xd1\x8b\xd0\xb1\xd0\xba\xd0\xb0 \xd1\x80\xd0\xb5\xd0\xb1\xd0\xb5\xd0\xbd\xd0\xba\xd0\xb0'},
{'url': 'telehub:ani', 'group': '', 'img': 'http://telehub.org/images/ani.png', 'title': 'Ani'},
{'url': 'telehub:jimjam', 'group': '', 'img': 'http://telehub.org/images/jimjam.png', 'title': 'JimJam'},
{'url': 'telehub:lale', 'group': '', 'img': 'http://telehub.org/images/lale.png', 'title': 'Lale'},
{'url': 'telehub:detskij-mir', 'group': '', 'img': 'http://telehub.org/images/detskij-mir.png', 'title': '\xd0\x94\xd0\xb5\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xbc\xd0\xb8\xd1\x80'},
{'url': 'telehub:bloomberg', 'group': '', 'img': 'http://telehub.org/images/bloomberg.png', 'title': 'Bloomberg'},
{'url': 'telehub:zoom', 'group': '', 'img': 'http://telehub.org/images/zoom.png', 'title': 'zoom'},
{'url': 'telehub:zagorodnaya-zhizn', 'group': '', 'img': 'http://telehub.org/images/zagorodnaya-zhizn.png', 'title': '\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb4\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xb6\xd0\xb8\xd0\xb7\xd0\xbd\xd1\x8c'},
{'url': 'telehub:zoo-tv', 'group': '', 'img': 'http://telehub.org/images/zoo-tv.png', 'title': '\xd0\x97\xd0\xbe\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'telehub:rtg', 'group': '', 'img': 'http://telehub.org/images/rtg.png', 'title': 'rtg'},
{'url': 'telehub:9-kanal-izrail', 'group': '', 'img': 'http://telehub.org/images/9-kanal-izrail.png', 'title': '9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\x98\xd0\xb7\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbb\xd1\x8c'},
{'url': 'telehub:dom-kino-premium', 'group': '', 'img': 'http://telehub.org/images/dom-kino-premium.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe \xd0\x9f\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb8\xd1\x83\xd0\xbc'},
{'url': 'telehub:ua-pervyj', 'group': '', 'img': 'http://telehub.org/images/uaper.png', 'title': 'UA \xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9'},
{'url': 'telehub:telekanal-pryamoj', 'group': '', 'img': 'http://telehub.org/images/pryamoj.png', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\x9f\xd1\x80\xd1\x8f\xd0\xbc\xd0\xbe\xd0\xb9'},
{'url': 'telehub:dange-tv', 'group': '', 'img': 'http://telehub.org/images/dange-tv.png', 'title': 'Dange TV'},
{'url': 'telehub:telenovella', 'group': '', 'img': 'http://telehub.org/images/telenovella.png', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb5\xd0\xbb\xd0\xbb\xd0\xb0'},
{'url': 'telehub:ntv-serial', 'group': '', 'img': 'http://telehub.org/images/ntv-serial.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 \xd0\xa1\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb'},
{'url': 'telehub:ntv-hit', 'group': '', 'img': 'http://telehub.org/images/ntv-hit.png', 'title': '\xd0\xbd\xd1\x82\xd0\xb2\xe2\x80\x91\xd1\x85\xd0\xb8\xd1\x82'},
{'url': 'telehub:ntv-mir', 'group': '', 'img': 'http://telehub.org/images/ntv-mir.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 \xd0\x9c\xd0\xb8\xd1\x80'},
{'url': 'telehub:malysh-tv', 'group': '', 'img': 'http://telehub.org/images/malysh.png', 'title': '\xd0\xbc\xd0\xb0\xd0\xbb\xd1\x8b\xd1\x88 \xd1\x82\xd0\xb2'},
{'url': 'telehub:sky-sports-premier-league', 'group': '', 'img': 'http://telehub.org/images/sky-sport-premier-league.png', 'title': 'Sky Sports Premier League'},
{'url': 'telehub:sky-sports-main-event', 'group': '', 'img': 'http://telehub.org/images/sky-sport-main-event.png', 'title': 'Sky Sports Main Event'},
{'url': 'telehub:bt-sport-1', 'group': '', 'img': 'http://telehub.org/images/bt-sport-1.png', 'title': 'BT Sport 1'},
{'url': 'telehub:bt-sport-2', 'group': '', 'img': 'http://telehub.org/images/bt-sport-2.png', 'title': 'BT Sport 2'},
{'url': 'telehub:bt-sport-3', 'group': '', 'img': 'http://telehub.org/images/bt-sport-3.png', 'title': 'BT Sport 3'},
{'url': 'telehub:arena-sport-1', 'group': '', 'img': 'http://telehub.org/images/arena-sport-1.png', 'title': 'Arena Sport 1'},
{'url': 'telehub:arena-sport-2', 'group': '', 'img': 'http://telehub.org/images/arena-sport-2.png', 'title': 'Arena Sport 2'},
{'url': 'telehub:arena-sport-3', 'group': '', 'img': 'http://telehub.org/images/arena-sport-3.png', 'title': 'Arena Sport 3'},
{'url': 'telehub:arena-sport-4', 'group': '', 'img': 'http://telehub.org/images/arena-sport-4.png', 'title': 'Arena Sport 4'},
{'url': 'telehub:arena-sport-5', 'group': '', 'img': 'http://telehub.org/images/arena-sport-5.png', 'title': 'Arena Sport 5'},
{'url': 'telehub:bein-sports-1', 'group': '', 'img': 'http://telehub.org/images/bein-sport-1.png', 'title': 'BeIN Sports 1'},
{'url': 'telehub:bein-sports-2', 'group': '', 'img': 'http://telehub.org/images/bein-sport-2.png', 'title': 'BeIN Sports 2'},
{'url': 'telehub:bein-sports-3', 'group': '', 'img': 'http://telehub.org/images/bein-sport-3.png', 'title': 'BeIN Sports 3'},
{'url': 'telehub:look-sport-tv', 'group': '', 'img': 'http://telehub.org/images/look-sport.png', 'title': 'Look Sport TV'},
{'url': 'telehub:canal-sport', 'group': '', 'img': 'http://telehub.org/images/canal-plus-sport.png', 'title': 'Canal+ Sport'},
{'url': 'telehub:sport-tv-1', 'group': '', 'img': 'http://telehub.org/images/sport-tv-1.png', 'title': 'Sport TV 1'},
{'url': 'telehub:sport-tv-2', 'group': '', 'img': 'http://telehub.org/images/sport-tv-2.png', 'title': 'Sport TV 2'},
{'url': 'telehub:sport-tv-3', 'group': '', 'img': 'http://telehub.org/images/sport-tv-3.png', 'title': 'Sport TV 3'},
{'url': 'telehub:sport-tv-4', 'group': '', 'img': 'http://telehub.org/images/sport-tv-4.png', 'title': 'Sport TV 4'},
{'url': 'telehub:sport-tv-5', 'group': '', 'img': 'http://telehub.org/images/sport-tv-5.png', 'title': 'Sport TV 5'},
{'url': 'telehub:sport-klub-1', 'group': '', 'img': 'http://telehub.org/images/sport-klub-1.png', 'title': 'Sport Klub 1'},
{'url': 'telehub:sport-klub-2', 'group': '', 'img': 'http://telehub.org/images/sport-klub-2.png', 'title': 'Sport Klub 2'},
{'url': 'telehub:sport-klub-3', 'group': '', 'img': 'http://telehub.org/images/sport-klub-3.png', 'title': 'Sport Klub 3'},
{'url': 'telehub:supersport-2', 'group': '', 'img': 'http://telehub.org/images/supersport-2.png', 'title': 'Supersport 2'},
{'url': 'telehub:supersport-3', 'group': '', 'img': 'http://telehub.org/images/supersport-3.png', 'title': 'Supersport 3'},
{'url': 'telehub:muzyka-pervogo', 'group': '', 'img': 'http://telehub.org/images/muzyka-pervogo.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0 \xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd0\xbe\xd0\xb3\xd0\xbe'},
{'url': 'telehub:zhara-tv', 'group': '', 'img': 'http://telehub.org/images/zhara.png', 'title': '\xd0\xb6\xd0\xb0\xd1\x80\xd0\xb0 \xd1\x82\xd0\xb2'},
{'url': 'telehub:enter-film', 'group': '', 'img': 'http://telehub.org/images/enter-film.png', 'title': 'Enter-\xd0\xa4\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xbc'},
{'url': 'telehub:pervyj-avtomobilnyj', 'group': '', 'img': 'http://telehub.org/images/pervyj-avtomobilnyj.png', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xb0\xd0\xb2\xd1\x82\xd0\xbe\xd0\xbc\xd0\xbe\xd0\xb1\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb9'},
{'url': 'telehub:sontse-tv', 'group': '', 'img': 'http://telehub.org/images/sontse.png', 'title': '\xd0\xa1\xd0\xbe\xd0\xbd\xd1\x86\xd0\xb5 \xd0\xa2\xd0\x92'},
{'url': 'telehub:100-news', 'group': '', 'img': 'http://telehub.org/images/100-news.png', 'title': '100% News'},
{'url': 'telehub:rzhd-tv', 'group': '', 'img': 'http://telehub.org/images/rzhd-tv.png', 'title': '\xd1\x80\xd0\xb6\xd0\xb4 \xd1\x82\xd0\xb2'},
{'url': 'telehub:ua-kultura', 'group': '', 'img': 'http://telehub.org/images/uakultura.png', 'title': 'UA \xd0\x9a\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd1\x83\xd1\x80\xd0\xb0'},
{'url': 'telehub:pervyj-delovoj', 'group': '', 'img': 'http://telehub.org/images/pervyj-delovoj.png', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xb4\xd0\xb5\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb9'},
{'url': 'telehub:nicktoons', 'group': '', 'img': 'http://telehub.org/images/nicktoons.png', 'title': 'NickToons'},
{'url': 'telehub:strah-hd', 'group': '', 'img': 'http://telehub.org/images/strah-hd.png', 'title': '\xd0\xa1\xd1\x82\xd1\x80\xd0\xb0\xd1\x85 HD'},
{'url': 'telehub:usadba', 'group': '', 'img': 'http://telehub.org/images/usadba.png', 'title': '\xd0\xa3\xd1\x81\xd0\xb0\xd0\xb4\xd1\x8c\xd0\xb1\xd0\xb0 \xd0\xa2\xd0\x92'},
{'url': 'telehub:kuban-24', 'group': '', 'img': 'http://telehub.org/images/kuban-24.png', 'title': '\xd0\x9a\xd1\x83\xd0\xb1\xd0\xb0\xd0\xbd\xd1\x8c 24'},
{'url': 'telehub:fashion-tv', 'group': '', 'img': 'http://telehub.org/images/fashion-tv.png', 'title': 'Fashion TV'},
{'url': 'telehub:retro-tv', 'group': '', 'img': 'http://telehub.org/images/retro.png', 'title': '\xd0\xa0\xd0\xb5\xd1\x82\xd1\x80\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'telehub:super-tennis-hd', 'group': '', 'img': 'http://telehub.org/images/super-tennis-hd.png', 'title': 'Super Tennis HD'},
{'url': 'telehub:tonus-tv', 'group': '', 'img': 'http://telehub.org/images/tonus.png', 'title': '\xd0\xa2\xd0\xbe\xd0\xbd\xd1\x83\xd1\x81 \xd0\xa2\xd0\x92'},
{'url': 'telehub:eurosport-gold', 'group': '', 'img': 'http://telehub.org/images/eurosport-gold.png', 'title': 'Eurosport Gold'},
{'url': 'telehub:filmbox-arthouse', 'group': '', 'img': 'http://telehub.org/images/filmbox-arthouse.png', 'title': 'FilmBox Arthouse'},
{'url': 'telehub:nashe-lyubimoe-hd', 'group': '', 'img': 'http://telehub.org/images/nashe-lyubimoe-hd.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88\xd0\xb5 \xd0\x9b\xd1\x8e\xd0\xb1\xd0\xb8\xd0\xbc\xd0\xbe\xd0\xb5 HD'},
{'url': 'telehub:pyatnitsa-tv', 'group': '', 'img': 'http://telehub.org/images/pyatnitsa.png', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd0\xbd\xd0\xb8\xd1\x86\xd0\xb0'},
{'url': 'telehub:english-club-tv', 'group': '', 'img': 'http://telehub.org/images/eng_tv.png', 'title': 'English Club TV'},
]
udata=1591794824.64