[
{'url': 'mediabay:393', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/Uz24.120.png', 'title': 'Ozbekiston 24'},
{'url': 'mediabay:395', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/z2.120.png', 'title': 'ZorTV '},
{'url': 'mediabay:491', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/mediabay1235.120.png', 'title': 'Mediabay TV'},
{'url': 'mediabay:425', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/06-2018/254px-France24.120.png', 'title': 'France 24 '},
{'url': 'mediabay:495', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/J.120.png', 'title': '\xd0\xa2\xd0\xb0\xd0\xb4\xd0\xb6\xd0\xb8\xd0\xba\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd0\x9c\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0'},
{'url': 'mediabay:138', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/7TdAVsportuz.120.png', 'title': 'Sport - UZ'},
{'url': 'mediabay:499', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/uzbekmusic.120.png', 'title': '\xd0\xa3\xd0\xb7\xd0\xb1\xd0\xb5\xd0\xba\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd0\xbc\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0'},
{'url': 'mediabay:405', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/belorussiya.120.png', 'title': '\xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c 24'},
{'url': 'mediabay:493', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/kaleydoskop_3.120.png', 'title': '\xd0\xba\xd0\xb0\xd0\xbb\xd0\xb5\xd0\xb9\xd0\xb4\xd0\xbe\xd1\x81\xd0\xba\xd0\xbe\xd0\xbf \xd1\x82\xd0\xb2'},
{'url': 'mediabay:406', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/varzish-l.120.png', 'title': 'Varzish - TJ'},
{'url': 'mediabay:507', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/diyar-tv.120.png', 'title': 'Diyar TV'},
{'url': 'mediabay:519', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/ebccccc.120.png', 'title': 'EBC1'},
{'url': 'mediabay:544', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/TJFILM.jpg', 'title': '\xd0\xa2\xd0\xb0\xd0\xb4\xd0\xb6\xd0\xb8\xd0\xba\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5 \xd1\x84\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xbc\xd1\x8b (\xd1\x82\xd0\xb5\xd1\x81\xd1\x82)'},
{'url': 'mediabay:545', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/kaz.jpg', 'title': '\xd0\x9a\xd0\xb0\xd0\xb7\xd0\xb0\xd1\x85\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5 \xd1\x84\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xbc\xd1\x8b (\xd1\x82\xd0\xb5\xd1\x81\xd1\x82)'},
{'url': 'mediabay:505', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/01-2019/8kanalua.120.png', 'title': '8 \xd0\x9a\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'mediabay:140', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/FCOf712.120.png', 'title': 'Ozbekiston '},
{'url': 'mediabay:396', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/sevimli.120.png', 'title': 'Sevimli '},
{'url': 'mediabay:414', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/8kr.120.png', 'title': '8 \xd0\x9a\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\x9a\xd1\x80\xd0\xb0\xd1\x81\xd0\xbd\xd0\xbe\xd1\x8f\xd1\x80\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xba\xd1\x80\xd0\xb0\xd0\xb9- RU'},
{'url': 'mediabay:391', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/milliylogo.120.png', 'title': 'MilliyTV '},
{'url': 'mediabay:521', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/nowwww.120.png', 'title': 'NOW'},
{'url': 'mediabay:112', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/TV-channels_0017_tochikiston.120.png', 'title': 'TVT 1 - TJ'},
{'url': 'mediabay:583', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/10-2019/FUTBOLHDTAD.120.png', 'title': '\xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb HD'},
{'url': 'mediabay:116', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/kpaB4logo.120.png', 'title': 'Kazakh TV - KZ'},
{'url': 'mediabay:467', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/10-2018/nt.120.png', 'title': '\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb5 \xd1\x82\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xb2\xd0\xb8\xd0\xb4\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5'},
{'url': 'mediabay:508', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/azontv11.120.png', 'title': 'AzonTV'},
{'url': 'mediabay:407', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/11-2017/atameken.120.png', 'title': '\xd0\x90\xd1\x82\xd0\xb0\xd0\xbc\xd0\xb5\xd0\xba\xd0\xb5\xd0\xbd'},
{'url': 'mediabay:559', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/06-2019/KTRK.120.png', 'title': '\xd0\x9a\xd0\xa2\xd0\xa0\xd0\x9a '},
{'url': 'mediabay:560', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/06-2019/KTRK-Musika.120.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0 '},
{'url': 'mediabay:561', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/06-2019/KTRT-Madaniyat.120.png', 'title': '\xd0\x9c\xd0\xb0\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f\xd1\x82 '},
{'url': 'mediabay:563', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/06-2019/KTRK-Ala-too.120.png', 'title': '\xd0\x90\xd0\xbb\xd0\xb0-\xd1\x82\xd0\xbe\xd0\xbe '},
{'url': 'mediabay:564', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/06-2019/KTRK-Balastan.120.png', 'title': '\xd0\x91\xd0\xb0\xd0\xbb\xd0\xb0\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd '},
{'url': 'mediabay:86', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/FKz7Razadazerbaycantvmb.120.png', 'title': 'atv'},
{'url': 'mediabay:571', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/arb.120.png', 'title': 'ARB'},
{'url': 'mediabay:572', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/08-2019/arb-24.120.png', 'title': 'ARB 24'},
{'url': 'mediabay:114', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/E2jJuAztvmb.120.png', 'title': 'AzTV - AZ'},
{'url': 'mediabay:90', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/ictimai.jpg', 'title': 'Ictimai TV'},
{'url': 'mediabay:98', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/aGaA6medeniyyettvmb.120.png', 'title': 'Medeniyyet - AZ'},
{'url': 'mediabay:480', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/1diloviy.120.png', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd1\x88\xd0\xb8\xd0\xb9 \xd0\x94\xd1\x96\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb8\xd0\xb9 \xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'mediabay:520', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/icc.120.png', 'title': 'ICC '},
{'url': 'mediabay:96', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/U9llrlidertvmb.120.png', 'title': 'Lider TV - AZ'},
{'url': 'mediabay:104', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/BSv97xezertvazmb.120.png', 'title': 'Xezer - AZ'},
{'url': 'mediabay:593', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/11-2019/mtv-az.120.png', 'title': 'MTV Azerbaijan'},
{'url': 'mediabay:154', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/TcR96cbc.120.png', 'title': 'CBC (Caspian Broadcasting Company) - AZ'},
{'url': 'mediabay:420', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/06-2018/nrbtv.120.png', 'title': 'NRBTV'},
{'url': 'mediabay:134', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/YoshlAR.120.png', 'title': 'Yoshlar - UZ'},
{'url': 'mediabay:136', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/iTUCW2.120.png', 'title': 'Toshkent - UZ'},
{'url': 'mediabay:451', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/A2i-t.120.png', 'title': 'A2itv'},
{'url': 'mediabay:452', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/a2i-r.120.png', 'title': 'A2i Religion'},
{'url': 'mediabay:453', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/a2i-music.120.png', 'title': 'A2i Music'},
{'url': 'mediabay:392', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/oilaviy.120.png', 'title': 'Oilaviy'},
{'url': 'mediabay:426', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/ARABIC.120.png', 'title': 'France 24  Arabic'},
{'url': 'mediabay:428', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/France24-Eng.120.png', 'title': 'France 24  English'},
{'url': 'mediabay:427', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/franceesp.120.png', 'title': 'France 24  Espanol'},
{'url': 'mediabay:397', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/logosinamo11494510073.120.png', 'title': '\xd0\xa1\xd0\xb8\xd0\xbd\xd0\xb0\xd0\xbc\xd0\xbe - TJ'},
{'url': 'mediabay:106', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/Jf5xPjahonnamomb.120.png', 'title': 'Jahonnamo - TJ'},
{'url': 'mediabay:108', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/tvbakhoriston.120.png', 'title': 'Bakhoristan - TJ'},
{'url': 'mediabay:110', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/hfzKVtvsafinamb.120.png', 'title': 'Safina - TJ'},
{'url': 'mediabay:144', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/GFX6X40.120.png', 'title': 'Dunyo Boylab - UZ'},
{'url': 'mediabay:484', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/bolshabolshayaziya.120.png', 'title': '\xd0\x91\xd0\xbe\xd0\xbb\xd1\x8c\xd1\x88\xd0\xb0\xd1\x8f \xd0\x90\xd0\xb7\xd0\xb8\xd1\x8f'},
{'url': 'mediabay:487', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/12-2018/NTM.jpg', 'title': '\xd0\x9d\xd0\xa2\xd0\x9c'},
{'url': 'mediabay:492', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/12-2018/prob.120.png', 'title': '\xd0\x9f\xd0\xa0\xd0\x9e \xd0\x91\xd0\x98\xd0\x97\xd0\x9d\xd0\x95\xd0\xa1'},
{'url': 'mediabay:240', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/QiPbm1eS0O35.120.png', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 - RU - TEST'},
{'url': 'mediabay:34', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/RTDOCDOC.120.png', 'title': 'RT \xd0\xb4\xd0\xbe\xd0\xba\xd1\x83\xd0\xbc\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb9 '},
{'url': 'mediabay:343', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/8tv.120.png', 'title': '8 \xd0\xa2\xd0\x92 \xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0 - RU'},
{'url': 'mediabay:378', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/1HLzzplanetamb.120.png', 'title': '\xd0\xa0\xd0\xa2\xd0\xa0 - \xd0\x9f\xd0\x9b\xd0\x90\xd0\x9d\xd0\x95\xd0\xa2\xd0\x90 - RU - TEST'},
{'url': 'mediabay:234', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/ONGlJrus24mb.120.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 24 - RU - TEST'},
{'url': 'mediabay:408', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/rtarabic.120.png', 'title': 'RT Arabic'},
{'url': 'mediabay:382', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/IcwZmtmsport.120.png', 'title': 'T\xc3\xbcrkmenistan Sport - TM'},
{'url': 'mediabay:383', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/Fvd9DYASHLYK.120.png', 'title': 'Yaslyk - TM'},
{'url': 'mediabay:384', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/QQJXEmirasmb.120.png', 'title': 'Miras - TM'},
{'url': 'mediabay:385', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/XdeOZturkmenistan.120.png', 'title': 'T\xc3\xbcrkmenistan - TM'},
{'url': 'mediabay:386', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/ugcTZashgabadmb.120.png', 'title': 'Asgabat - TM'},
{'url': 'mediabay:387', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/XFl4eowazymb.120.png', 'title': 'T\xc3\xbcrkmen Owazy - TM'},
{'url': 'mediabay:256', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/uJ7ugTRTCOCUK.120.png', 'title': 'TRT - COCUK - TR'},
{'url': 'mediabay:258', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/SODiqTRTHABER1.120.png', 'title': 'TRT - HABER - TR'},
{'url': 'mediabay:283', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/tlcD8trtturk1.120.png', 'title': 'TRT T\xc3\xbcrk - TR'},
{'url': 'mediabay:585', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/10-2019/TRT-World.120.png', 'title': 'TRT World'},
{'url': 'mediabay:586', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/10-2019/TRT-AVAZ.120.png', 'title': 'TRT Avaz'},
{'url': 'mediabay:587', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/TRT-Arabi.120.png', 'title': 'TRT Arabic'},
{'url': 'mediabay:409', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/grozny-new.120.png', 'title': '\xd0\x93\xd1\x80\xd0\xbe\xd0\xb7\xd0\xbd\xd1\x8b\xd0\xb9'},
{'url': 'mediabay:546', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/05-2019/M24.120.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0 24'},
{'url': 'mediabay:591', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/11-2019/nano.120.png', 'title': '\xd0\xbd\xd0\xb0\xd0\xbd\xd0\xbe'},
{'url': 'mediabay:592', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/11-2019/luxury.120.png', 'title': 'luxury'},
{'url': 'mediabay:146', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/Dev2F39.120.png', 'title': 'Madaniyat va Marifat - UZ'},
{'url': 'mediabay:148', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/VUTumKOOV114.120.png', 'title': 'Bolajon - UZ'},
{'url': 'mediabay:465', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/min-idey.120.png', 'title': '\xd0\x9c\xd0\xb8\xd0\xbd\xd0\xb8\xd1\x81\xd1\x82\xd0\xb5\xd1\x80\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe \xd0\x98\xd0\xb4\xd0\xb5\xd0\xb9'},
{'url': 'mediabay:466', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/tulskiy1.120.png', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xa2\xd1\x83\xd0\xbb\xd1\x8c\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9'},
{'url': 'mediabay:473', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/10-2018/saratov24.120.png', 'title': '\xd0\xa1\xd0\xb0\xd1\x80\xd0\xb0\xd1\x82\xd0\xbe\xd0\xb2 24'},
{'url': 'mediabay:474', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/10-2018/rline.120.png', 'title': '\xd0\x9a\xd1\x80\xd0\xb0\xd1\x81\xd0\xbd\xd0\xb0\xd1\x8f \xd0\x9b\xd0\xb8\xd0\xbd\xd0\xb8\xd1\x8f'},
{'url': 'mediabay:476', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/11-2018/sinergiya.120.png', 'title': 'Synergy - TV'},
{'url': 'mediabay:489', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/12-2018/sever-tv.120.png', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xa1\xd0\xb5\xd0\xb2\xd0\xb5\xd1\x80'},
{'url': 'mediabay:496', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/12-2018/novosib.120.png', 'title': '8 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb. \xd0\x9d\xd0\xbe\xd0\xb2\xd0\xbe\xd1\x81\xd0\xb8\xd0\xb1\xd0\xb8\xd1\x80\xd1\x81\xd0\xba'},
{'url': 'mediabay:497', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/12-2018/vmeste-rf.120.png', 'title': '\xd0\x92\xd0\xbc\xd0\xb5\xd1\x81\xd1\x82\xd0\xb5 - \xd0\xa0\xd0\xa4'},
{'url': 'mediabay:502', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/gubern2.120.png', 'title': '\xd0\x93\xd1\x83\xd0\xb1\xd0\xb5\xd1\x80\xd0\xbd\xd0\xb8\xd1\x8f'},
{'url': 'mediabay:506', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/02-2019/belros.120.png', 'title': '\xd0\xb1\xd0\xb5\xd0\xbb\xd1\x80\xd0\xbe\xd1\x81'},
{'url': 'mediabay:418', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/05-2018/krasnodarTV.120.png', 'title': '\xd0\x9a\xd1\x80\xd0\xb0\xd1\x81\xd0\xbd\xd0\xbe\xd0\xb4\xd0\xb0\xd1\x80'},
{'url': 'mediabay:442', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/soyuz-b.120.png', 'title': '\xd0\xa1\xd0\xbe\xd1\x8e\xd0\xb7'},
{'url': 'mediabay:443', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/muzsoyuz-b.120.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb7\xd1\x81\xd0\xbe\xd1\x8e\xd0\xb7'},
{'url': 'mediabay:518', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/tochka-tv.120.png', 'title': '\xd0\xa2\xd0\xbe\xd1\x87\xd0\xba\xd0\xb0 \xd0\xa2\xd0\x92'},
{'url': 'mediabay:576', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/tolotv.120.png', 'title': 'TOLO (\xd1\x82\xd0\xb5\xd1\x81\xd1\x82)'},
{'url': 'mediabay:577', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/09-2019/ToloNews.120.png', 'title': 'TOLO News (\xd1\x82\xd0\xb5\xd1\x81\xd1\x82)'},
{'url': 'mediabay:578', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/09-2019/arianat.120.png', 'title': 'Ariana Television (\xd1\x82\xd0\xb5\xd1\x81\xd1\x82)'},
{'url': 'mediabay:588', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/11-2019/noor-tv.120.png', 'title': 'Noor TV'},
{'url': 'mediabay:590', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/11-2019/zhwandoon-tv.120.png', 'title': 'Zhwandoon TV'},
{'url': 'mediabay:478', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/11-2018/watan-af.120.png', 'title': 'Watan HD TV'},
{'url': 'mediabay:479', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/11-2018/tbn-baltia.120.png', 'title': 'TBN Baltia'},
{'url': 'mediabay:575', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/08-2019/iniyantv.120.png', 'title': 'Iniyan TV'},
{'url': 'mediabay:394', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/mahalla.120.png', 'title': 'Mahalla'},
{'url': 'mediabay:482', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/nadejda.120.png', 'title': 'Hope TV'},
{'url': 'mediabay:485', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/12-2018/ua.120.png', 'title': 'UA - TV HD'},
{'url': 'mediabay:490', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/12-2018/svarojichi.120.png', 'title': '\xd0\xa1\xd0\xb2\xd0\xb0\xd1\x80\xd0\xbe\xd0\xb6\xd0\xb8\xd1\x87\xd0\xb8'},
{'url': 'mediabay:254', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/YXT71Navo.120.png', 'title': 'Navo - UZ'},
{'url': 'mediabay:510', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/rumeli.jpg', 'title': 'Rumeli TV'},
{'url': 'mediabay:512', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/rtrtrtrtrtrtr.120.png', 'title': 'rt'},
{'url': 'mediabay:517', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/die.120.png', 'title': 'Die Neue Zeit '},
{'url': 'mediabay:528', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/rtdhd.120.png', 'title': 'RT Documentary'},
{'url': 'mediabay:529', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/espanolRT.120.png', 'title': 'RT Espa\xc3\xb1ol'},
{'url': 'mediabay:530', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/rt27-05.120.png', 'title': 'RT International'},
{'url': 'mediabay:531', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/americaRT.120.png', 'title': 'RT America'},
{'url': 'mediabay:532', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/ukRT.120.png', 'title': 'RT UK'},
{'url': 'mediabay:533', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/rtfranCEEEE.120.png', 'title': 'RT France'},
{'url': 'mediabay:542', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/TVMCHANNEL__.120.png', 'title': 'TVMChannel'},
{'url': 'mediabay:511', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/canalmotor.120.png', 'title': 'Canal Motor'},
{'url': 'mediabay:515', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/19-03-19.120.png', 'title': 'Sophia-TV'},
{'url': 'mediabay:534', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/04-2019/godasia.120.png', 'title': 'GOD Asia'},
{'url': 'mediabay:535', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/04-2019/godusa.120.png', 'title': 'GOD USA'},
{'url': 'mediabay:536', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/04-2019/goduk.120.png', 'title': 'GOD United Kingdom'},
{'url': 'mediabay:537', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/04-2019/godafrica.120.png', 'title': 'GOD Africa'},
{'url': 'mediabay:538', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/04-2019/godau.120.png', 'title': 'GOD Australia'},
{'url': 'mediabay:539', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/04-2019/godTV.120.png', 'title': 'GOD Event'},
{'url': 'mediabay:540', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/04-2019/godmusic.120.png', 'title': 'GOD Prayer'},
{'url': 'mediabay:569', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/arezotv.120.png', 'title': 'Arezo TV'},
{'url': 'mediabay:579', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/jigyasatv.120.png', 'title': 'Jigyasa TV'},
{'url': 'mediabay:541', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/Sonnnn_life.120.png', 'title': 'SONLife International Channel'},
{'url': 'mediabay:551', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/06-2019/imam1.120.png', 'title': 'Imam Hussein TV 1'},
{'url': 'mediabay:552', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/IMAM2.120.png', 'title': 'Imam Hussein TV 2'},
{'url': 'mediabay:553', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/06-2019/IMAM3.120.png', 'title': 'Imam Hussein TV 3'},
{'url': 'mediabay:554', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/06-2019/IMAM4.120.png', 'title': 'Imam Hussein TV 4'},
{'url': 'mediabay:555', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/al-zahratv.120.png', 'title': 'Al-Zahra TV'},
{'url': 'mediabay:584', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/10-2019/SBN2.120.png', 'title': 'SONLife Domestic'},
{'url': 'mediabay:573', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/08-2019/now-music.120.png', 'title': 'Now Music'},
{'url': 'mediabay:556', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/06-2019/novotempo.120.png', 'title': 'Novo Tempo'},
{'url': 'mediabay:557', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/06-2019/nuevo.120.png', 'title': 'Nuevo Tempo'},
{'url': 'mediabay:582', 'img': 'http://static.mediabay.com/www_data/newlogos/channels/09-2019/shifatv.120.png', 'title': 'Shifa TV'},
]
udata=1574832701.16