[
{'url': 'http://teledays.net/ren-tv.html', 'img': 'http://teledays.net/images/ren-tv.png', 'title': '\xd0\xa0\xd0\xb5\xd0\xbd \xd0\xa2\xd0\x92'},
{'url': 'http://teledays.net/tnt.html', 'img': 'http://teledays.net/images/tnt.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2'},
{'url': 'http://teledays.net/komediya.html', 'img': 'http://teledays.net/images/komediya.png', 'title': '\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f'},
{'url': 'http://teledays.net/che.html', 'img': 'http://teledays.net/images/chetv.png', 'title': '\xd0\xa7\xd0\xb5'},
{'url': 'http://teledays.net/pervyj-kanal.html', 'img': 'http://teledays.net/images/perviy_kanal.png', 'title': '\xd0\xbf\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9'},
{'url': 'http://teledays.net/russkij-roman.html', 'img': 'http://teledays.net/images/russkiy_roman.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd'},
{'url': 'http://teledays.net/morskoj.html', 'img': 'http://teledays.net/images/morskoj.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x80\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9'},
{'url': 'http://teledays.net/kanal-yu.html', 'img': 'http://teledays.net/images/yu-tv.png', 'title': '\xd1\x8e'},
{'url': 'http://teledays.net/kino-tv.html', 'img': 'http://teledays.net/images/kino_tv.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'http://teledays.net/nst.html', 'img': 'http://teledays.net/images/nst_tv.png', 'title': '\xd0\x9d\xd0\xa1\xd0\xa2'},
{'url': 'http://teledays.net/domashnij.html', 'img': 'http://teledays.net/images/domashniy_tv.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc\xd0\xb0\xd1\x88\xd0\xbd\xd0\xb8\xd0\xb9'},
{'url': 'http://teledays.net/nickelodeon.html', 'img': 'http://teledays.net/images/nickelodeon.png', 'title': 'Nickelodeon'},
{'url': 'http://teledays.net/1hd.html', 'img': 'http://teledays.net/images/1hd.png', 'title': '1HD'},
{'url': 'http://teledays.net/bober.html', 'img': 'http://teledays.net/images/bober.png', 'title': '\xd0\xb1\xd0\xbe\xd0\xb1\xd0\xb5\xd1\x80 \xd1\x82\xd0\xb2'},
{'url': 'http://teledays.net/ntv.html', 'img': 'http://teledays.net/images/ntv-tv.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x92'},
{'url': 'http://teledays.net/priklyucheniya-hd.html', 'img': 'http://teledays.net/images/priklyucheniya-hd.png', 'title': '\xd0\x9f\xd1\x80\xd0\xb8\xd0\xba\xd0\xbb\xd1\x8e\xd1\x87\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f HD'},
{'url': 'http://teledays.net/dom-kino.html', 'img': 'http://teledays.net/images/dom_kino.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://teledays.net/disney.html', 'img': 'http://teledays.net/images/disney-channel.png', 'title': 'disney'},
{'url': 'http://teledays.net/galaxy-tv.html', 'img': 'http://teledays.net/images/galaxy-tv.png', 'title': '\xd0\xa2\xd0\xb0\xd0\xb9\xd0\xbd\xd1\x8b \xd0\x93\xd0\xb0\xd0\xbb\xd0\xb0\xd0\xba\xd1\x82\xd0\xb8\xd0\xba\xd0\xb8'},
{'url': 'http://teledays.net/rossiya-1.html', 'img': 'http://teledays.net/images/russia-1.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 1'},
{'url': 'http://teledays.net/cinema.html', 'img': 'http://teledays.net/images/cinema.png', 'title': 'Cinema'},
{'url': 'http://teledays.net/ani.html', 'img': 'http://teledays.net/images/ani.png', 'title': 'Ani'},
{'url': 'http://teledays.net/europa-plus-tv.html', 'img': 'http://teledays.net/images/europa-plus-tv.png', 'title': 'Europa Plus TV'},
{'url': 'http://teledays.net/360-gradusov.html', 'img': 'http://teledays.net/images/360gr.png', 'title': '360 \xd0\xb3\xd1\x80\xd0\xb0\xd0\xb4\xd1\x83\xd1\x81\xd0\xbe\xd0\xb2'},
{'url': 'http://teledays.net/8-kanal.html', 'img': 'http://teledays.net/images/8-kanal.png', 'title': '8 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'http://teledays.net/2x2.html', 'img': 'http://teledays.net/images/2x2.png', 'title': '2\xd1\x852'},
{'url': 'http://teledays.net/lale.html', 'img': 'http://teledays.net/images/lale.png', 'title': 'Lale'},
{'url': 'http://teledays.net/bridge-tv.html', 'img': 'http://teledays.net/images/bridge-tv.png', 'title': 'Bridge TV'},
{'url': 'http://teledays.net/hdl.html', 'img': 'http://teledays.net/images/hdl.png', 'title': 'HDL'},
{'url': 'http://teledays.net/kinouzhas.html', 'img': 'http://teledays.net/images/kinouzhas.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x83\xd0\xb6\xd0\xb0\xd1\x81'},
{'url': 'http://teledays.net/hollywood.html', 'img': 'http://teledays.net/images/hollywood.png', 'title': 'Hollywood'},
{'url': 'http://teledays.net/m-1-global.html', 'img': 'http://teledays.net/images/m-1-global.png', 'title': 'M-1 Global'},
{'url': 'http://teledays.net/music-box-russia.html', 'img': 'http://teledays.net/images/music-box-russia.png', 'title': 'Music Box Russia'},
{'url': 'http://teledays.net/nano-tv.html', 'img': 'http://teledays.net/images/nano.png', 'title': '\xd0\xbd\xd0\xb0\xd0\xbd\xd0\xbe \xd1\x82\xd0\xb2'},
{'url': 'http://teledays.net/paramount-channel.html', 'img': 'http://teledays.net/images/paramount-channel.png', 'title': 'Paramount Channel'},
{'url': 'http://teledays.net/mtv-rossiya.html', 'img': 'http://teledays.net/images/mtv-rossiya.png', 'title': 'MTV \xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f'},
{'url': 'http://teledays.net/paramount-comedy.html', 'img': 'http://teledays.net/images/paramount-comedy.png', 'title': 'Paramount Comedy'},
{'url': 'http://teledays.net/rtg-tv.html', 'img': 'http://teledays.net/images/rtg-tv.png', 'title': 'RTG TV'},
{'url': 'http://teledays.net/ru-tv.html', 'img': 'http://teledays.net/images/ru-tv.png', 'title': '\xd1\x80\xd1\x83 \xd1\x82\xd0\xb2'},
{'url': 'http://teledays.net/russia-today.html', 'img': 'http://teledays.net/images/russia-today.png', 'title': 'Russia Today'},
{'url': 'http://teledays.net/travel-adventure.html', 'img': 'http://teledays.net/images/travel-adventure.png', 'title': 'Travel+Adventure'},
{'url': 'http://teledays.net/avto-plyus.html', 'img': 'http://teledays.net/images/avto-plyus.png', 'title': '\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe \xd0\x9f\xd0\xbb\xd1\x8e\xd1\x81'},
{'url': 'http://teledays.net/avto24.html', 'img': 'http://teledays.net/images/avto24.png', 'title': '\xd0\xb0\xd0\xb2\xd1\x82\xd0\xbe24'},
{'url': 'http://teledays.net/v-mire-zhivotnykh.html', 'img': 'http://teledays.net/images/v-mire-zhivotnykh.png', 'title': '\xd0\x92 \xd0\xbc\xd0\xb8\xd1\x80\xd0\xb5 \xd0\xb6\xd0\xb8\xd0\xb2\xd0\xbe\xd1\x82\xd0\xbd\xd1\x8b\xd1\x85'},
{'url': 'http://teledays.net/doktor.html', 'img': 'http://teledays.net/images/doktor.png', 'title': '\xd0\x94\xd0\xbe\xd0\xba\xd1\x82\xd0\xbe\xd1\x80'},
{'url': 'http://teledays.net/dom-kino-premium.html', 'img': 'http://teledays.net/images/dom-kino-premium.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe \xd0\x9f\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb8\xd1\x83\xd0\xbc'},
{'url': 'http://teledays.net/dorama.html', 'img': 'http://teledays.net/images/dorama.png', 'title': '\xd0\x94\xd0\xbe\xd1\x80\xd0\xb0\xd0\xbc\xd0\xb0'},
{'url': 'http://teledays.net/drajv-tv.html', 'img': 'http://teledays.net/images/drajv.png', 'title': '\xd0\xb4\xd1\x80\xd0\xb0\xd0\xb9\xd0\xb2 \xd1\x82\xd0\xb2'},
{'url': 'http://teledays.net/kinokhit.html', 'img': 'http://teledays.net/images/kinokhit.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x85\xd0\xb8\xd1\x82'},
{'url': 'http://teledays.net/evrokino.html', 'img': 'http://teledays.net/images/evrokino.png', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://teledays.net/eda-premium.html', 'img': 'http://teledays.net/images/eda-premium.png', 'title': '\xd0\x95\xd0\xb4\xd0\xb0 \xd0\x9f\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb8\xd1\x83\xd0\xbc'},
{'url': 'http://teledays.net/zhara.html', 'img': 'http://teledays.net/images/zhara.png', 'title': '\xd0\xb6\xd0\xb0\xd1\x80\xd0\xb0 \xd1\x82\xd0\xb2'},
{'url': 'http://teledays.net/zhivaya-planeta.html', 'img': 'http://teledays.net/images/zhivaya-planeta.png', 'title': '\xd0\x96\xd0\xb8\xd0\xb2\xd0\xb0\xd1\x8f \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'http://teledays.net/zagorodnaya-zhizn.html', 'img': 'http://teledays.net/images/zagorodnaya-zhizn.png', 'title': '\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb4\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xb6\xd0\xb8\xd0\xb7\xd0\xbd\xd1\x8c'},
{'url': 'http://teledays.net/zvezda.html', 'img': 'http://teledays.net/images/zvezda.png', 'title': '\xd0\x97\xd0\xb2\xd0\xb5\xd0\xb7\xd0\xb4\xd0\xb0'},
{'url': 'http://teledays.net/zoo-tv.html', 'img': 'http://teledays.net/images/zoo-tv.png', 'title': '\xd0\x97\xd0\xbe\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'http://teledays.net/illyuzion.html', 'img': 'http://teledays.net/images/illyuzion.png', 'title': '\xd0\xb8\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd+'},
{'url': 'http://teledays.net/istoriya.html', 'img': 'http://teledays.net/images/istoriya.png', 'title': '\xd0\x98\xd1\x81\xd1\x82\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f'},
{'url': 'http://teledays.net/indijskoe-kino.html', 'img': 'http://teledays.net/images/indijskoe-kino.png', 'title': '\xd0\x98\xd0\xbd\xd0\xb4\xd0\xb8\xd0\xb9\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://teledays.net/kapitan-fantastika.html', 'img': 'http://teledays.net/images/kapitan-fantastika.png', 'title': '\xd0\x9a\xd0\xb0\xd0\xbf\xd0\xb8\xd1\x82\xd0\xb0\xd0\xbd \xd0\xa4\xd0\xb0\xd0\xbd\xd1\x82\xd0\xb0\xd1\x81\xd1\x82\xd0\xb8\xd0\xba\xd0\xb0'},
{'url': 'http://teledays.net/karusel.html', 'img': 'http://teledays.net/images/karusel.png', 'title': '\xd0\x9a\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd0\xb5\xd0\xbb\xd1\x8c'},
{'url': 'http://teledays.net/kvn-tv.html', 'img': 'http://teledays.net/images/kvn-tv.png', 'title': '\xd0\x9a\xd0\x92\xd0\x9d \xd0\xa2\xd0\x92'},
{'url': 'http://teledays.net/kinosat.html', 'img': 'http://teledays.net/images/kinosat.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xa1\xd0\xb0\xd1\x82'},
{'url': 'http://teledays.net/kinopokaz.html', 'img': 'http://teledays.net/images/kinopokaz-hd.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbf\xd0\xbe\xd0\xba\xd0\xb0\xd0\xb7'},
{'url': 'http://teledays.net/komedijnoe.html', 'img': 'http://teledays.net/images/komedijnoe.png', 'title': '\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd0\xb9\xd0\xbd\xd0\xbe\xd0\xb5'},
{'url': 'http://teledays.net/konnyj-mir.html', 'img': 'http://teledays.net/images/konnyj-mir.png', 'title': '\xd0\x9a\xd0\xbe\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\xbc\xd0\xb8\xd1\x80'},
{'url': 'http://teledays.net/krasnaya-liniya.html', 'img': 'http://teledays.net/images/krasnaya-liniya.png', 'title': '\xd0\x9a\xd1\x80\xd0\xb0\xd1\x81\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xbb\xd0\xb8\xd0\xbd\xd0\xb8\xd1\x8f'},
{'url': 'http://teledays.net/kinokomediya.html', 'img': 'http://teledays.net/images/kinokomediya.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xba\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f'},
{'url': 'http://teledays.net/rossiya-kultura.html', 'img': 'http://teledays.net/images/rossiya-kultura.png', 'title': '\xd1\x80\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f \xd0\xba\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd1\x83\xd1\x80\xd0\xb0'},
{'url': 'http://teledays.net/mama.html', 'img': 'http://teledays.net/images/mama.png', 'title': '\xd0\x9c\xd0\xb0\xd0\xbc\xd0\xb0'},
{'url': 'http://teledays.net/moskva-24.html', 'img': 'http://teledays.net/images/moskva-24.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0 24'},
{'url': 'http://teledays.net/kinomiks.html', 'img': 'http://teledays.net/images/kinomiks.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbc\xd0\xb8\xd0\xba\xd1\x81'},
{'url': 'http://teledays.net/mir.html', 'img': 'http://teledays.net/images/mir.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x80'},
{'url': 'http://teledays.net/mir-24.html', 'img': 'http://teledays.net/images/mir-24.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x80 24'},
{'url': 'http://teledays.net/motorsport-tv.html', 'img': 'http://teledays.net/images/motorsport-tv.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x82\xd0\xbe\xd1\x80\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 \xd0\xa2\xd0\x92'},
{'url': 'http://teledays.net/moya-planeta.html', 'img': 'http://teledays.net/images/moya-planeta.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x8f \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'http://teledays.net/muz-tv.html', 'img': 'http://teledays.net/images/muz-tv.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb7-\xd0\xa2\xd0\x92'},
{'url': 'http://teledays.net/muzhskoj.html', 'img': 'http://teledays.net/images/muzhskoj.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9'},
{'url': 'http://teledays.net/muzyka-pervogo.html', 'img': 'http://teledays.net/images/muzyka-pervogo.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0 \xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd0\xbe\xd0\xb3\xd0\xbe'},
{'url': 'http://teledays.net/mult.html', 'img': 'http://teledays.net/images/mult.png', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82'},
{'url': 'http://teledays.net/multimuzyka.html', 'img': 'http://teledays.net/images/multimuzyka.png', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd0\xb8\xd0\xbc\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0'},
{'url': 'http://teledays.net/nauka.html', 'img': 'http://teledays.net/images/nauka.png', 'title': '\xd0\xbd\xd0\xb0\xd1\x83\xd0\xba\xd0\xb0 2.0'},
{'url': 'http://teledays.net/nash-kinoroman.html', 'img': 'http://teledays.net/images/nash-kinoroman.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88 \xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd'},
{'url': 'http://teledays.net/nashe-krutoe.html', 'img': 'http://teledays.net/images/nashe-krutoe.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88\xd0\xb5 \xd0\xba\xd1\x80\xd1\x83\xd1\x82\xd0\xbe\xd0\xb5'},
{'url': 'http://teledays.net/kinopremera.html', 'img': 'http://teledays.net/images/kinopremera.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbf\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8c\xd0\xb5\xd1\x80\xd0\xb0'},
{'url': 'http://teledays.net/lyubimoe-kino.html', 'img': 'http://teledays.net/images/lyubimoe-kino.png', 'title': '\xd0\x9b\xd1\x8e\xd0\xb1\xd0\xb8\xd0\xbc\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://teledays.net/kanal-o.html', 'img': 'http://teledays.net/images/o-kanal.png', 'title': '\xd0\xbe!'},
{'url': 'http://teledays.net/nashe-novoe-kino.html', 'img': 'http://teledays.net/images/nashe-novoe-kino.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88\xd0\xb5 \xd0\x9d\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb5 \xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://teledays.net/oruzhie.html', 'img': 'http://teledays.net/images/oruzhie.png', 'title': '\xd0\x9e\xd1\x80\xd1\x83\xd0\xb6\xd0\xb8\xd0\xb5'},
{'url': 'http://teledays.net/ntv-mir.html', 'img': 'http://teledays.net/images/ntv-mir.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 \xd0\x9c\xd0\xb8\xd1\x80'},
{'url': 'http://teledays.net/ntv-serial.html', 'img': 'http://teledays.net/images/ntv-serial.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 \xd0\xa1\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb'},
{'url': 'http://teledays.net/ntv-khit.html', 'img': 'http://teledays.net/images/ntv-khit.png', 'title': '\xd0\xbd\xd1\x82\xd0\xb2 \xd1\x85\xd0\xb8\xd1\x82'},
{'url': 'http://teledays.net/ostrosyuzhetnoe-hd.html', 'img': 'http://teledays.net/images/ostrosyuzhetnoe-hd.png', 'title': '\xd0\x9e\xd1\x81\xd1\x82\xd1\x80\xd0\xbe\xd1\x81\xd1\x8e\xd0\xb6\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe\xd0\xb5 HD'},
{'url': 'http://teledays.net/otr.html', 'img': 'http://teledays.net/images/otr.png', 'title': '\xd0\x9e\xd0\xa2\xd0\xa0'},
{'url': 'http://teledays.net/okhota-i-rybalka.html', 'img': 'http://teledays.net/images/okhota-i-rybalka.png', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xb0 \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xb0\xd0\xbb\xd0\xba\xd0\xb0'},
{'url': 'http://teledays.net/okhotnik-i-rybolov.html', 'img': 'http://teledays.net/images/okhotnik-i-rybolov.png', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2'},
{'url': 'http://teledays.net/premialnoe-hd.html', 'img': 'http://teledays.net/images/premialnoe-hd.png', 'title': '\xd0\x9f\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb8\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd0\xbe\xd0\xb5 HD'},
{'url': 'http://teledays.net/pyatyj-kanal.html', 'img': 'http://teledays.net/images/pyatyj-kanal.png', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'http://teledays.net/radost-moya.html', 'img': 'http://teledays.net/images/radost-moya.png', 'title': '\xd0\xa0\xd0\xb0\xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c \xd0\xbc\xd0\xbe\xd1\x8f'},
{'url': 'http://teledays.net/rbk-tv.html', 'img': 'http://teledays.net/images/rbk-tv.png', 'title': '\xd1\x80\xd0\xb1\xd0\xba \xd1\x82\xd0\xb2'},
{'url': 'http://teledays.net/rossiya-24.html', 'img': 'http://teledays.net/images/rossiya-24.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 24'},
{'url': 'http://teledays.net/kinosvidanie.html', 'img': 'http://teledays.net/images/kinosvidanie.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb2\xd0\xb8\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'},
{'url': 'http://teledays.net/rodnoe-kino.html', 'img': 'http://teledays.net/images/rodnoe-kino.png', 'title': '\xd0\xa0\xd0\xbe\xd0\xb4\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://teledays.net/russkij-bestseller.html', 'img': 'http://teledays.net/images/russkij-bestseller.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb1\xd0\xb5\xd1\x81\xd1\x82\xd1\x81\xd0\xb5\xd0\xbb\xd0\xbb\xd0\xb5\xd1\x80'},
{'url': 'http://teledays.net/russkij-detektiv.html', 'img': 'http://teledays.net/images/russkij-detektiv.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb4\xd0\xb5\xd1\x82\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2'},
{'url': 'http://teledays.net/russkij-illyuzion.html', 'img': 'http://teledays.net/images/russkij-illyuzion.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb8\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd'},
{'url': 'http://teledays.net/sarafan.html', 'img': 'http://teledays.net/images/sarafan.png', 'title': '\xd0\xa1\xd0\xb0\xd1\x80\xd0\xb0\xd1\x84\xd0\xb0\xd0\xbd'},
{'url': 'http://teledays.net/sila-tv.html', 'img': 'http://teledays.net/images/sila-tv.png', 'title': '\xd0\xa1\xd0\xb8\xd0\xbb\xd0\xb0 \xd0\xa2\xd0\x92'},
{'url': 'http://teledays.net/sovershenno-sekretno.html', 'img': 'http://teledays.net/images/sovershenno-sekretno.png', 'title': '\xd0\xa1\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x80\xd1\x88\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xbe \xd1\x81\xd0\xb5\xd0\xba\xd1\x80\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe'},
{'url': 'http://teledays.net/strashnoe-hd.html', 'img': 'http://teledays.net/images/strashnoe-hd.png', 'title': '\xd0\xa1\xd1\x82\xd1\x80\xd0\xb0\xd1\x88\xd0\xbd\xd0\xbe\xd0\xb5 HD'},
{'url': 'http://teledays.net/super.html', 'img': 'http://teledays.net/images/super.png', 'title': '\xd1\x81\xd1\x83\xd0\xbf\xd0\xb5\xd1\x80'},
{'url': 'http://teledays.net/tv-tsentr.html', 'img': 'http://teledays.net/images/tvts.png', 'title': '\xd0\xa2\xd0\x92 \xd0\xa6\xd0\xb5\xd0\xbd\xd1\x82\xd1\x80'},
{'url': 'http://teledays.net/tdk.html', 'img': 'http://teledays.net/images/tdk.png', 'title': '\xd0\xa2\xd0\x94\xd0\x9a'},
{'url': 'http://teledays.net/tekhno-24.html', 'img': 'http://teledays.net/images/tekhno-24.png', 'title': '\xd0\xa2\xd0\xb5\xd1\x85\xd0\xbd\xd0\xbe 24'},
{'url': 'http://teledays.net/tnt-music.html', 'img': 'http://teledays.net/images/tnt-music.png', 'title': '\xd1\x82\xd0\xbd\xd1\x82 music'},
{'url': 'http://teledays.net/tnt4.html', 'img': 'http://teledays.net/images/tnt4.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa24'},
{'url': 'http://teledays.net/tochka-otryva.html', 'img': 'http://teledays.net/images/tochka-otryva.png', 'title': '\xd0\xa2\xd0\xbe\xd1\x87\xd0\xba\xd0\xb0 \xd0\xbe\xd1\x82\xd1\x80\xd1\x8b\xd0\xb2\xd0\xb0'},
{'url': 'http://teledays.net/tochka-tv.html', 'img': 'http://teledays.net/images/tochka-tv.png', 'title': '\xd0\xa2\xd0\xbe\xd1\x87\xd0\xba\xd0\xb0 \xd0\xa2\xd0\x92'},
{'url': 'http://teledays.net/unikum.html', 'img': 'http://teledays.net/images/unikum.png', 'title': '\xd0\xa3\xd0\xbd\xd0\xb8\xd0\xba\xd1\x83\xd0\xbc'},
{'url': 'http://teledays.net/shanson-tv.html', 'img': 'http://teledays.net/images/shanson-tv.png', 'title': '\xd0\xa8\xd0\xb0\xd0\xbd\xd1\x81\xd0\xbe\xd0\xbd \xd0\xa2\xd0\x92'},
{'url': 'http://teledays.net/shokiruyushchee.html', 'img': 'http://teledays.net/images/shokiruyushchee.png', 'title': '\xd0\xa8\xd0\xbe\xd0\xba\xd0\xb8\xd1\x80\xd1\x83\xd1\x8e\xd1\x89\xd0\xb5\xd0\xb5 HD'},
{'url': 'http://teledays.net/bollywood-hd.html', 'img': 'http://teledays.net/images/bollywood-hd.png', 'title': 'Bollywood HD'},
{'url': 'http://teledays.net/euronews.html', 'img': 'http://teledays.net/images/euronews.png', 'title': 'Euronews'},
{'url': 'http://teledays.net/extreme-sports.html', 'img': 'http://teledays.net/images/extreme-sports.png', 'title': 'Extreme sports'},
{'url': 'http://teledays.net/filmbox.html', 'img': 'http://teledays.net/images/filmbox.png', 'title': 'FilmBox'},
{'url': 'http://teledays.net/fine-living.html', 'img': 'http://teledays.net/images/fine-living.png', 'title': 'Fine Living'},
{'url': 'http://teledays.net/fox-life.html', 'img': 'http://teledays.net/images/fox-life.png', 'title': 'Fox Life'},
{'url': 'http://teledays.net/fox.html', 'img': 'http://teledays.net/images/fox.png', 'title': 'FOX'},
{'url': 'http://teledays.net/gulli-girl.html', 'img': 'http://teledays.net/images/gulli-girl.png', 'title': 'Gulli Girl'},
{'url': 'http://teledays.net/kinosemya.html', 'img': 'http://teledays.net/images/kinosemya.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb5\xd0\xbc\xd1\x8c\xd1\x8f'},
{'url': 'http://teledays.net/history-channel.html', 'img': 'http://teledays.net/images/history.png', 'title': 'History'},
{'url': 'http://teledays.net/jimjam.html', 'img': 'http://teledays.net/images/jimjam.png', 'title': 'JimJam'},
{'url': 'http://teledays.net/mezzo.html', 'img': 'http://teledays.net/images/mezzo.png', 'title': 'Mezzo'},
{'url': 'http://teledays.net/mezzo-live-hd.html', 'img': 'http://teledays.net/images/mezzo-live-hd.png', 'title': 'Mezzo Live HD'},
{'url': 'http://teledays.net/nick-jr.html', 'img': 'http://teledays.net/images/nick-jr.png', 'title': 'Nick Jr'},
{'url': 'http://teledays.net/nat-geo-wild.html', 'img': 'http://teledays.net/images/nat-geo-wild.png', 'title': 'Nat Geo Wild'},
{'url': 'http://teledays.net/national-geographic.html', 'img': 'http://teledays.net/images/national-geographic.png', 'title': 'National Geographic'},
{'url': 'http://teledays.net/outdoor-channel.html', 'img': 'http://teledays.net/images/outdoor-channel.png', 'title': 'Outdoor'},
{'url': 'http://teledays.net/sony-channel.html', 'img': 'http://teledays.net/images/sony-channel.png', 'title': 'Sony Channel'},
{'url': 'http://teledays.net/sony-sci-fi.html', 'img': 'http://teledays.net/images/sony-sci-fi.png', 'title': 'Sony Sci-Fi'},
{'url': 'http://teledays.net/sony-turbo.html', 'img': 'http://teledays.net/images/sony-turbo.png', 'title': 'Sony Turbo'},
{'url': 'http://teledays.net/spike.html', 'img': 'http://teledays.net/images/spike.png', 'title': 'Spike'},
{'url': 'http://teledays.net/tiji.html', 'img': 'http://teledays.net/images/tiji.png', 'title': 'TiJi'},
{'url': 'http://teledays.net/travel-channel.html', 'img': 'http://teledays.net/images/travel-channel.png', 'title': 'Travel Channel'},
{'url': 'http://teledays.net/world-fashion-channel.html', 'img': 'http://teledays.net/images/world-fashion-channel.png', 'title': 'World Fashion'},
{'url': 'http://teledays.net/kinoseriya.html', 'img': 'http://teledays.net/images/kinoseriya.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb5\xd1\x80\xd0\xb8\xd1\x8f'},
{'url': 'http://teledays.net/detskij-mir.html', 'img': 'http://teledays.net/images/detskij-mir.png', 'title': '\xd0\x94\xd0\xb5\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xbc\xd0\xb8\xd1\x80'},
{'url': 'http://teledays.net/mir-seriala.html', 'img': 'http://teledays.net/images/mir-seriala.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x80 \xd1\x81\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb\xd0\xb0'},
{'url': 'http://teledays.net/multilandiya.html', 'img': 'http://teledays.net/images/multilandiya.png', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd0\xb8\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb4\xd0\xb8\xd1\x8f'},
{'url': 'http://teledays.net/tv-xxi.html', 'img': 'http://teledays.net/images/tv-xxi.png', 'title': 'TV 21'},
{'url': 'http://teledays.net/romantichnoe-hd.html', 'img': 'http://teledays.net/images/romantichnoe-hd.png', 'title': '\xd0\xa0\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd\xd1\x82\xd0\xb8\xd1\x87\xd0\xbd\xd0\xbe\xd0\xb5 HD'},
{'url': 'http://teledays.net/rtr-planeta.html', 'img': 'http://teledays.net/images/rtr-planeta.png', 'title': '\xd1\x80\xd1\x82\xd1\x80 \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'http://teledays.net/vh1.html', 'img': 'http://teledays.net/images/vh1.png', 'title': 'VH1'},
{'url': 'http://teledays.net/pervyj-krymskij.html', 'img': 'http://teledays.net/images/pervyj-krymskij.png', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\x9a\xd1\x80\xd1\x8b\xd0\xbc\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9'},
{'url': 'http://teledays.net/9-kanal-izrail.html', 'img': 'http://teledays.net/images/9-kanal-izrail.png', 'title': '9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb (\xd0\x98\xd0\xb7\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbb\xd1\x8c)'},
{'url': 'http://teledays.net/bridge-tv-hits.html', 'img': 'http://teledays.net/images/bridge-tv-hits.png', 'title': 'Bridge TV Hits'},
]
udata=1607072767.06