[
{'url': 'rustv:pervii', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/0.png', 'title': '\xd0\xbf\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9'},
{'url': 'rustv:ntv', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/1.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x92'},
{'url': 'rustv:tnt', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/2.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2'},
{'url': 'rustv:sts', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/3.png', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1'},
{'url': 'rustv:rentv', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/4.png', 'title': '\xd0\xa0\xd0\xb5\xd0\xbd \xd0\xa2\xd0\x92'},
{'url': 'rustv:tv3', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/5.png', 'title': '\xd0\xa2\xd0\x92-3'},
{'url': 'rustv:che', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/6.png', 'title': '\xd0\xa7\xd0\xb5'},
{'url': 'rustv:patnica', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/7.png', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd0\xbd\xd0\xb8\xd1\x86\xd0\xb0'},
{'url': 'rustv:utv', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/8.png', 'title': '\xd0\xae'},
{'url': 'rustv:russia1', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/9.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 1'},
{'url': 'rustv:russiak', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/10.png', 'title': '\xd1\x80\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f \xd0\xba'},
{'url': 'rustv:rtr-planeta', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/11.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f \xd0\xa0\xd0\xa2\xd0\xa0'},
{'url': 'rustv:tvc', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/12.png', 'title': '\xd0\xa2\xd0\x92 \xd0\xa6\xd0\xb5\xd0\xbd\xd1\x82\xd1\x80'},
{'url': 'rustv:5kanal', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/13.png', 'title': '5 \xd0\x9a\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'rustv:domashnii', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/14.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc\xd0\xb0\xd1\x88\xd0\xbd\xd0\xb8\xd0\xb9'},
{'url': 'rustv:zvezda', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/15.png', 'title': '\xd0\x97\xd0\xb2\xd0\xb5\xd0\xb7\xd0\xb4\xd0\xb0'},
{'url': 'rustv:mir', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/16.png', 'title': '\xd0\x9c\xd0\x98\xd0\xa0'},
{'url': 'rustv:otr', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/17.png', 'title': '\xd0\x9e\xd0\xa2\xd0\xa0'},
{'url': 'rustv:russia24', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/18.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 24'},
{'url': 'rustv:rbk', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/19.png', 'title': '\xd0\xa0\xd0\x91\xd0\x9a'},
{'url': 'rustv:lifenews', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/20.png', 'title': '\xd0\x98\xd0\xb7\xd0\xb2\xd0\xb5\xd1\x81\xd1\x82\xd0\xb8\xd1\x8f'},
{'url': 'rustv:eda', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/21.png', 'title': '\xd0\x95\xd0\xb4\xd0\xb0 \xd0\xa2\xd0\x92'},
{'url': 'rustv:wbc', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/22.png', 'title': 'World Business Channel'},
{'url': 'rustv:luxury', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/23.png', 'title': 'Luxury World'},
{'url': 'rustv:fashion-tv', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/24.png', 'title': 'world fashion channel'},
{'url': 'rustv:strana', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/25.png', 'title': '\xd0\x9a\xd1\x80\xd0\xb0\xd1\x81\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xbb\xd0\xb8\xd0\xbd\xd0\xb8\xd1\x8f'},
{'url': 'rustv:tdk', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/26.png', 'title': '\xd0\x94\xd0\xb0\xd0\xbc\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xba\xd0\xbb\xd1\x83\xd0\xb1'},
{'url': 'rustv:umor-tv', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/27.png', 'title': '\xd0\xae\xd0\xbc\xd0\xbe\xd1\x80 BOX'},
{'url': 'rustv:tnt-4', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/28.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2-4'},
{'url': 'rustv:moskow-24', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/29.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0 24'},
{'url': 'rustv:zoo-tv', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/30.png', 'title': 'Zoo \xd0\xa2\xd0\x92'},
{'url': 'rustv:tnv', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/31.png', 'title': '\xd1\x82\xd0\xbd\xd0\xb2 \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'rustv:8kanal', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/32.png', 'title': '8 \xd0\x9a\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'rustv:novoe-tv', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/33.png', 'title': 'Game Show'},
{'url': 'rustv:360', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/34.png', 'title': '360\xc2\xb0 \xd0\xbf\xd0\xbe\xd0\xb4\xd0\xbc\xd0\xbe\xd1\x81\xd0\xba\xd0\xbe\xd0\xb2\xd1\x8c\xd0\xb5'},
{'url': 'rustv:souz', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/35.png', 'title': '\xd0\xa1\xd0\xbe\xd1\x8e\xd0\xb7'},
{'url': 'rustv:disney', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/36.png', 'title': 'disney'},
{'url': 'rustv:detskii', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/37.png', 'title': '\xd0\x94\xd0\xb5\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xbc\xd0\xb8\xd1\x80'},
{'url': 'rustv:karusel', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/38.png', 'title': '\xd0\x9a\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd0\xb5\xd0\xbb\xd1\x8c'},
{'url': 'rustv:ulibka', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/39.png', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82 \xd0\xbc\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0'},
{'url': 'rustv:radost', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/40.png', 'title': '\xd0\xa0\xd0\xb0\xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c \xd0\x9c\xd0\xbe\xd1\x8f'},
{'url': 'rustv:nickelodeon', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/41.png', 'title': '\xd0\xa0\xd1\x8b\xd0\xb6\xd0\xb8\xd0\xb9'},
{'url': 'rustv:barboskiny', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/42.png', 'title': '\xd0\x91\xd0\xb0\xd1\x80\xd0\xb1\xd0\xbe\xd1\x81\xd0\xba\xd0\xb8\xd0\xbd\xd1\x8b'},
{'url': 'rustv:fiksiki', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/43.png', 'title': '\xd0\xa4\xd0\xb8\xd0\xba\xd1\x81\xd0\xb8\xd0\xba\xd0\xb8'},
{'url': 'rustv:masha', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/44.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x88\xd0\xb0 \xd0\xb8 \xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb2\xd0\xb5\xd0\xb4\xd1\x8c'},
{'url': 'rustv:tom-jerry', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/45.png', 'title': '\xd0\xa2\xd0\xbe\xd0\xbc \xd0\xb8 \xd0\x94\xd0\xb6\xd0\xb5\xd1\x80\xd1\x80\xd0\xb8'},
{'url': 'rustv:chip-deil', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/46.png', 'title': '\xd0\xa7\xd0\xb8\xd0\xbf \xd0\xb8 \xd0\x94\xd0\xb5\xd0\xb8\xd0\xbb'},
{'url': 'rustv:duck-tales', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/47.png', 'title': '\xd0\xa3\xd1\x82\xd0\xb8\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb5 \xd0\xb8\xd1\x81\xd1\x82\xd0\xbe\xd1\x80\xd0\xb8\xd0\xb8'},
{'url': 'rustv:winnie-pooh', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/48.png', 'title': '\xd0\x92\xd0\xb8\xd0\xbd\xd0\xbd\xd0\xb8 \xd0\xbf\xd1\x83\xd1\x85'},
{'url': 'rustv:mishki', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/49.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x88\xd0\xba\xd0\xb8 \xd0\x93\xd0\xb0\xd0\xbc\xd0\xbc\xd0\xb8'},
{'url': 'rustv:tale-spin', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/50.png', 'title': '\xd0\xa7\xd1\x83\xd0\xb4\xd0\xb5\xd1\x81\xd0\xb0 \xd0\xbd\xd0\xb0 \xd0\xb2\xd0\xb8\xd1\x80\xd0\xb0\xd0\xb6\xd0\xb0\xd1\x85'},
{'url': 'rustv:mermaid', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/51.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd0\xb0\xd0\xbb\xd0\xbe\xd1\x87\xd0\xba\xd0\xb0'},
{'url': 'rustv:aladdin', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/52.png', 'title': '\xd0\x90\xd0\xbb\xd0\xb0\xd0\xb4\xd0\xb4\xd0\xb8\xd0\xbd'},
{'url': 'rustv:sponge-bob', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/53.png', 'title': '\xd0\x93\xd1\x83\xd0\xb1\xd0\xba\xd0\xb0 \xd0\x91\xd0\xbe\xd0\xb1'},
{'url': 'rustv:eurokino', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/54.png', 'title': '\xd0\x9b\xd1\x8e\xd0\xb1\xd0\xb8\xd0\xbc\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'rustv:a2', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/55.png', 'title': 'A2'},
{'url': 'rustv:illizion', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/56.png', 'title': '\xd0\x9a\xd0\xbb\xd0\xb0\xd1\x81\xd1\x81\xd0\xb8\xd0\xba\xd0\xb0 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'rustv:tv21', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/57.png', 'title': 'TV XXI'},
{'url': 'rustv:zeetv', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/58.png', 'title': 'zee tv'},
{'url': 'rustv:teledom', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/59.png', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xb4\xd0\xbe\xd0\xbc'},
{'url': 'rustv:kino-menu', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/60.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe \xd0\xbc\xd0\xb5\xd0\xbd\xd1\x8e'},
{'url': 'rustv:tvm-channel', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/61.png', 'title': 'TVM Channel'},
{'url': 'rustv:egoist', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/62.png', 'title': '\xd0\xad\xd0\xb3\xd0\xbe\xd0\xb8\xd1\x81\xd1\x82 \xd0\xa2\xd0\x92'},
{'url': 'rustv:dom-kino', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/63.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'rustv:nst', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/64.png', 'title': '\xd0\x9d\xd0\xa1\xd0\xa2'},
{'url': 'rustv:tro', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/65.png', 'title': '\xd0\xa2\xd0\xa0\xd0\x9e'},
{'url': 'rustv:komedia', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/66.png', 'title': '\xd0\x9b\xd1\x8e\xd0\xb1\xd0\xb8\xd0\xbc\xd0\xbe\xd0\xb5 \xd0\xa2\xd0\x92'},
{'url': 'rustv:vhs', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/67.png', 'title': 'VHS \xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x82\xd0\xb5\xd0\xb0\xd1\x82\xd1\x80'},
{'url': 'rustv:tochka-tv', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/68.png', 'title': '\xd0\xa2\xd0\xbe\xd1\x87\xd0\xba\xd0\xb0 \xd0\xa2\xd0\x92'},
{'url': 'rustv:eho-tv', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/69.png', 'title': '\xd0\xad\xd1\x85\xd0\xbe TV'},
{'url': 'rustv:alf', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/70.png', 'title': '\xd0\x90\xd0\xbb\xd1\x8c\xd1\x84'},
{'url': 'rustv:duraki', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/71.png', 'title': '\xd0\x94\xd0\xb5\xd1\x80\xd0\xb5\xd0\xb2\xd0\xbd\xd1\x8f \xd0\xb4\xd1\x83\xd1\x80\xd0\xb0\xd0\xba\xd0\xbe\xd0\xb2'},
{'url': 'rustv:discovery', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/72.png', 'title': 'Discovery Channel'},
{'url': 'rustv:animal', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/73.png', 'title': 'Animal Planet'},
{'url': 'rustv:rtd', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/74.png', 'title': 'Russia Today Documentary'},
{'url': 'rustv:nat-geo-wild', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/75.png', 'title': '\xd0\xa1\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x80\xd1\x88\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xbe \xd1\x81\xd0\xb5\xd0\xba\xd1\x80\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe'},
{'url': 'rustv:history', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/76.png', 'title': '\xd0\x98\xd1\x81\xd1\x82\xd0\xbe\xd1\x80\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9'},
{'url': 'rustv:univer', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/77.png', 'title': '\xd0\xa3\xd0\xbd\xd0\xb8\xd0\xb2\xd0\xb5\xd1\x80\xd1\x81\xd0\xb8\xd1\x82\xd0\xb5\xd1\x82 \xd0\xa2\xd0\x92'},
{'url': 'rustv:bober', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/78.png', 'title': '\xd0\xb1\xd0\xbe\xd0\xb1\xd0\xb5\xd1\x80 \xd1\x82\xd0\xb2'},
{'url': 'rustv:kak-rabotaet', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/79.png', 'title': '\xd0\x9a\xd0\xb0\xd0\xba \xd1\x8d\xd1\x82\xd0\xbe \xd1\x80\xd0\xb0\xd0\xb1\xd0\xbe\xd1\x82\xd0\xb0\xd0\xb5\xd1\x82'},
{'url': 'rustv:myth-busters', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/80.png', 'title': '\xd0\xa0\xd0\xb0\xd0\xb7\xd1\x80\xd1\x83\xd1\x88\xd0\xb8\xd1\x82\xd0\xb5\xd0\xbb\xd0\xb8 \xd0\xbc\xd0\xb8\xd1\x84\xd0\xbe\xd0\xb2'},
{'url': 'rustv:moya-planeta', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/81.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x8f \xd0\x9f\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'rustv:nauka', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/82.png', 'title': '\xd0\xbd\xd0\xb0\xd1\x83\xd0\xba\xd0\xb0 2.0'},
{'url': 'rustv:orugie', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/83.png', 'title': '\xd0\x9e\xd1\x80\xd1\x83\xd0\xb6\xd0\xb8\xd0\xb5'},
{'url': 'rustv:prosweshwnie', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/84.png', 'title': '\xd0\x9f\xd1\x80\xd0\xbe\xd1\x81\xd0\xb2\xd0\xb5\xd1\x89\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5'},
{'url': 'rustv:nano', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/85.png', 'title': '\xd0\xbd\xd0\xb0\xd0\xbd\xd0\xbe \xd1\x82\xd0\xb2'},
{'url': 'rustv:kaleidoskop', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/86.png', 'title': '\xd0\x9a\xd0\xb0\xd0\xbb\xd0\xb5\xd0\xb9\xd0\xb4\xd0\xbe\xd1\x81\xd0\xba\xd0\xbe\xd0\xbf'},
{'url': 'rustv:24-techno', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/87.png', 'title': '24 \xd1\x82\xd0\xb5\xd1\x85\xd0\xbd\xd0\xbe'},
{'url': 'rustv:galileo', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/88.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x85\xd0\xb8\xd0\xbd\xd0\xb0\xd1\x82\xd0\xbe\xd1\x80\xd1\x8b'},
{'url': 'rustv:ocean-tv', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/89.png', 'title': 'O\xd0\xba\xd0\xb5\xd0\xb0\xd0\xbd \xd0\xa2\xd0\x92'},
{'url': 'rustv:tnt-music', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/90.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2 Music'},
{'url': 'rustv:music-box', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/91.png', 'title': 'music box'},
{'url': 'rustv:ru-tv', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/92.png', 'title': 'Ru TV'},
{'url': 'rustv:a-one', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/93.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88\xd0\xb5 \xd0\xa2\xd0\x92'},
{'url': 'rustv:o2tv', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/94.png', 'title': '\xd0\xbe2 \xd1\x82\xd0\xb2'},
{'url': 'rustv:1hd', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/95.png', 'title': '\xd0\xbf\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 hd'},
{'url': 'rustv:1-music', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/96.png', 'title': '1 Music HD'},
{'url': 'rustv:monte-carlo', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/97.png', 'title': 'Monte Carlo'},
{'url': 'rustv:retro', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/98.png', 'title': 'Retro'},
{'url': 'rustv:europa-plus-tv', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/99.png', 'title': 'Europa Plus TV'},
{'url': 'rustv:bridge', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/100.png', 'title': 'Bridge TV'},
{'url': 'rustv:vh1', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/101.png', 'title': 'VH1 Classic'},
{'url': 'rustv:pik', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/102.png', 'title': 'NRJ Hits'},
{'url': 'rustv:shanson', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/103.png', 'title': '\xd1\x88\xd0\xb0\xd0\xbd\xd1\x81\xd0\xbe\xd0\xbd tb'},
{'url': 'rustv:9volna', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/104.png', 'title': 'ACB TV'},
{'url': 'rustv:muzsouz', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/105.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb7 \xd0\xa1\xd0\xbe\xd1\x8e\xd0\xb7'},
{'url': 'rustv:radio102', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/106.png', 'title': 'Radio 102.5'},
{'url': 'rustv:virgin', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/107.png', 'title': 'Virgin TV'},
{'url': 'rustv:matc', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/108.png', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87!'},
{'url': 'rustv:arena', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/109.png', 'title': '\xd0\xa1\xd1\x82\xd0\xb0\xd1\x80\xd1\x82'},
{'url': 'rustv:igra', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/110.png', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba \xd0\xb8 \xd0\xa0\xd1\x8b\xd0\xb1\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2 HD'},
{'url': 'rustv:auto-plus', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/111.png', 'title': '\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe \xd0\x9f\xd0\xbb\xd1\x8e\xd1\x81'},
{'url': 'rustv:rus-extreme', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/112.png', 'title': '\xd0\x9a\xd0\xbe\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\xbc\xd0\xb8\xd1\x80'},
{'url': 'rustv:khl', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/113.png', 'title': '\xd0\x9a\xd0\xa5\xd0\x9b'},
{'url': 'rustv:top-gear', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/114.png', 'title': 'Top Gear'},
{'url': 'rustv:boetc', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/115.png', 'title': '\xd0\x91\xd0\xbe\xd0\xb5\xd1\x86'},
{'url': 'rustv:football', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/116.png', 'title': '\xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb'},
{'url': 'rustv: ', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/117.png', 'title': ' '},
{'url': 'rustv: ', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/118.png', 'title': ' '},
{'url': 'rustv: ', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/119.png', 'title': ' '},
{'url': 'rustv: ', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/120.png', 'title': ' '},
{'url': 'rustv: ', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/121.png', 'title': ' '},
{'url': 'rustv: ', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/122.png', 'title': ' '},
{'url': 'rustv: ', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/123.png', 'title': ' '},
{'url': 'rustv: ', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/124.png', 'title': ' '},
{'url': 'rustv: ', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/125.png', 'title': ' '},
{'url': 'rustv:2x2', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/126.png', 'title': '2x2'},
{'url': 'rustv:simpsons', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/127.png', 'title': '\xd0\xa1\xd0\xb8\xd0\xbc\xd0\xbf\xd1\x81\xd0\xbe\xd0\xbd\xd1\x8b'},
{'url': 'rustv:futurama', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/128.png', 'title': '\xd0\xa4\xd1\x83\xd1\x82\xd1\x83\xd1\x80\xd0\xb0\xd0\xbc\xd0\xb0'},
{'url': 'rustv:family-guy', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/129.png', 'title': '\xd0\x93\xd1\x80\xd0\xb8\xd1\x84\xd1\x84\xd0\xb8\xd0\xbd\xd1\x8b'},
{'url': 'rustv:south-park', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/130.png', 'title': '\xd0\xae\xd0\xb6\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\xbf\xd0\xb0\xd1\x80\xd0\xba'},
{'url': 'rustv:cleveland', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/131.png', 'title': '\xd0\xa8\xd0\xbe\xd1\x83 \xd0\xba\xd0\xbb\xd0\xb8\xd0\xb2\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xb4\xd0\xb0'},
{'url': 'rustv:robochicken', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/132.png', 'title': '\xd0\xa0\xd0\xbe\xd0\xb1\xd0\xbe\xd1\x86\xd1\x8b\xd0\xbf'},
{'url': 'rustv:beavis', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/133.png', 'title': '\xd0\x91\xd0\xb8\xd0\xb2\xd0\xb8\xd1\x81 \xd0\xb8 \xd0\x91\xd0\xb0\xd1\x82\xd1\x85\xd0\xb5\xd0\xb4'},
{'url': 'rustv:ghostbusters', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/134.png', 'title': '\xd0\xa0\xd0\xb8\xd0\xba \xd0\xb8 \xd0\x9c\xd0\xbe\xd1\x80\xd1\x82\xd0\xb8'},
{'url': 'rustv: ', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/135.png', 'title': ' '},
{'url': 'rustv: ', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/136.png', 'title': ' '},
{'url': 'rustv: ', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/137.png', 'title': ' '},
{'url': 'rustv: ', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/138.png', 'title': ' '},
{'url': 'rustv: ', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/139.png', 'title': ' '},
{'url': 'rustv: ', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/140.png', 'title': ' '},
{'url': 'rustv: ', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/141.png', 'title': ' '},
{'url': 'rustv: ', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/142.png', 'title': ' '},
{'url': 'rustv: ', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/143.png', 'title': ' '},
{'url': 'rustv:europa-plus', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/144.png', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd0\xbf\xd0\xb0 \xd0\x9f\xd0\xbb\xd1\x8e\xd1\x81'},
{'url': 'rustv:dfm', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/145.png', 'title': '\xd0\x94\xd0\xb8\xd0\xbd\xd0\xb0\xd0\xbc\xd0\xb8\xd1\x82 \xd0\xa4\xd0\x9c'},
{'url': 'rustv:record', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/146.png', 'title': '\xd0\xa0\xd0\xb5\xd0\xba\xd0\xbe\xd1\x80\xd0\xb4 \xd0\xa4\xd0\x9c'},
{'url': 'rustv:love-radio', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/147.png', 'title': '\xd0\x9d\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb5 \xd1\x80\xd0\xb0\xd0\xb4\xd0\xb8\xd0\xbe'},
{'url': 'rustv:maximum', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/148.png', 'title': '\xd0\x9c\xd0\xb0\xd0\xba\xd1\x81\xd0\xb8\xd0\xbc\xd1\x83\xd0\xbc'},
{'url': 'rustv:nrj', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/149.png', 'title': 'NRJ'},
{'url': 'rustv:megapolis', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/150.png', 'title': 'Megapolis'},
{'url': 'rustv:romantica', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/151.png', 'title': '\xd0\xa0\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd\xd1\x82\xd0\xb8\xd0\xba\xd0\xb0'},
{'url': 'rustv:retro-fm', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/152.png', 'title': '\xd0\xa0\xd0\xb5\xd1\x82\xd1\x80\xd0\xbe \xd0\xa4\xd0\x9c'},
{'url': 'rustv:russkoe-radio', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/153.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd1\x80\xd0\xb0\xd0\xb4\xd0\xb8\xd0\xbe'},
{'url': 'rustv:radio-dacha', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/154.png', 'title': '\xd0\xa0\xd0\xb0\xd0\xb4\xd0\xb8\xd0\xbe \xd0\xb4\xd0\xb0\xd1\x87\xd0\xb0'},
{'url': 'rustv:dorojnoe-radio', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/155.png', 'title': '\xd0\x94\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb6\xd0\xbd\xd0\xbe\xd0\xb5 \xd1\x80\xd0\xb0\xd0\xb4\xd0\xb8\xd0\xbe'},
{'url': 'rustv:avtoradio', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/156.png', 'title': '\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe\xd1\x80\xd0\xb0\xd0\xb4\xd0\xb8\xd0\xbe'},
{'url': 'rustv:shanson-fm', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/157.png', 'title': '\xd0\xa8\xd0\xb0\xd0\xbd\xd1\x81\xd0\xbe\xd0\xbd \xd0\xa4\xd0\x9c'},
{'url': 'rustv:hit-fm', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/158.png', 'title': '\xd0\xa5\xd0\xb8\xd1\x82 \xd0\xa4\xd0\x9c'},
{'url': 'rustv:radio-sibir', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/159.png', 'title': '\xd0\xa0\xd0\xb0\xd0\xb4\xd0\xb8\xd0\xbe \xd1\x81\xd0\xb8\xd0\xb1\xd0\xb8\xd1\x80\xd1\x8c'},
{'url': 'rustv:eho-moskow', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/160.png', 'title': '\xd0\xad\xd1\x85\xd0\xbe \xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd1\x8b'},
{'url': 'rustv:mayak', 'group': '', 'img': 'https://www.rustv-player.ru/tv/images/icon/161.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x8f\xd0\xba'},
]
udata=1575454310.77