[
{'url': 'telecdn:eurosport', 'img': 'http://telecdn.net/img/eurosport.png', 'title': 'Eurosport 1'},
{'url': 'telecdn:ntv', 'img': 'http://telecdn.net/img/ntv.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x92'},
{'url': 'telecdn:muztv', 'img': 'http://telecdn.net/img/muztv.png', 'title': '\xd0\xbc\xd1\x83\xd0\xb7 \xd1\x82\xd0\xb2'},
{'url': 'telecdn:ostrotv', 'img': 'http://telecdn.net/img/ostrotv.png', 'title': '\xd0\x9e\xd1\x81\xd1\x82\xd1\x80\xd0\xbe\xd1\x81\xd1\x8e\xd0\xb6\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe\xd0\xb5 HD'},
{'url': 'telecdn:nauka2', 'img': 'http://telecdn.net/img/nauka2.png', 'title': '\xd0\xbd\xd0\xb0\xd1\x83\xd0\xba\xd0\xb0 2.0'},
{'url': 'telecdn:vip-megahit', 'img': 'http://telecdn.net/img/vip-megahit.png', 'title': 'ViP Megahit'},
{'url': 'telecdn:vip-comedy', 'img': 'http://telecdn.net/img/vip-comedy.png', 'title': 'ViP Comedy'},
{'url': 'telecdn:vip-premiere', 'img': 'http://telecdn.net/img/vip-premiere.png', 'title': 'ViP Premiere'},
{'url': 'telecdn:tnt', 'img': 'http://telecdn.net/img/tnt.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2'},
{'url': 'telecdn:sts', 'img': 'http://telecdn.net/img/sts.png', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1'},
{'url': 'telecdn:stb', 'img': 'http://telecdn.net/img/stb.png', 'title': '\xd0\xa1\xd0\xa2\xd0\x91'},
{'url': 'telecdn:noviy', 'img': 'http://telecdn.net/img/noviy.png', 'title': '\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'telecdn:ren', 'img': 'http://telecdn.net/img/ren.png', 'title': '\xd0\xa0\xd0\x95\xd0\x9d \xd0\xa2\xd0\x92'},
{'url': 'telecdn:eurosport2', 'img': 'http://telecdn.net/img/eurosport2.png', 'title': 'Eurosport 2'},
{'url': 'telecdn:dozhd', 'img': 'http://telecdn.net/img/dozhd.png', 'title': '\xd0\x94\xd0\xbe\xd0\xb6\xd0\xb4\xd1\x8c'},
{'url': 'telecdn:pervij', 'img': 'http://telecdn.net/img/pervij.png', 'title': '\xd0\xbf\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9'},
{'url': 'telecdn:cartoon_network', 'img': 'http://telecdn.net/img/cartoon_network.png', 'title': 'Cartoon Network'},
{'url': 'telecdn:nick', 'img': 'http://telecdn.net/img/nick.png', 'title': 'Nickelodeon'},
{'url': 'telecdn:mult', 'img': 'http://telecdn.net/img/mult.png', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82'},
{'url': 'telecdn:ictv', 'img': 'http://telecdn.net/img/ictv.png', 'title': 'ICTV'},
{'url': 'telecdn:trkukr', 'img': 'http://telecdn.net/img/trkukr.png', 'title': '\xd0\xa2\xd0\xa0\xd0\x9a \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'telecdn:nashfut', 'img': 'http://telecdn.net/img/nashfut.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88 \xd1\x84\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb'},
{'url': 'telecdn:matf1', 'img': 'http://telecdn.net/img/matf1.png', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87 \xd1\x84\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 1'},
{'url': 'telecdn:matf2', 'img': 'http://telecdn.net/img/matf2.png', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87 \xd1\x84\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 2'},
{'url': 'telecdn:pyatnitsa', 'img': 'http://telecdn.net/img/pyatnitsa.png', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd0\xbd\xd0\xb8\xd1\x86\xd0\xb0'},
{'url': 'telecdn:nat-geo-wild', 'img': 'http://telecdn.net/img/nat-geo-wild.png', 'title': 'Nat Geo Wild'},
{'url': 'telecdn:tnt-music', 'img': 'http://telecdn.net/img/tnt-music.png', 'title': '\xd1\x82\xd0\xbd\xd1\x82 music'},
{'url': 'telecdn:2na2', 'img': 'http://telecdn.net/img/2na2.png', 'title': '2x2'},
{'url': 'telecdn:fox', 'img': 'http://telecdn.net/img/fox.png', 'title': 'FOX'},
{'url': 'telecdn:5kanalrus', 'img': 'http://telecdn.net/img/5kanalrus.png', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'telecdn:galaxy', 'img': 'http://telecdn.net/img/galaxy.png', 'title': 'Galaxy TV'},
{'url': 'telecdn:kinotv', 'img': 'http://telecdn.net/img/kinotv.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'telecdn:tnt4', 'img': 'http://telecdn.net/img/tnt4.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa24'},
{'url': 'telecdn:muzhskoekino', 'img': 'http://telecdn.net/img/muzhskoekino.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'telecdn:nst', 'img': 'http://telecdn.net/img/nst.png', 'title': '\xd0\x9d\xd0\xa1\xd0\xa2'},
{'url': 'telecdn:oruzie', 'img': 'http://telecdn.net/img/oruzie.png', 'title': '\xd0\x9e\xd1\x80\xd1\x83\xd0\xb6\xd0\xb8\xd0\xb5'},
{'url': 'telecdn:che', 'img': 'http://telecdn.net/img/che.png', 'title': '\xd0\x9a\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xa7\xd1\x91'},
{'url': 'telecdn:you', 'img': 'http://telecdn.net/img/you.png', 'title': '\xd1\x8e'},
{'url': 'telecdn:tv3', 'img': 'http://telecdn.net/img/tv3.png', 'title': '\xd1\x82\xd0\xb2\xe2\x80\x933'},
{'url': 'telecdn:paramount', 'img': 'http://telecdn.net/img/paramount.png', 'title': 'Paramount Comedy'},
{'url': 'telecdn:moyaplaneta', 'img': 'http://telecdn.net/img/moyaplaneta.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x8f \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'telecdn:disney', 'img': 'http://telecdn.net/img/disney.png', 'title': 'disney'},
{'url': 'telecdn:domash', 'img': 'http://telecdn.net/img/domash.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc\xd0\xb0\xd1\x88\xd0\xbd\xd0\xb8\xd0\xb9'},
{'url': 'telecdn:natgeo', 'img': 'http://telecdn.net/img/natgeo.png', 'title': 'National Geographic'},
{'url': 'telecdn:discovery', 'img': 'http://telecdn.net/img/discovery.png', 'title': 'discovery'},
{'url': 'telecdn:ohryb', 'img': 'http://telecdn.net/img/ohryb.png', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xb0 \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xb0\xd0\xbb\xd0\xba\xd0\xb0'},
{'url': 'telecdn:zvezda', 'img': 'http://telecdn.net/img/zvezda.png', 'title': '\xd0\x97\xd0\xb2\xd0\xb5\xd0\xb7\xd0\xb4\xd0\xb0'},
{'url': 'telecdn:domkino', 'img': 'http://telecdn.net/img/domkino.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'telecdn:zeetv', 'img': 'http://telecdn.net/img/zeetv.png', 'title': 'zee tv'},
{'url': 'telecdn:sony-sci-fi', 'img': 'http://telecdn.net/img/sony-sci-fi.png', 'title': 'Sony Sci-Fi'},
{'url': 'telecdn:ruroman', 'img': 'http://telecdn.net/img/ruroman.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd'},
{'url': 'telecdn:rtrplaneta', 'img': 'http://telecdn.net/img/rtrplaneta.png', 'title': '\xd0\xa0\xd0\xa2\xd0\xa0 \xd0\x9f\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'telecdn:nlotv', 'img': 'http://telecdn.net/img/nlotv.png', 'title': '\xd0\x9d\xd0\x9b\xd0\x9e \xd0\xa2\xd0\x92'},
{'url': 'telecdn:rudetektiv', 'img': 'http://telecdn.net/img/rudetektiv.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb4\xd0\xb5\xd1\x82\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2'},
{'url': 'telecdn:khl', 'img': 'http://telecdn.net/img/khl.png', 'title': '\xd0\x9a\xd0\xa5\xd0\x9b'},
{'url': 'telecdn:karusel', 'img': 'http://telecdn.net/img/karusel.png', 'title': '\xd0\x9a\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd0\xb5\xd0\xbb\xd1\x8c'},
{'url': 'telecdn:history', 'img': 'http://telecdn.net/img/history.png', 'title': 'History'},
{'url': 'telecdn:istoriya', 'img': 'http://telecdn.net/img/istoriya.png', 'title': '\xd0\x98\xd1\x81\xd1\x82\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f'},
{'url': 'telecdn:rubestseller', 'img': 'http://telecdn.net/img/rubestseller.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb1\xd0\xb5\xd1\x81\xd1\x82\xd1\x81\xd0\xb5\xd0\xbb\xd0\xbb\xd0\xb5\xd1\x80'},
{'url': 'telecdn:evrokino', 'img': 'http://telecdn.net/img/evrokino.png', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'telecdn:idx', 'img': 'http://telecdn.net/img/idx.png', 'title': 'ID Xtra'},
{'url': 'telecdn:edatv', 'img': 'http://telecdn.net/img/edatv.png', 'title': '\xd0\x95\xd0\x94\xd0\x90 HD'},
{'url': 'telecdn:matchboets', 'img': 'http://telecdn.net/img/matchboets.png', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87 \xd0\xb1\xd0\xbe\xd0\xb5\xd1\x86'},
{'url': 'telecdn:viasatsport', 'img': 'http://telecdn.net/img/viasatsport.png', 'title': 'Viasat Sport'},
{'url': 'telecdn:Playboy', 'img': 'http://telecdn.net/img/Playboy.png', 'title': 'Playboy TV'},
{'url': 'telecdn:tv1000', 'img': 'http://telecdn.net/img/tv1000.png', 'title': 'TV1000'},
{'url': 'telecdn:tv1000act', 'img': 'http://telecdn.net/img/tv1000act.png', 'title': 'TV1000 Action'},
{'url': 'telecdn:match', 'img': 'http://telecdn.net/img/match.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87 \xd0\xa2\xd0\x92'},
{'url': 'telecdn:futukr1', 'img': 'http://telecdn.net/img/futukr1.png', 'title': '\xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 1 \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'telecdn:futukr2', 'img': 'http://telecdn.net/img/futukr2.png', 'title': '\xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 2 \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'telecdn:via_ex', 'img': 'http://telecdn.net/img/via_ex.png', 'title': 'Viasat Explorer'},
{'url': 'telecdn:via_his', 'img': 'http://telecdn.net/img/via_his.png', 'title': 'Viasat History'},
{'url': 'telecdn:via_nat', 'img': 'http://telecdn.net/img/via_nat.png', 'title': 'Viasat Nature'},
{'url': 'telecdn:mtvru', 'img': 'http://telecdn.net/img/mtvru.png', 'title': 'MTV'},
{'url': 'telecdn:discovery_science', 'img': 'http://telecdn.net/img/discovery_science.png', 'title': 'Discovery science'},
{'url': 'telecdn:kinoxit', 'img': 'http://telecdn.net/img/kinoxit.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x85\xd0\xb8\xd1\x82'},
{'url': 'telecdn:kinomiks', 'img': 'http://telecdn.net/img/kinomiks.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbc\xd0\xb8\xd0\xba\xd1\x81'},
{'url': 'telecdn:kinopremera', 'img': 'http://telecdn.net/img/kinopremera.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbf\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8c\xd0\xb5\xd1\x80\xd0\xb0'},
{'url': 'telecdn:kinosemya', 'img': 'http://telecdn.net/img/kinosemya.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb5\xd0\xbc\xd1\x8c\xd1\x8f'},
{'url': 'telecdn:strachnoe', 'img': 'http://telecdn.net/img/strachnoe.png', 'title': '\xd0\xa1\xd1\x82\xd1\x80\xd0\xb0\xd1\x88\xd0\xbd\xd0\xbe\xd0\xb5 HD'},
{'url': 'telecdn:kinosvidanie', 'img': 'http://telecdn.net/img/kinosvidanie.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb2\xd0\xb8\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'},
{'url': 'telecdn:euronews', 'img': 'http://telecdn.net/img/euronews.png', 'title': 'EuroNews'},
{'url': 'telecdn:24tekhno', 'img': 'http://telecdn.net/img/24tekhno.png', 'title': '24 \xd1\x82\xd0\xb5\xd1\x85\xd0\xbd\xd0\xbe'},
{'url': 'telecdn:rodnoekino', 'img': 'http://telecdn.net/img/rodnoekino.png', 'title': '\xd0\xa0\xd0\xbe\xd0\xb4\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'telecdn:lubkino', 'img': 'http://telecdn.net/img/lubkino.png', 'title': '\xd0\x9b\xd1\x8e\xd0\xb1\xd0\xb8\xd0\xbc\xd0\xbe\xd0\xb5 \xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'telecdn:kinoprem', 'img': 'http://telecdn.net/img/kinoprem.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\x9f\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb8\xd1\x83\xd0\xbc HD'},
{'url': 'telecdn:amc', 'img': 'http://telecdn.net/img/amc.png', 'title': 'AMC'},
{'url': 'telecdn:tv1000rus', 'img': 'http://telecdn.net/img/tv1000rus.png', 'title': '\xd1\x82\xd0\xb2 1000 \xd1\x80\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'telecdn:nostalgiya', 'img': 'http://telecdn.net/img/nostalgiya.png', 'title': '\xd0\x9d\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xb3\xd0\xb8\xd1\x8f'},
{'url': 'telecdn:rline', 'img': 'http://telecdn.net/img/rline.png', 'title': '\xd0\x9a\xd1\x80\xd0\xb0\xd1\x81\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xbb\xd0\xb8\xd0\xbd\xd0\xb8\xd1\x8f'},
{'url': 'telecdn:nashe_nov_kino', 'img': 'http://telecdn.net/img/nashe_nov_kino.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88\xd0\xb5 \xd0\xbd\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'telecdn:setanta_sport', 'img': 'http://telecdn.net/img/setanta_sport.png', 'title': 'setanta sports'},
{'url': 'telecdn:mir', 'img': 'http://telecdn.net/img/mir.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x80'},
]
udata=1559838322.06