[
{'url': 'http://ontivi.net/ictvtv.html', 'img': '', 'title': 'ICTV'},
{'url': 'http://ontivi.net/intertv.html', 'img': '', 'title': '\xd0\x98\xd0\xbd\xd1\x82\xd0\xb5\xd1\x80'},
{'url': 'http://ontivi.net/ntntv.html', 'img': '', 'title': '\xd0\x9d\xd0\xa2\xd0\x9d'},
{'url': 'http://ontivi.net/k1tv.html', 'img': '', 'title': '\xd0\x9a1'},
{'url': 'http://ontivi.net/k2tv.html', 'img': '', 'title': '\xd0\x9a2'},
{'url': 'http://ontivi.net/tvc-tvtv.html', 'img': '', 'title': '\xd1\x82\xd0\xb2\xd1\x86'},
{'url': 'http://ontivi.net/rossiya-1tv.html', 'img': '', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 1'},
{'url': 'http://ontivi.net/5-kanaltv.html', 'img': '', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'http://ontivi.net/krim-1tv.html', 'img': '', 'title': '\xd0\x9a\xd1\x80\xd1\x8b\xd0\xbc 1'},
{'url': 'http://ontivi.net/9-kanal-izrailtv.html', 'img': '', 'title': '9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\x98\xd0\xb7\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbb\xd1\x8c'},
{'url': 'http://ontivi.net/atrtv.html', 'img': '', 'title': 'ATR'},
{'url': 'http://ontivi.net/360tv.html', 'img': '', 'title': '360'},
{'url': 'http://ontivi.net/domkinotv.html', 'img': '', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://ontivi.net/dom-kino-premiumtv.html', 'img': '', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe \xd0\x9f\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb8\xd1\x83\xd0\xbc'},
{'url': 'http://ontivi.net/nash-kinoromantv.html', 'img': '', 'title': '\xd0\x9d\xd0\xb0\xd1\x88 \xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd'},
{'url': 'http://ontivi.net/russkiy-romantv.html', 'img': '', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd'},
{'url': 'http://ontivi.net/russkiy-detektivtv.html', 'img': '', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb4\xd0\xb5\xd1\x82\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2'},
{'url': 'http://ontivi.net/russkiy-bestsellertv.html', 'img': '', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb1\xd0\xb5\xd1\x81\xd1\x82\xd1\x81\xd0\xb5\xd0\xbb\xd0\xbb\xd0\xb5\xd1\x80'},
{'url': 'http://ontivi.net/kino-tvtv.html', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe \xd0\xa2\xd0\x92'},
{'url': 'http://ontivi.net/romantichnoetv.html', 'img': '', 'title': '\xd0\xa0\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd\xd1\x82\xd0\xb8\xd1\x87\xd0\xbd\xd0\xbe\xd0\xb5 HD'},
{'url': 'http://ontivi.net/illuzionrustv.html', 'img': '', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb8\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd'},
{'url': 'http://ontivi.net/illyuzion-pltv.html', 'img': '', 'title': '\xd0\xb8\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd+'},
{'url': 'http://ontivi.net/ostrosjuzhetnoetv.html', 'img': '', 'title': '\xd0\x9e\xd1\x81\xd1\x82\xd1\x80\xd0\xbe\xd1\x81\xd1\x8e\xd0\xb6\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe\xd0\xb5 HD'},
{'url': 'http://ontivi.net/nashe-ktytoetv.html', 'img': '', 'title': '\xd0\x9d\xd0\xb0\xd1\x88\xd0\xb5 \xd0\xba\xd1\x80\xd1\x83\xd1\x82\xd0\xbe\xd0\xb5'},
{'url': 'http://ontivi.net/muzhskoe-kinotv.html', 'img': '', 'title': '\xd0\x9c\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://ontivi.net/kinosvidanietv.html', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb2\xd0\xb8\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'},
{'url': 'http://ontivi.net/kinopremeratv.html', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbf\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8c\xd0\xb5\xd1\x80\xd0\xb0'},
{'url': 'http://ontivi.net/kinomikstv.html', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbc\xd0\xb8\xd0\xba\xd1\x81'},
{'url': 'http://ontivi.net/kinokomediyatv.html', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xba\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f'},
{'url': 'http://ontivi.net/kinosemyatv.html', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb5\xd0\xbc\xd1\x8c\xd1\x8f'},
{'url': 'http://ontivi.net/kinohittv.html', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x85\xd0\xb8\xd1\x82'},
{'url': 'http://ontivi.net/rodnoe-kinotv.html', 'img': '', 'title': '\xd0\xa0\xd0\xbe\xd0\xb4\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://ontivi.net/a1tv.html', 'img': '', 'title': 'A1'},
{'url': 'http://ontivi.net/a2tv.html', 'img': '', 'title': 'A2'},
{'url': 'http://ontivi.net/shokirujuscheetv.html', 'img': '', 'title': '\xd0\xa8\xd0\xbe\xd0\xba\xd0\xb8\xd1\x80\xd1\x83\xd1\x8e\xd1\x89\xd0\xb5\xd0\xb5 HD'},
{'url': 'http://ontivi.net/nsttv.html', 'img': '', 'title': '\xd0\x9d\xd0\xa1\xd0\xa2'},
{'url': 'http://ontivi.net/lyubimoe-kinotv.html', 'img': '', 'title': '\xd0\x9d\xd0\xb0\xd1\x88\xd0\xb5 \xd0\xbb\xd1\x8e\xd0\xb1\xd0\xb8\xd0\xbc\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://ontivi.net/hollywoodtv.html', 'img': '', 'title': 'Hollywood'},
{'url': 'http://ontivi.net/komedijatv.html', 'img': '', 'title': '\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f'},
{'url': 'http://ontivi.net/ntv-hittv.html', 'img': '', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 \xd0\xa5\xd0\xb8\xd1\x82'},
{'url': 'http://ontivi.net/ntv-serialtv.html', 'img': '', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 \xd0\xa1\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb'},
{'url': 'http://ontivi.net/kinoserijatv.html', 'img': '', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb5\xd1\x80\xd0\xb8\xd1\x8f'},
{'url': 'http://ontivi.net/indiya-kinotv.html', 'img': '', 'title': '\xd0\x98\xd0\xbd\xd0\xb4\xd0\xb8\xd0\xb9\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://ontivi.net/zee-tvtv.html', 'img': '', 'title': 'zee tv'},
{'url': 'http://ontivi.net/bollywoodtv.html', 'img': '', 'title': 'Bollywood'},
{'url': 'http://ontivi.net/amctv.html', 'img': '', 'title': 'AMC'},
{'url': 'http://ontivi.net/paramount-channeltv.html', 'img': '', 'title': 'Paramount Channel'},
{'url': 'http://ontivi.net/parcomedytv.html', 'img': '', 'title': 'Paramount Comedy'},
{'url': 'http://ontivi.net/enter-filmtv.html', 'img': '', 'title': 'Enter-\xd1\x84\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xbc'},
{'url': 'http://ontivi.net/evrokinotv.html', 'img': '', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'http://ontivi.net/sonyscifitv.html', 'img': '', 'title': 'Sony Sci-Fi'},
{'url': 'http://ontivi.net/historitv.html', 'img': '', 'title': 'History'},
{'url': 'http://ontivi.net/trofejtv.html', 'img': '', 'title': '\xd0\xa2\xd1\x80\xd0\xbe\xd1\x84\xd0\xb5\xd0\xb9'},
{'url': 'http://ontivi.net/dikiytv.html', 'img': '', 'title': '\xd0\x94\xd0\xb8\xd0\xba\xd0\xb8\xd0\xb9'},
{'url': 'http://ontivi.net/dikaya-ohotatv.html', 'img': '', 'title': '\xd0\x94\xd0\xb8\xd0\xba\xd0\xb0\xd1\x8f \xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xb0 HD'},
{'url': 'http://ontivi.net/travel-adventuretv.html', 'img': '', 'title': 'Travel+adventure'},
{'url': 'http://ontivi.net/morskoytv.html', 'img': '', 'title': '\xd0\x9c\xd0\xbe\xd1\x80\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9'},
{'url': 'http://ontivi.net/ohota-i-rybalkatv.html', 'img': '', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xb0 \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xb0\xd0\xbb\xd0\xba\xd0\xb0'},
{'url': 'http://ontivi.net/ohotnik-i-rybolovtv.html', 'img': '', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2'},
{'url': 'http://ontivi.net/priklyucheniya-hdtv.html', 'img': '', 'title': '\xd0\x9f\xd1\x80\xd0\xb8\xd0\xba\xd0\xbb\xd1\x8e\xd1\x87\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f HD'},
{'url': 'http://ontivi.net/zivaya-planetatv.html', 'img': '', 'title': '\xd0\x96\xd0\xb8\xd0\xb2\xd0\xb0\xd1\x8f \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'http://ontivi.net/galaxytv.html', 'img': '', 'title': 'Galaxy TV'},
{'url': 'http://ontivi.net/zagorodnaya-zhizntv.html', 'img': '', 'title': '\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb4\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xb6\xd0\xb8\xd0\xb7\xd0\xbd\xd1\x8c'},
{'url': 'http://ontivi.net/teatrtv.html', 'img': '', 'title': '\xd0\xa2\xd0\xb5\xd0\xb0\xd1\x82\xd1\x80'},
{'url': 'http://ontivi.net/doktortv.html', 'img': '', 'title': '\xd0\x94\xd0\xbe\xd0\xba\xd1\x82\xd0\xbe\xd1\x80'},
{'url': 'http://ontivi.net/tvoy-domtv.html', 'img': '', 'title': '\xd0\xa2\xd0\xb2\xd0\xbe\xd0\xb9 \xd0\x94\xd0\xbe\xd0\xbc'},
{'url': 'http://ontivi.net/rtg-tvtv.html', 'img': '', 'title': 'RTG TV'},
{'url': 'http://ontivi.net/russki-ekstrimtv.html', 'img': '', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x8d\xd0\xba\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd0\xbc'},
{'url': 'http://ontivi.net/travel-channeltv.html', 'img': '', 'title': 'Travel Channel'},
{'url': 'http://ontivi.net/pervyy-vegetarianskiytv.html', 'img': '', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\x92\xd0\xb5\xd0\xb3\xd0\xb5\xd1\x82\xd0\xb0\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9'},
{'url': 'http://ontivi.net/avtoplystv.html', 'img': '', 'title': '\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe \xd0\x9f\xd0\xbb\xd1\x8e\xd1\x81'},
{'url': 'http://ontivi.net/sovershenno-sekretnotv.html', 'img': '', 'title': '\xd0\xa1\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x80\xd1\x88\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xbe \xd1\x81\xd0\xb5\xd0\xba\xd1\x80\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe'},
{'url': 'http://ontivi.net/moya-planetatv.html', 'img': '', 'title': '\xd0\x9c\xd0\xbe\xd1\x8f \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'http://ontivi.net/oruzhietv.html', 'img': '', 'title': '\xd0\x9e\xd1\x80\xd1\x83\xd0\xb6\xd0\xb8\xd0\xb5'},
{'url': 'http://ontivi.net/istoriyatv.html', 'img': '', 'title': '\xd0\x98\xd1\x81\xd1\x82\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f'},
{'url': 'http://ontivi.net/naukatv.html', 'img': '', 'title': '\xd0\xbd\xd0\xb0\xd1\x83\xd0\xba\xd0\xb0 2.0'},
{'url': 'http://ontivi.net/t24tv.html', 'img': '', 'title': '\xd0\xa224'},
{'url': 'http://ontivi.net/megatv.html', 'img': '', 'title': '\xd0\x9c\xd0\x95\xd0\x93\xd0\x90'},
{'url': 'http://ontivi.net/365tv.html', 'img': '', 'title': '365'},
{'url': 'http://ontivi.net/eda-tvtv.html', 'img': '', 'title': '\xd0\x95\xd0\xb4\xd0\xb0 \xd0\xa2\xd0\x92'},
{'url': 'http://ontivi.net/kuhnya-tvtv.html', 'img': '', 'title': '\xd0\x9a\xd1\x83\xd1\x85\xd0\xbd\xd1\x8f \xd0\xa2\xd0\x92'},
{'url': 'http://ontivi.net/mamatv.html', 'img': '', 'title': '\xd0\x9c\xd0\xb0\xd0\xbc\xd0\xb0'},
{'url': 'http://ontivi.net/sarafantv.html', 'img': '', 'title': '\xd0\xa1\xd0\xb0\xd1\x80\xd0\xb0\xd1\x84\xd0\xb0\xd0\xbd'},
{'url': 'http://ontivi.net/zoomtv.html', 'img': '', 'title': 'zoom'},
{'url': 'http://ontivi.net/xsporttv.html', 'img': '', 'title': 'Xsport'},
{'url': 'http://ontivi.net/sport1tv.html', 'img': '', 'title': '\xd0\xa1\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 1'},
{'url': 'http://ontivi.net/sport2tv.html', 'img': '', 'title': '\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 2'},
{'url': 'http://ontivi.net/boks-tvtv.html', 'img': '', 'title': '\xd0\x91\xd0\xbe\xd0\xba\xd1\x81 \xd0\xa2\xd0\x92'},
{'url': 'http://ontivi.net/sport-uztv.html', 'img': '', 'title': 'Sport UZ'},
{'url': 'http://ontivi.net/tochka-otryvatv.html', 'img': '', 'title': '\xd0\xa2\xd0\xbe\xd1\x87\xd0\xba\xd0\xb0 \xd0\xbe\xd1\x82\xd1\x80\xd1\x8b\xd0\xb2\xd0\xb0'},
{'url': 'http://ontivi.net/super-tennistv.html', 'img': '', 'title': 'Super Tennis HD'},
{'url': 'http://ontivi.net/kazsporttv.html', 'img': '', 'title': 'KazSport'},
{'url': 'http://ontivi.net/multtv.html', 'img': '', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82'},
{'url': 'http://ontivi.net/tlumtv.html', 'img': '', 'title': '\xd0\xa2\xd0\xbb\xd1\x83\xd0\xbc'},
{'url': 'http://ontivi.net/pikseltv.html', 'img': '', 'title': '\xd0\xbf\xd0\xb8\xd0\xba\xd1\x81\xd0\xb5\xd0\xbb\xd1\x8c'},
{'url': 'http://ontivi.net/karuseltv.html', 'img': '', 'title': '\xd0\x9a\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd0\xb5\xd0\xbb\xd1\x8c'},
{'url': 'http://ontivi.net/malyshtv.html', 'img': '', 'title': '\xd0\x9c\xd0\xb0\xd0\xbb\xd1\x8b\xd1\x88'},
{'url': 'http://ontivi.net/anitv.html', 'img': '', 'title': 'Ani'},
{'url': 'http://ontivi.net/tijitv.html', 'img': '', 'title': 'Tiji'},
{'url': 'http://ontivi.net/nickelodeontv.html', 'img': '', 'title': 'Nickelodeon'},
{'url': 'http://ontivi.net/nick-jrtv.html', 'img': '', 'title': 'Nick Jr'},
{'url': 'http://ontivi.net/disneytv.html', 'img': '', 'title': 'disney channel'},
{'url': 'http://ontivi.net/gullitv.html', 'img': '', 'title': 'gulli'},
{'url': 'http://ontivi.net/sojuzmultfilmtv.html', 'img': '', 'title': '\xd0\xa1\xd0\xbe\xd1\x8e\xd0\xb7\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd1\x84\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xbc'},
{'url': 'http://ontivi.net/eralashtv.html', 'img': '', 'title': '\xd0\x95\xd1\x80\xd0\xb0\xd0\xbb\xd0\xb0\xd1\x88'},
{'url': 'http://ontivi.net/multmuzykatv.html', 'img': '', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd0\xbc\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0'},
{'url': 'http://ontivi.net/v-gostyah-u-skazkitv.html', 'img': '', 'title': '\xd0\x92 \xd0\xb3\xd0\xbe\xd1\x81\xd1\x82\xd1\x8f\xd1\x85 \xd1\x83 \xd1\x81\xd0\xba\xd0\xb0\xd0\xb7\xd0\xba\xd0\xb8'},
{'url': 'http://ontivi.net/radost-mojatv.html', 'img': '', 'title': '\xd0\xa0\xd0\xb0\xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c \xd0\xbc\xd0\xbe\xd1\x8f'},
{'url': 'http://ontivi.net/bridge-tvtv.html', 'img': '', 'title': 'Bridge TV'},
{'url': 'http://ontivi.net/otvtv.html', 'img': '', 'title': 'OTV Music'},
{'url': 'http://ontivi.net/music-box-uatv.html', 'img': '', 'title': 'Music Box UA'},
{'url': 'http://ontivi.net/russian-music-boxtv.html', 'img': '', 'title': 'Russian Music Box'},
{'url': 'http://ontivi.net/muz-tvtv.html', 'img': '', 'title': '\xd0\x9c\xd1\x83\xd0\xb7-\xd0\xa2\xd0\x92'},
{'url': 'http://ontivi.net/zharatv.html', 'img': '', 'title': '\xd0\x96\xd0\x90\xd0\xa0\xd0\x90'},
{'url': 'http://ontivi.net/tnt-musiktv.html', 'img': '', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2 MUSIC'},
{'url': 'http://ontivi.net/ru-tvtv.html', 'img': '', 'title': 'RU TV'},
{'url': 'http://ontivi.net/europaplustv.html', 'img': '', 'title': 'Europa Plus TV'},
{'url': 'http://ontivi.net/lya-minortv.html', 'img': '', 'title': '\xd0\xbb\xd1\x8f \xd0\xbc\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x80'},
{'url': 'http://ontivi.net/shansontv.html', 'img': '', 'title': '\xd0\xa8\xd0\xb0\xd0\xbd\xd1\x81\xd0\xbe\xd0\xbd \xd0\xa2\xd0\x92'},
{'url': 'http://ontivi.net/mtv-hitstv.html', 'img': '', 'title': 'MTV Hits'},
{'url': 'http://ontivi.net/mtv-dancetv.html', 'img': '', 'title': 'MTV Dance'},
{'url': 'http://ontivi.net/mtvtv.html', 'img': '', 'title': 'MTV'},
{'url': 'http://ontivi.net/1hdtv.html', 'img': '', 'title': '1HD'},
{'url': 'http://ontivi.net/vh1tv.html', 'img': '', 'title': 'VH1 Europe'},
{'url': 'http://ontivi.net/vh1clastv.html', 'img': '', 'title': 'VH1 Classic'},
{'url': 'http://ontivi.net/mcm-toptv.html', 'img': '', 'title': 'MCM Top'},
{'url': 'http://ontivi.net/112-ukranatv.html', 'img': '', 'title': '112 \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'http://ontivi.net/24-telekanal-novintv.html', 'img': '', 'title': '24 \xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb8\xd0\xbd'},
{'url': 'http://ontivi.net/news-onetv.html', 'img': '', 'title': 'News One'},
{'url': 'http://ontivi.net/5-kanal-ukrainatv.html', 'img': '', 'title': '5 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0'},
{'url': 'http://ontivi.net/espreso-tvtv.html', 'img': '', 'title': '\xd0\xb5\xd1\x81\xd0\xbf\xd1\x80\xd0\xb5\xd1\x81\xd0\xbe tv'},
{'url': 'http://ontivi.net/hromadsketv.html', 'img': '', 'title': '\xd0\x93\xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xb4\xd1\x81\xd1\x8c\xd0\xba\xd0\xb5 \xd0\xa2\xd0\x92'},
{'url': 'http://ontivi.net/prmtv.html', 'img': '', 'title': '\xd0\x9f\xd1\x80\xd1\x8f\xd0\xbc\xd0\xb8\xd0\xb9'},
{'url': 'http://ontivi.net/ua-pervyitv.html', 'img': '', 'title': 'UA \xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9'},
{'url': 'http://ontivi.net/chp-infotv.html', 'img': '', 'title': '\xd0\xa7\xd0\x9f.INFO'},
{'url': 'http://ontivi.net/bbc-world-newstv.html', 'img': '', 'title': 'BBC News'},
]
udata=1579785525.26