[
{'url': 'smotr:europaplus', 'group': '', 'img': 'http://tele.smotr.online/img/europaplus.jpg', 'title': 'Europa Plus TV'},
{'url': 'smotr:mezzolivehd', 'group': '', 'img': 'http://tele.smotr.online/img/mezzolivehd.jpg', 'title': 'Mezzo Live HD'},
{'url': 'smotr:mtvdance', 'group': '', 'img': 'http://tele.smotr.online/img/mtvdance.jpg', 'title': 'MTV Dance'},
{'url': 'smotr:mtvrocks', 'group': '', 'img': 'http://tele.smotr.online/img/mtvrocks.jpg', 'title': 'MTV Rocks'},
{'url': 'smotr:rutv', 'group': '', 'img': 'http://tele.smotr.online/img/rutv.jpg', 'title': 'RU TV'},
{'url': 'smotr:vh1', 'group': '', 'img': 'http://tele.smotr.online/img/vh1.jpg', 'title': 'VH1'},
{'url': 'smotr:vh1classic', 'group': '', 'img': 'http://tele.smotr.online/img/vh1classic.jpg', 'title': 'VH1 Classic'},
{'url': 'smotr:muz1', 'group': '', 'img': 'http://tele.smotr.online/img/muz1.jpg', 'title': '\xd0\x9c\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0 \xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd0\xbe\xd0\xb3\xd0\xbe'},
{'url': 'smotr:tntmusic', 'group': '', 'img': 'http://tele.smotr.online/img/tntmusic.jpg', 'title': '\xd1\x82\xd0\xbd\xd1\x82 music'},
{'url': 'smotr:8tv', 'group': '', 'img': 'http://tele.smotr.online/img/8tv.jpg', 'title': '8 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'smotr:fashiontv', 'group': '', 'img': 'http://tele.smotr.online/img/fashiontv.jpg', 'title': 'Fashion TV'},
{'url': 'smotr:mtvru', 'group': '', 'img': 'http://tele.smotr.online/img/mtvru.jpg', 'title': 'MTV \xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f'},
{'url': 'smotr:voprosyiotvety', 'group': '', 'img': 'http://tele.smotr.online/img/voprosyiotvety.jpg', 'title': '\xd0\x92\xd0\xbe\xd0\xbf\xd1\x80\xd0\xbe\xd1\x81\xd1\x8b \xd0\xb8 \xd0\xbe\xd1\x82\xd0\xb2\xd0\xb5\xd1\x82\xd1\x8b'},
{'url': 'smotr:friday', 'group': '', 'img': 'http://tele.smotr.online/img/friday.jpg', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd0\xbd\xd0\xb8\xd1\x86\xd0\xb0'},
{'url': 'smotr:sarafan', 'group': '', 'img': 'http://tele.smotr.online/img/sarafan.jpg', 'title': '\xd1\x81\xd0\xb0\xd1\x80\xd0\xb0\xd1\x84\xd0\xb0\xd0\xbd \xd1\x82\xd0\xb2'},
{'url': 'smotr:super', 'group': '', 'img': 'http://tele.smotr.online/img/super.jpg', 'title': '\xd1\x81\xd1\x83\xd0\xbf\xd0\xb5\xd1\x80'},
{'url': 'smotr:tnt', 'group': '', 'img': 'http://tele.smotr.online/img/tnt.jpg', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2'},
{'url': 'smotr:tnthd', 'group': '', 'img': 'http://tele.smotr.online/img/tnthd.jpg', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2 HD'},
{'url': 'smotr:tnt4', 'group': '', 'img': 'http://tele.smotr.online/img/tnt4.jpg', 'title': '\xd0\xa2\xd0\x9d\xd0\xa24'},
{'url': 'smotr:u', 'group': '', 'img': 'http://tele.smotr.online/img/u.jpg', 'title': '\xd0\xae'},
{'url': 'smotr:amedia1', 'group': '', 'img': 'http://tele.smotr.online/img/amedia1.jpg', 'title': 'amedia 1'},
{'url': 'smotr:amedia1hd', 'group': '', 'img': 'http://tele.smotr.online/img/amedia1hd.jpg', 'title': 'Amedia 1 HD'},
{'url': 'smotr:amediahithd', 'group': '', 'img': 'http://tele.smotr.online/img/amediahithd.jpg', 'title': 'Amedia Hit HD'},
{'url': 'smotr:amediapremium', 'group': '', 'img': 'http://tele.smotr.online/img/amediapremium.jpg', 'title': 'Amedia Premium'},
{'url': 'smotr:amediapremiumhd', 'group': '', 'img': 'http://tele.smotr.online/img/amediapremiumhd.jpg', 'title': 'Amedia Premium HD'},
{'url': 'smotr:fox', 'group': '', 'img': 'http://tele.smotr.online/img/fox.jpg', 'title': 'Fox'},
{'url': 'smotr:foxhd', 'group': '', 'img': 'http://tele.smotr.online/img/foxhd.jpg', 'title': 'Fox HD'},
{'url': 'smotr:foxlife', 'group': '', 'img': 'http://tele.smotr.online/img/foxlife.jpg', 'title': 'Fox Life'},
{'url': 'smotr:foxlifehd', 'group': '', 'img': 'http://tele.smotr.online/img/foxlifehd.jpg', 'title': 'Fox Life HD'},
{'url': 'smotr:paramount', 'group': '', 'img': 'http://tele.smotr.online/img/paramount.jpg', 'title': 'Paramount Channel'},
{'url': 'smotr:paramountcomedy', 'group': '', 'img': 'http://tele.smotr.online/img/paramountcomedy.jpg', 'title': 'Paramount Comedy'},
{'url': 'smotr:paramountcomedyhd', 'group': '', 'img': 'http://tele.smotr.online/img/paramountcomedyhd.jpg', 'title': 'Paramount Comedy HD'},
{'url': 'smotr:set', 'group': '', 'img': 'http://tele.smotr.online/img/set.jpg', 'title': 'SET'},
{'url': 'smotr:sethd', 'group': '', 'img': 'http://tele.smotr.online/img/sethd.jpg', 'title': 'SET HD'},
{'url': 'smotr:sonyscifi', 'group': '', 'img': 'http://tele.smotr.online/img/sonyscifi.jpg', 'title': 'Sony Sci-Fi'},
{'url': 'smotr:sonyturbo', 'group': '', 'img': 'http://tele.smotr.online/img/sonyturbo.jpg', 'title': 'Sony Turbo'},
{'url': 'smotr:spikehd', 'group': '', 'img': 'http://tele.smotr.online/img/spikehd.jpg', 'title': 'Spike HD'},
{'url': 'smotr:tv21', 'group': '', 'img': 'http://tele.smotr.online/img/tv21.jpg', 'title': 'tv xxi'},
{'url': 'smotr:domkino', 'group': '', 'img': 'http://tele.smotr.online/img/domkino.jpg', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'smotr:domkinopremiumhd', 'group': '', 'img': 'http://tele.smotr.online/img/domkinopremiumhd.jpg', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe \xd0\x9f\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb8\xd1\x83\xd0\xbc HD'},
{'url': 'smotr:india', 'group': '', 'img': 'http://tele.smotr.online/img/india.jpg', 'title': '\xd0\x98\xd0\xbd\xd0\xb4\xd0\xb8\xd0\xb9\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'smotr:nashkinoromanhd', 'group': '', 'img': 'http://tele.smotr.online/img/nashkinoromanhd.jpg', 'title': '\xd0\x9d\xd0\xb0\xd1\x88 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd HD'},
{'url': 'smotr:ntvserial', 'group': '', 'img': 'http://tele.smotr.online/img/ntvserial.jpg', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 \xd0\xa1\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb0\xd0\xbb'},
{'url': 'smotr:ostrosyuzhetnoehd', 'group': '', 'img': 'http://tele.smotr.online/img/ostrosyuzhetnoehd.jpg', 'title': '\xd0\x9e\xd1\x81\xd1\x82\xd1\x80\xd0\xbe\xd1\x81\xd1\x8e\xd0\xb6\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe\xd0\xb5 HD'},
{'url': 'smotr:russkayakomediya', 'group': '', 'img': 'http://tele.smotr.online/img/russkayakomediya.jpg', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb0\xd1\x8f \xd0\xba\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f'},
{'url': 'smotr:russkiyillusion', 'group': '', 'img': 'http://tele.smotr.online/img/russkiyillusion.jpg', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb8\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd'},
{'url': 'smotr:tv3', 'group': '', 'img': 'http://tele.smotr.online/img/tv3.jpg', 'title': '\xd1\x82\xd0\xb2 3'},
{'url': 'smotr:euronews', 'group': '', 'img': 'http://tele.smotr.online/img/euronews.jpg', 'title': 'EuroNews'},
{'url': 'smotr:tvrain', 'group': '', 'img': 'http://tele.smotr.online/img/tvrain.jpg', 'title': '\xd0\x94\xd0\xbe\xd0\xb6\xd0\xb4\xd1\x8c'},
{'url': 'smotr:tvrainhd', 'group': '', 'img': 'http://tele.smotr.online/img/tvrainhd.jpg', 'title': '\xd0\x94\xd0\xbe\xd0\xb6\xd0\xb4\xd1\x8c HD'},
{'url': 'smotr:davincilearning', 'group': '', 'img': 'http://tele.smotr.online/img/davincilearning.jpg', 'title': 'Da Vinci Learning'},
{'url': 'smotr:discovery', 'group': '', 'img': 'http://tele.smotr.online/img/discovery.jpg', 'title': 'Discovery Channel'},
{'url': 'smotr:discoveryhd', 'group': '', 'img': 'http://tele.smotr.online/img/discoveryhd.jpg', 'title': 'Discovery Channel HD'},
{'url': 'smotr:discoveryscience', 'group': '', 'img': 'http://tele.smotr.online/img/discoveryscience.jpg', 'title': 'Discovery Science'},
{'url': 'smotr:discoverysciencehd', 'group': '', 'img': 'http://tele.smotr.online/img/discoverysciencehd.jpg', 'title': 'Discovery Science HD'},
{'url': 'smotr:eurekahd', 'group': '', 'img': 'http://tele.smotr.online/img/eurekahd.jpg', 'title': 'Eureka HD'},
{'url': 'smotr:hdlife', 'group': '', 'img': 'http://tele.smotr.online/img/hdlife.jpg', 'title': 'HD Life'},
{'url': 'smotr:history', 'group': '', 'img': 'http://tele.smotr.online/img/history.jpg', 'title': 'history channel'},
{'url': 'smotr:historyhd', 'group': '', 'img': 'http://tele.smotr.online/img/historyhd.jpg', 'title': 'history channel hd'},
{'url': 'smotr:natgeowild', 'group': '', 'img': 'http://tele.smotr.online/img/natgeowild.jpg', 'title': 'Nat Geo Wild'},
{'url': 'smotr:natgeowildhd', 'group': '', 'img': 'http://tele.smotr.online/img/natgeowildhd.jpg', 'title': 'Nat Geo Wild HD'},
{'url': 'smotr:natgeohd', 'group': '', 'img': 'http://tele.smotr.online/img/natgeohd.jpg', 'title': 'National Geographic HD'},
{'url': 'smotr:rtg', 'group': '', 'img': 'http://tele.smotr.online/img/rtg.jpg', 'title': 'RTG TV'},
{'url': 'smotr:traveladventurehd', 'group': '', 'img': 'http://tele.smotr.online/img/traveladventurehd.jpg', 'title': 'Travel + adventure HD'},
{'url': 'smotr:travelchannelhd', 'group': '', 'img': 'http://tele.smotr.online/img/travelchannelhd.jpg', 'title': 'Travel Channel HD'},
{'url': 'smotr:viasatexplore', 'group': '', 'img': 'http://tele.smotr.online/img/viasatexplore.jpg', 'title': 'viasat explore'},
{'url': 'smotr:viasathistory', 'group': '', 'img': 'http://tele.smotr.online/img/viasathistory.jpg', 'title': 'Viasat History'},
{'url': 'smotr:viasatnaturehistoryhd', 'group': '', 'img': 'http://tele.smotr.online/img/viasatnaturehistoryhd.jpg', 'title': 'Viasat Nature-History HD'},
{'url': 'smotr:animalfamilyhd', 'group': '', 'img': 'http://tele.smotr.online/img/animalfamilyhd.jpg', 'title': '\xd0\x92 \xd0\xbc\xd0\xb8\xd1\x80\xd0\xb5 \xd0\xb6\xd0\xb8\xd0\xb2\xd0\xbe\xd1\x82\xd0\xbd\xd1\x8b\xd1\x85 HD'},
{'url': 'smotr:timetv', 'group': '', 'img': 'http://tele.smotr.online/img/timetv.jpg', 'title': '\xd0\x92\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f'},
{'url': 'smotr:liveplanet', 'group': '', 'img': 'http://tele.smotr.online/img/liveplanet.jpg', 'title': '\xd0\x96\xd0\xb8\xd0\xb2\xd0\xb0\xd1\x8f \xd0\x9f\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'smotr:istoriya', 'group': '', 'img': 'http://tele.smotr.online/img/istoriya.jpg', 'title': '\xd0\x98\xd1\x81\xd1\x82\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f'},
{'url': 'smotr:moyaplaneta', 'group': '', 'img': 'http://tele.smotr.online/img/moyaplaneta.jpg', 'title': '\xd0\x9c\xd0\xbe\xd1\x8f \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'smotr:nauka', 'group': '', 'img': 'http://tele.smotr.online/img/nauka.jpg', 'title': '\xd0\xbd\xd0\xb0\xd1\x83\xd0\xba\xd0\xb0 2.0'},
{'url': 'smotr:teletravel', 'group': '', 'img': 'http://tele.smotr.online/img/teletravel.jpg', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xbf\xd1\x83\xd1\x82\xd0\xb5\xd1\x88\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xb8\xd1\x8f'},
{'url': 'smotr:disney', 'group': '', 'img': 'http://tele.smotr.online/img/disney.jpg', 'title': 'disney channel'},
{'url': 'smotr:gulli', 'group': '', 'img': 'http://tele.smotr.online/img/gulli.jpg', 'title': 'Gulli Girl'},
{'url': 'smotr:jimjam', 'group': '', 'img': 'http://tele.smotr.online/img/jimjam.jpg', 'title': 'JimJam'},
{'url': 'smotr:nickjr', 'group': '', 'img': 'http://tele.smotr.online/img/nickjr.jpg', 'title': 'nick jr.'},
{'url': 'smotr:nickelodeon', 'group': '', 'img': 'http://tele.smotr.online/img/nickelodeon.jpg', 'title': 'Nickelodeon'},
{'url': 'smotr:nickelodeonhd', 'group': '', 'img': 'http://tele.smotr.online/img/nickelodeonhd.jpg', 'title': 'Nickelodeon HD'},
{'url': 'smotr:tiji', 'group': '', 'img': 'http://tele.smotr.online/img/tiji.jpg', 'title': 'TiJi'},
{'url': 'smotr:skazka', 'group': '', 'img': 'http://tele.smotr.online/img/skazka.jpg', 'title': '\xd0\x92 \xd0\xb3\xd0\xbe\xd1\x81\xd1\x82\xd1\x8f\xd1\x85 \xd1\x83 \xd1\x81\xd0\xba\xd0\xb0\xd0\xb7\xd0\xba\xd0\xb8'},
{'url': 'smotr:karusel', 'group': '', 'img': 'http://tele.smotr.online/img/karusel.jpg', 'title': '\xd0\x9a\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd0\xb5\xd0\xbb\xd1\x8c'},
{'url': 'smotr:detskiy', 'group': '', 'img': 'http://tele.smotr.online/img/detskiy.jpg', 'title': '\xd0\xa3\xd0\xbd\xd0\xb8\xd0\xba\xd1\x83\xd0\xbc'},
{'url': 'smotr:extremesports', 'group': '', 'img': 'http://tele.smotr.online/img/extremesports.jpg', 'title': 'Extreme Sports'},
{'url': 'smotr:viasatsporthd', 'group': '', 'img': 'http://tele.smotr.online/img/viasatsporthd.jpg', 'title': 'Viasat Sport HD'},
{'url': 'smotr:outdoor', 'group': '', 'img': 'http://tele.smotr.online/img/outdoor.jpg', 'title': 'Outdoor Channel'},
{'url': 'smotr:outdoorhd', 'group': '', 'img': 'http://tele.smotr.online/img/outdoorhd.jpg', 'title': 'Outdoor Channel HD'},
{'url': 'smotr:avto24', 'group': '', 'img': 'http://tele.smotr.online/img/avto24.jpg', 'title': '\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe 24'},
{'url': 'smotr:morskoi', 'group': '', 'img': 'http://tele.smotr.online/img/morskoi.jpg', 'title': '\xd0\x9c\xd0\xbe\xd1\x80\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9'},
{'url': 'smotr:ohotairybalka', 'group': '', 'img': 'http://tele.smotr.online/img/ohotairybalka.jpg', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xb0 \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xb0\xd0\xbb\xd0\xba\xd0\xb0'},
{'url': 'smotr:ohotnikirybolovhd', 'group': '', 'img': 'http://tele.smotr.online/img/ohotnikirybolovhd.jpg', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2 HD'},
{'url': 'smotr:zvezda', 'group': '', 'img': 'http://tele.smotr.online/img/zvezda.jpg', 'title': '\xd0\x97\xd0\xb2\xd0\xb5\xd0\xb7\xd0\xb4\xd0\xb0'},
{'url': 'smotr:inter', 'group': '', 'img': 'http://tele.smotr.online/img/inter.jpg', 'title': '\xd0\x98\xd0\xbd\xd1\x82\xd0\xb5\xd1\x80'},
{'url': 'smotr:mirhd', 'group': '', 'img': 'http://tele.smotr.online/img/mirhd.jpg', 'title': '\xd0\x9c\xd0\xb8\xd1\x80 HD'},
{'url': 'smotr:ntvhd', 'group': '', 'img': 'http://tele.smotr.online/img/ntvhd.jpg', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 HD'},
{'url': 'smotr:otr', 'group': '', 'img': 'http://tele.smotr.online/img/otr.jpg', 'title': '\xd0\x9e\xd0\xa2\xd0\xa0'},
{'url': 'smotr:russiahd', 'group': '', 'img': 'http://tele.smotr.online/img/russiahd.jpg', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f HD'},
]
udata=1606587837.84