[
{'url': 'tvplus:perviyhd', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/m1hd.png', 'title': '\xd0\xbf\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 hd'},
{'url': 'tvplus:russiahd', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mrhd.png', 'title': '\xd1\x80\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 1 hd'},
{'url': 'tvplus:matchtv', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mmatch.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87 \xd0\xa2\xd0\x92'},
{'url': 'tvplus:ntv', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mntv.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x92'},
{'url': 'tvplus:kanal5', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mspb.png', 'title': '5 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb'},
{'url': 'tvplus:kultura', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mrusk.png', 'title': '\xd0\x9a\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd1\x83\xd1\x80\xd0\xb0'},
{'url': 'tvplus:russia24', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mr24.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 24'},
{'url': 'tvplus:karusel', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mcar.png', 'title': '\xd0\x9a\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd0\xb5\xd0\xbb\xd1\x8c'},
{'url': 'tvplus:otr', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/motr.png', 'title': '\xd0\x9e\xd0\xa2\xd0\xa0'},
{'url': 'tvplus:tvc', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mtvc.png', 'title': '\xd1\x82\xd0\xb2\xd1\x86'},
{'url': 'tvplus:ren', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mrentv.png', 'title': '\xd0\xa0\xd0\xb5\xd0\xbd \xd0\xa2\xd0\x92'},
{'url': 'tvplus:spas', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mspas.png', 'title': '\xd1\x81\xd0\xbf\xd0\xb0\xd1\x81'},
{'url': 'tvplus:sts', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/msts.png', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1'},
{'url': 'tvplus:dom', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mdom.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc\xd0\xb0\xd1\x88\xd0\xbd\xd0\xb8\xd0\xb9'},
{'url': 'tvplus:tv3', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mtv3.png', 'title': '\xd1\x82\xd0\xb23'},
{'url': 'tvplus:friday', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mpyatnica.png', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd0\xbd\xd0\xb8\xd1\x86\xd0\xb0'},
{'url': 'tvplus:zvezda', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mzvezda.png', 'title': '\xd0\x97\xd0\xb2\xd0\xb5\xd0\xb7\xd0\xb4\xd0\xb0'},
{'url': 'tvplus:mir', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mmir.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x80'},
{'url': 'tvplus:tnt', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mtnt.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2'},
{'url': 'tvplus:muztv', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mmuztv.png', 'title': '\xd0\xbc\xd1\x83\xd0\xb7 \xd1\x82\xd0\xb2'},
{'url': 'tvplus:europaplustv', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/europaplustv.png', 'title': 'Europa Plus TV'},
{'url': 'tvplus:tntmusic', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mtntmusic.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2 Music'},
{'url': 'tvplus:bridgetv', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/bridgetv.png', 'title': 'Bridge TV'},
{'url': 'tvplus:bridgetvrushit', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/bridgetvrushit.png', 'title': 'Bridge TV \xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x85\xd0\xb8\xd1\x82'},
{'url': 'tvplus:bridgetvclassic', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/bridgetvclassic.png', 'title': 'Bridge TV Classic'},
{'url': 'tvplus:bridgetvhits', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/bridgetvhits.png', 'title': 'Bridge TV Hits'},
{'url': 'tvplus:russianmb', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/russianmb.png', 'title': 'Russian music box'},
{'url': 'tvplus:russianmbhd', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/russianmbhd.png', 'title': 'Russian Music Box HD'},
{'url': 'tvplus:yu', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/yu.png', 'title': '\xd0\xae'},
{'url': 'tvplus:t2x2', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/t2x2.jpg', 'title': '2x2'},
{'url': 'tvplus:tnt4', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/tnt4.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa24'},
{'url': 'tvplus:super', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/supertv.jpg', 'title': '\xd1\x81\xd1\x83\xd0\xbf\xd0\xb5\xd1\x80'},
{'url': 'tvplus:stslove', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/stslove.png', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1 Love'},
{'url': 'tvplus:che', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/che.png', 'title': '\xd0\xa7\xd0\xb5'},
{'url': 'tvplus:kinopremier', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/kinopremier.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xbf\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8c\xd0\xb5\xd1\x80\xd0\xb0'},
{'url': 'tvplus:kinohit', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/kinohit.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x85\xd0\xb8\xd1\x82'},
{'url': 'tvplus:kinofamily', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/kinofamily.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb5\xd0\xbc\xd1\x8c\xd1\x8f'},
{'url': 'tvplus:kinolove', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/kinolove.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb2\xd0\xb8\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'},
{'url': 'tvplus:kinoman', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/kinoman.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'tvplus:matchfootball1', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/matchfootball1.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 1'},
{'url': 'tvplus:matchfootball2', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/matchfootball2.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 2'},
{'url': 'tvplus:matchfootball2', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/matchfootball3.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 3'},
{'url': 'tvplus:matchpremier', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/matchpremier.png', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87! \xd0\xbf\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8c\xd0\xb5\xd1\x80'},
{'url': 'tvplus:matcharena', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/matcharena.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\x90\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb0'},
{'url': 'tvplus:matchgame', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/matchgame.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\x98\xd0\xb3\xd1\x80\xd0\xb0'},
{'url': 'tvplus:matchoursport', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/matchoursport.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\xa1\xd1\x82\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb0'},
{'url': 'tvplus:matchfighter', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/matchfighter.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\x91\xd0\xbe\xd0\xb5\xd1\x86'},
{'url': 'tvplus:m1global', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/m1global.png', 'title': 'M-1 Global'},
{'url': 'tvplus:boxtv', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/boxtv.png', 'title': '\xd0\x91\xd0\xbe\xd0\xba\xd1\x81 \xd0\xa2\xd0\x92'},
{'url': 'tvplus:ntvhd', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/ntvhd.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 HD'},
{'url': 'tvplus:mirhd', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mmir.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x80 HD'},
{'url': 'tvplus:tnthd', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/tnthd.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2 HD'},
{'url': 'tvplus:matchtvhd', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/matchtvhd.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87 \xd0\xa2\xd0\x92 HD'},
{'url': 'tvplus:matchfootball1hd', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/matchfootball1hd.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 1 HD'},
{'url': 'tvplus:matchfootball2hd', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/matchfootball2hd.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 2 HD'},
{'url': 'tvplus:matchfootball3hd', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/matchfootball3hd.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 3 HD'},
{'url': 'tvplus:matchpremierhd', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/matchpremierhd.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\x9f\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8c\xd0\xb5\xd1\x80 HD'},
{'url': 'tvplus:matcharenahd', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/matcharenahd.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\x90\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb0 HD'},
{'url': 'tvplus:matchgamehd', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/matchgamehd.png', 'title': '\xd0\xbc\xd0\xb0\xd1\x82\xd1\x87! \xd0\xb8\xd0\xb3\xd1\x80\xd0\xb0 hd'},
{'url': 'tvplus:moscow24', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mm24.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0 24'},
{'url': 'tvplus:disney', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/disney.png', 'title': 'disney'},
{'url': 'tvplus:iz', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/iz.png', 'title': '\xd0\x98\xd0\xb7\xd0\xb2\xd0\xb5\xd1\x81\xd1\x82\xd0\xb8\xd1\x8f'},
{'url': 'tvplus:bash24', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/bash24.png', 'title': '\xd0\x91\xd0\xb0\xd1\x88\xd0\xba\xd0\xbe\xd1\x80\xd1\x82\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd 24'},
{'url': 'tvplus:otv24', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/otv24.png', 'title': '\xd0\x9e\xd0\xa2\xd0\x9224'},
{'url': 'tvplus:rt', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mrthd.png', 'title': 'russia today hd'},
{'url': 'tvplus:rtdocru', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mrtd.png', 'title': 'RT \xd0\x94 HD'},
{'url': 'tvplus:hdmedia', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/hdmedia.png', 'title': 'hd media'},
{'url': 'tvplus:kinomenu', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/kinomenu.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe\xd0\x9c\xd0\xb5\xd0\xbd\xd1\x8e HD'},
{'url': 'tvplus:unknownplanet', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/unknownplanet.png', 'title': '\xd0\x9d\xd0\xb5\xd0\xb8\xd0\xb7\xd0\xb2\xd0\xb5\xd1\x81\xd1\x82\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0'},
{'url': 'tvplus:terra', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/terra.png', 'title': '\xd0\xa2\xd0\xb5\xd1\x80\xd1\x80\xd0\xb0 \xd0\x98\xd0\xbd\xd0\xba\xd0\xbe\xd0\xb3\xd0\xbd\xd0\xb8\xd1\x82\xd0\xb0'},
{'url': 'tvplus:patriot', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/patriot.png', 'title': '\xd0\x9f\xd0\xb0\xd1\x82\xd1\x80\xd0\xb8\xd0\xbe\xd1\x82'},
{'url': 'tvplus:classickino', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/classickino.png', 'title': '\xd0\x9a\xd0\xbb\xd0\xb0\xd1\x81\xd1\x81\xd0\xb8\xd0\xba\xd0\xb0 \xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'tvplus:sovmov', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/sovmov.png', 'title': '\xd0\xa1\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x82\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe'},
{'url': 'tvplus:rusmult', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/rusmult.png', 'title': '\xd0\xa1\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5 \xd0\xbc\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd1\x84\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xbc\xd1\x8b'},
{'url': 'tvplus:skazki', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/skazki.png', 'title': '\xd0\xa1\xd0\xba\xd0\xb0\xd0\xb7\xd0\xba\xd0\xb8 \xd0\x97\xd0\xb0\xd0\xb9\xd0\xba\xd0\xb8'},
{'url': 'tvplus:joycook', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/joycook.png', 'title': 'Joy Cook'},
{'url': 'tvplus:radost', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mradost.png', 'title': '\xd0\xa0\xd0\xb0\xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c \xd0\xbc\xd0\xbe\xd1\x8f'},
{'url': 'tvplus:probusiness', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/probusiness.png', 'title': '\xd0\x9f\xd1\x80\xd0\xbe \xd0\x91\xd0\xb8\xd0\xb7\xd0\xbd\xd0\xb5\xd1\x81'},
{'url': 'tvplus:tochkatv', 'group': '', 'img': 'https://www.tvplusonline.ru/assets/img/channels/list/mtochkatv.png', 'title': '\xd0\xa2\xd0\xbe\xd1\x87\xd0\xba\xd0\xb0 \xd0\xa2\xd0\x92'},
]
udata=1575635418.65